# SPDX-License-Identifier: AGPL-3.0-or-later
"""`localm run X` must NEVER answer with a different model.

When a background server for this directory serves model Y, `localm run X`
refuses rather than streaming a reply generated by Y. These tests drive the real
`run` command (CliRunner), stubbing only the network seam (attach discovery, the
/v1/models probe, and the HTTP engine), so the real run() control flow decides
what happens.
"""

from unittest.mock import MagicMock

import pytest
from click.testing import CliRunner

from localm.audit import SessionMode
from localm.cli.chat import run


@pytest.fixture
def patched(monkeypatch):
    """Stub the attach seam and hand the test control of the probe result + a
    spy HttpEngine, so it can assert whether an attach/stream to the server ever
    happened."""
    fake_target = {"base_url": "http://127.0.0.1:8642/v1", "token": "tok"}
    engine_spy = MagicMock(name="HttpEngine")

    monkeypatch.setattr("localm.instances.attach_target",
                        lambda *a, **k: fake_target)
    monkeypatch.setattr("localm.instances.resolve_root_dir", lambda *a, **k: ".")
    monkeypatch.setattr("localm.inference.http_engine.HttpEngine", engine_spy)
    monkeypatch.setattr("localm.audit.effective_mode",
                        lambda *a, **k: SessionMode.LOG)

    def set_status(state, active):
        monkeypatch.setattr("localm.inference.http_engine.remote_model_status",
                            lambda *a, **k: (state, active))

    return engine_spy, set_status


def _flat(output: str) -> str:
    """Collapse rich line-wrapping so phrase assertions are wrap-proof."""
    return " ".join(output.split()).lower()


def test_run_refuses_when_server_serves_a_different_model(patched):
    engine_spy, set_status = patched
    set_status("loaded", "qwen2.5-0.5b")   # server serves Y

    result = CliRunner().invoke(
        run, ["SmolLM2-135M", "-p", "What color is the sky?"])

    flat = _flat(result.output)
    # It refuses (non-zero exit) instead of proceeding.
    assert result.exit_code == 1, result.output
    # It never attaches/streams - so it cannot emit Y's answer.
    assert not engine_spy.called, "must NOT build an HttpEngine to the wrong model"
    # The message names both models and the way out.
    assert "smollm2-135m" in flat
    assert "qwen2.5-0.5b" in flat
    assert "--no-server" in flat


def test_run_attaches_when_server_serves_the_requested_model(patched):
    engine_spy, set_status = patched
    set_status("loaded", "SmolLM2-135M")   # server already serves X

    result = CliRunner().invoke(run, ["SmolLM2-135M", "-p", "hi"])

    flat = _flat(result.output)
    assert result.exit_code == 0, result.output
    assert engine_spy.called, "should attach to the server serving the same model"
    # No refusal wording on the happy path.
    assert "not the requested" not in flat
    assert "--no-server" not in flat


def test_run_refuses_when_server_has_no_model_loaded(patched):
    engine_spy, set_status = patched
    set_status("empty", None)   # server up, nothing loaded

    result = CliRunner().invoke(run, ["SmolLM2-135M", "-p", "hi"])

    flat = _flat(result.output)
    assert result.exit_code == 1, result.output
    assert not engine_spy.called, "an empty server cannot serve the requested model"
    assert "smollm2-135m" in flat
    assert "--no-server" in flat


def test_run_attaches_quietly_when_model_is_unknown(patched):
    # A chat-scoped attach token cannot read /v1/models -> ("unknown", None),
    # which does not refuse: it attaches quietly.
    engine_spy, set_status = patched
    set_status("unknown", None)

    result = CliRunner().invoke(run, ["SmolLM2-135M", "-p", "hi"])

    assert result.exit_code == 0, result.output
    assert engine_spy.called, "unknown model state must still attach"


def test_run_no_server_does_not_trigger_the_conflict_refusal(patched, monkeypatch):
    # --no-server opts out of attaching entirely, so a running server serving Y
    # is irrelevant and the conflict refusal does not fire.
    engine_spy, set_status = patched
    set_status("loaded", "qwen2.5-0.5b")
    # attach_target is not consulted under --no-server; this stub raises if it
    # is, so the opt-out has to short-circuit before the probe.
    monkeypatch.setattr(
        "localm.instances.attach_target",
        lambda *a, **k: (_ for _ in ()).throw(AssertionError("consulted under --no-server")))

    result = CliRunner().invoke(
        run, ["SmolLM2-135M", "-p", "hi", "--no-server"])

    flat = _flat(result.output)
    assert "qwen2.5-0.5b" not in flat, "must not mention the server's model"
    assert "the localm server here serves" not in flat
