# SPDX-License-Identifier: AGPL-3.0-or-later
"""Graceful failure + the autogenerated, editable bug report (localm/bugreport)."""

from __future__ import annotations

import os
import pathlib
import stat
import sys
import threading
import time
import types
from urllib.parse import unquote

import pytest
from click.testing import CliRunner

from localm import bugreport


# --------------------------- the typed error ------------------------------ #

def test_localm_error_carries_summary_reason_context():
    e = bugreport.LocalmError("it broke", reason="because X", context={"a": 1})
    assert e.summary == "it broke"
    assert e.reason == "because X"
    assert e.context == {"a": 1}
    assert str(e) == "it broke"


# --------------------------- diagnostics ---------------------------------- #

def test_collect_diagnostics_is_safe_and_useful():
    diag = bugreport.collect_diagnostics({"operation": "test", "backend": "cuda"})
    assert "python" in diag and "platform" in diag
    assert diag.get("operation") == "test"
    assert diag.get("backend") == "cuda"
    # gpu_vendors is always present (possibly empty), never raises.
    assert "gpu_vendors" in diag


def test_collect_diagnostics_never_includes_env_secrets(monkeypatch):
    monkeypatch.setenv("LOCALM_API_KEY", "super-secret-value")
    diag = bugreport.collect_diagnostics({})
    assert "super-secret-value" not in repr(diag)


# --------------------------- report rendering ----------------------------- #

def test_build_report_has_sections_and_summary():
    text = bugreport.build_report("disk on fire", reason="too hot",
                                  context={"operation": "run"})
    assert "# localm bug report: disk on fire" in text
    assert "## What I was doing" in text
    assert "## Environment" in text
    assert "too hot" in text
    assert bugreport.MAINTAINER_EMAIL in text   # contact line, intentionally


def test_report_footer_strip_removes_exactly_the_disclaimer_block():
    """LM-DA-PUBTEXT: the in-app 'edit before sending' disclaimer (and the maintainer's email that rides with it) must be removable from a real build_report() output as a single, exact, single-sourced block - not a fuzzy substring match that could also eat real report content."""
    text = bugreport.build_report("disk on fire", reason="too hot")
    assert bugreport.MAINTAINER_EMAIL in text
    assert "You can edit anything above before sending." in text

    stripped = bugreport._strip_report_footer(text)
    assert bugreport.MAINTAINER_EMAIL not in stripped
    assert "You can edit anything above before sending." not in stripped
    # Nothing else was touched - the stripped text is a strict prefix of the
    # original (only the trailing footer block is gone).
    assert text.startswith(stripped)
    assert "disk on fire" in stripped
    assert "too hot" in stripped


def test_report_footer_strip_tolerates_missing_trailing_newline():
    """A user who re-saves the file in an editor that trims trailing whitespace must still get a clean strip, not a silent no-op."""
    text = bugreport.build_report("x")
    without_trailing_newline = text.rstrip("\n")
    stripped = bugreport._strip_report_footer(without_trailing_newline)
    assert bugreport.MAINTAINER_EMAIL not in stripped


def test_report_footer_strip_is_a_noop_when_footer_absent():
    """A body that never had the footer (or had it manually edited away) must come back byte-for-byte unchanged - never raise, never eat real content."""
    plain = "## What happened\nsomething broke, no footer here"
    assert bugreport._strip_report_footer(plain) == plain
    assert bugreport._strip_report_footer("") == ""


def test_build_report_includes_error_traceback():
    try:
        raise ValueError("boom")
    except ValueError as e:
        text = bugreport.build_report("crashed", error=e)
    assert "## Error detail" in text
    assert "ValueError: boom" in text


def test_build_report_scrubs_credentialed_url_in_error_traceback():
    """HON-15: an exception message can embed a user-configured credentialed URL (a comfy_api_url / net_search_url / remote-server base with user:pass@), and the traceback ships in the uploaded 'Error detail' body."""
    try:
        raise RuntimeError("Could not reach the localm server at "
                           "http://user:SECRETPASS@remote:8000/v1: timeout")
    except RuntimeError as e:
        text = bugreport.build_report("server unreachable", error=e)
    assert "## Error detail" in text
    assert "SECRETPASS" not in text
    assert "<redacted>" in text


# A credential is at least as often carried as a URL QUERY PARAMETER
# (?api_key=...) or a pasted HTTP header line (X-Api-Key: ...) as it is via
# user:pass@ syntax. Both shapes are asserted in ONE block together with the
# user:pass@ case: if a regression ever deletes the _scrub_secrets call
# entirely, a query-only test would still pass while user:pass@ silently
# started leaking again (QA-FINDING-bugreport-url-query-secret-leak-2026-08-13).
def test_scrub_secrets_redacts_credential_query_params_by_name():
    out = bugreport._scrub_secrets(
        "https://x.example/s?api_key=CANARY1&token=CANARY2"
        "&apikey=CANARY3&key=CANARY4")
    assert "CANARY1" not in out
    assert "CANARY2" not in out
    assert "CANARY3" not in out
    assert "CANARY4" not in out
    # The parameter NAME survives - the maintainer needs to see the endpoint
    # was credentialed and which one, only the value must go.
    assert "api_key=<redacted>" in out
    assert "token=<redacted>" in out
    assert "apikey=<redacted>" in out
    assert "key=<redacted>" in out


def test_scrub_secrets_leaves_non_credential_query_params_intact():
    """Over-redaction destroys the diagnostic value of a report and is a real failure mode here - a plain search/lang parameter must not be touched."""
    out = bugreport._scrub_secrets("https://x.example/s?q=hello&lang=en")
    assert out == "https://x.example/s?q=hello&lang=en"


def test_scrub_secrets_still_redacts_user_pass_at_url_creds():
    """Same assertion block as the query-param cases above, deliberately - see the module comment on this test group."""
    out = bugreport._scrub_secrets("http://user:SECRETPASS@remote:8000/v1")
    assert "SECRETPASS" not in out
    assert "<redacted>" in out


def test_scrub_secrets_redacts_credential_header_line():
    out = bugreport._scrub_secrets("X-Api-Key: CANARY5")
    assert "CANARY5" not in out
    assert "X-Api-Key: <redacted>" in out


def test_scrub_secrets_query_and_header_redaction_is_idempotent():
    once = bugreport._scrub_secrets(
        "https://x.example/s?api_key=CANARY1&q=hello -- X-Api-Key: CANARY2")
    twice = bugreport._scrub_secrets(once)
    assert once == twice
    assert "CANARY1" not in once and "CANARY2" not in once


# The credential NAME does not have to sit right after a ? or & - a user pasting
# a .env fragment, a shell line or a printed launcher URL into a report writes it
# at the start of a line, or behind a prefix (OPENAI_API_KEY=, pull_token=) that
# never touches a query delimiter at all. Every one of those shipped verbatim
# until _QUERY_SECRET_RE grew its bare-name branches.
#
# CANARY CHOICE IS LOAD-BEARING: these canaries match none of the OTHER scrubbers
# in the chain. An sk- shaped canary would be eaten by _APIKEY_RE and make the
# test pass on the unfixed pattern - green for a reason unrelated to the fix.
def test_scrub_secrets_redacts_bare_credential_assignment_outside_a_url():
    out = bugreport._scrub_secrets(
        "pasted from my .env:\napi_key=CANARYBARE7Q4M\ntoken=CANARYBARE9VLM\n")
    # The DATA first: a regression must report "the canary survived", which is a
    # statement about the world. Leading with the <redacted> marker would read as
    # an adjustable formatting nit and invite someone to edit the assertion.
    assert "CANARYBARE7Q4M" not in out
    assert "CANARYBARE9VLM" not in out
    # The marker second - the name still shows THAT a credential was there.
    assert "api_key=<redacted>" in out
    assert "token=<redacted>" in out


def test_scrub_secrets_redacts_prefixed_credential_names():
    """SECRET_KEY / PRIVATE_KEY / OPENAI_API_KEY are the shapes a .env actually carries, and none of them can reach the ?/& anchored form."""
    out = bugreport._scrub_secrets(
        "OPENAI_API_KEY=CANARYBARE1AAA SECRET_KEY=CANARYBARE2BBB "
        "PRIVATE_KEY=CANARYBARE3CCC x-auth=CANARYBARE4DDD")
    for canary in ("CANARYBARE1AAA", "CANARYBARE2BBB",
                   "CANARYBARE3CCC", "CANARYBARE4DDD"):
        assert canary not in out
    assert "OPENAI_API_KEY=<redacted>" in out
    assert "SECRET_KEY=<redacted>" in out
    assert "x-auth=<redacted>" in out


def test_scrub_secrets_redacts_launch_grants_in_a_printed_gui_url():
    """``localm gui`` puts its pull/launch grants in the URL it prints to the console, so this is the one shape known to reach a report carrying a real (short-lived, single-use) credential. It has a prefixed parameter name, so the ?/& anchored form left the whole line untouched."""
    out = bugreport._scrub_secrets(
        "opening https://127.0.0.1:8080/?view=models&pull=owner%2Frepo"
        "&pull_token=CANARYBARE5EEE&localm_token=CANARYBARE6FFF")
    assert "CANARYBARE5EEE" not in out
    assert "CANARYBARE6FFF" not in out
    assert "pull_token=<redacted>" in out
    assert "localm_token=<redacted>" in out
    assert "pull=owner%2Frepo" in out


def test_scrub_secrets_leaves_non_credential_bare_assignments_intact():
    """The OTHER failure direction, and the one with no natural signal: an over-broad pattern ships green and silently eats diagnostic text out of every report."""
    text = ("n_gpu_layers=35 port=8080 n_ctx=4096 max_tokens=512 model=llama "
            "monkey=13 hotkey=f1 key=value auth=none sig=short")
    assert bugreport._scrub_secrets(text) == text


def test_scrub_secrets_bare_assignment_redaction_is_idempotent():
    once = bugreport._scrub_secrets(
        "api_key=CANARYBARE7Q4M SECRET_KEY=CANARYBARE2BBB n_ctx=4096")
    twice = bugreport._scrub_secrets(once)
    assert once == twice
    assert "CANARYBARE7Q4M" not in once and "CANARYBARE2BBB" not in once


# The name-based match is deliberately broad, so it needs a floor on the other
# side. These values were NOT invented: they are the shapes a scan of this repo's
# own tracked docs and sources found the name match eating before the non-secret
# literal suppressor was added. Picking fixture values out of imagination is how
# the over-redaction direction went untested in the first place.
_NON_SECRET_ASSIGNMENTS = (
    "LOCALM_REQUIRE_AUTH=1",
    "require_auth=true",
    "digital_signature=True",
    "secret=True",
    "has_token=false",
    "password=None",
    "signature=None",
    "auth_token=none",
    "api_key=disabled",
    "pull_token=null",
    # A report is prose, so the same flag arrives wrapped in markup. Found by a
    # test bound to the real docs, which write it as markdown inline code - the
    # first version of the suppressor missed every one of these.
    "`require_auth=1`",
    "(require_auth=1)",
    "`LOCALM_REQUIRE_AUTH=1`",
    "set `require_auth=true` to fail closed",
    'require_auth="true"',
    "require_auth='true'",
)


@pytest.mark.parametrize("line", _NON_SECRET_ASSIGNMENTS)
def test_scrub_secrets_keeps_assignments_whose_value_cannot_be_a_secret(line):
    """Over-redaction has no natural failure signal: an over-broad pattern ships green and silently eats diagnostic text out of every report."""
    assert bugreport._scrub_secrets(line) == line


# The suppressor must not become a bypass: a real secret that merely STARTS with
# one of the literals has to keep going. The inner lookahead pins each literal to
# the WHOLE value, and this is the test that holds it there.
@pytest.mark.parametrize("line,canary", [
    ("api_key=trueCANARYLIT1", "trueCANARYLIT1"),
    ("token=noCANARYLIT2", "noCANARYLIT2"),
    ("api_key=onCANARYLIT3", "onCANARYLIT3"),
    ("SECRET_KEY=falseCANARYLIT4", "falseCANARYLIT4"),
    ("api_key=0CANARYLIT5", "0CANARYLIT5"),
    ("api_key=10", "10"),
])
def test_scrub_secrets_still_redacts_a_secret_that_starts_with_a_literal(line, canary):
    out = bugreport._scrub_secrets(line)
    assert canary not in out          # DATA first
    assert "=<redacted>" in out       # marker second


@pytest.mark.parametrize("line", [
    "api_key=1)SECRETLEAK",
    'api_key=1"SECRETLEAK',
    "token=true]MORESECRET",
])
def test_the_non_secret_suppressor_does_not_fire_when_more_value_follows(line):
    """Tolerating closing markup must not become a bypass. ``(require_auth=1)`` is a flag; ``api_key=1)SECRET`` is not, and the difference is whether anything other than whitespace follows the markup."""
    out = bugreport._scrub_secrets(line)
    assert "=<redacted>" in out, (
        f"the suppressor swallowed a credential assignment: {out!r}")


# FOUND BY A LIVE RUN, not by the suite: filing a real report through the CLI
# with a pasted .env produced
#
#     API_KEY=<redacted>"ENVQUOTEDSECRET1"
#
# The value stopped at the opening quote, so the secret shipped in full sitting
# next to a marker claiming it had been removed. A quoted value is the COMMON
# .env form, and every fixture in this file had used the bare form.
#
# Worse than a plain miss: a privacy step reporting a success it did not achieve
# is the one thing AGENTS.md rule 5 forbids outright.
@pytest.mark.parametrize("line,canary", [
    ('API_KEY="ENVQUOTED1"', "ENVQUOTED1"),
    ("SECRET_KEY='ENVQUOTED2'", "ENVQUOTED2"),
    ('api_key="with spaces inside"', "with spaces inside"),
    ('OPENAI_API_KEY="sk-ENVQUOTED3"', "ENVQUOTED3"),
    ('?api_key="ENVQUOTED4"&x=1', "ENVQUOTED4"),
    # An unterminated quote redacts to end of line. Over-redacting the rest of a
    # line that opened with a credential is the safe direction.
    ('api_key="ENVQUOTED5', "ENVQUOTED5"),
    ("api_key='ENVQUOTED6", "ENVQUOTED6"),
])
def test_scrub_secrets_redacts_a_quoted_credential_value(line, canary):
    out = bugreport._scrub_secrets(line)
    # DATA first: a regression must say the canary survived.
    assert canary not in out, (
        f"a quoted credential shipped verbatim: {out!r}")
    assert "=<redacted>" in out


def test_unterminated_quote_redaction_span_is_what_the_comment_claims():
    """The three spans an unterminated quote can produce, pinned because the comment beside the pattern got one of them wrong: it claimed end-of-line in all cases, when a later quote on the same line ends the span earlier."""
    # no later quote: to end of line
    out = bugreport._scrub_secrets("api_key=\"UNTERM1 and more text here")
    assert "UNTERM1" not in out
    assert out == "api_key=<redacted>"
    # a later quote on the same line: the span ends THERE, not at end of line
    out = bugreport._scrub_secrets(
        "api_key=\"UNTERM2 then require_auth=\"true\" after")
    assert "UNTERM2" not in out
    assert out.endswith("after"), out
    # never across a newline: the next line is untouched
    out = bugreport._scrub_secrets("api_key=\"UNTERM3\nn_gpu_layers=35")
    assert "UNTERM3" not in out
    assert "n_gpu_layers=35" in out


def test_scrub_secrets_never_marks_redacted_while_leaving_the_secret():
    """The specific shape the live run produced."""
    out = bugreport._scrub_secrets('my .env has API_KEY="ENVQUOTED7"')
    assert "ENVQUOTED7" not in out
    assert '<redacted>"' not in out, (
        f"a redaction marker was emitted immediately before a surviving quoted "
        f"value: {out!r}")


def test_scrub_secrets_never_eats_a_non_secret_value_out_of_the_real_docs():
    """Bound to the SHIPPED artefact, not to a fixture."""
    docs = pathlib.Path(bugreport.__file__).resolve().parents[1] / "docs"
    assert docs.is_dir(), f"docs/ not found next to the package: {docs}"
    files = sorted(docs.rglob("*.md"))
    assert len(files) > 5, f"instrument broken: only found {len(files)} docs"

    literals = {"true", "false", "none", "null", "nil", "yes", "no",
                "on", "off", "enabled", "disabled", "0", "1"}
    seen, eaten = 0, []
    for f in files:
        text = f.read_text(encoding="utf-8", errors="replace")
        for m in bugreport._QUERY_SECRET_RE.finditer(text):
            seen += 1
            # The docs write flags as markdown inline code, so the captured value
            # is ``1` `` and not ``1`` (a backtick does not terminate the value).
            # Comparing the RAW value made this test unable to fail: it passed
            # with the suppressor removed. Strip the surrounding markup first.
            value = m.group(0)[len(m.group(1)):].strip("`*_.,;:)]}").lower()
            if value in literals:
                line_no = text.count("\n", 0, m.start()) + 1
                eaten.append(f"{f.name}:{line_no} {m.group(0)!r}")
    # Prove the scan can see anything at all. If the docs ever stop containing a
    # credential-named assignment, this test becomes vacuous, and it should say
    # so loudly rather than keep reporting a green it did not earn.
    assert seen > 0, (
        "no credential-named assignment found anywhere in the docs - this test "
        "can no longer detect the regression it exists for")
    assert eaten == [], (
        "the scrub redacted a value that cannot be a secret, out of real shipped "
        f"docs: {eaten}")


def test_build_report_no_secret_when_none_given():
    text = bugreport.build_report("x")
    assert "## Error detail" not in text


def test_build_report_scrubs_home_path_in_summary_and_reason():
    """HON-15: the user-typed summary/reason are the only report fields not otherwise scrubbed; a home path (username) in them would ship in the uploaded body (and, via the derived title, a PUBLIC issue)."""
    text = bugreport.build_report(
        r"crash running Z:\Users\bob\localm\app.py",
        reason=r"see backup at Z:\Users\bob\localm-backups\b1")
    assert "bob" not in text
    assert "<redacted>" in text
    # The scrubbed summary still lands in the title header (nothing is dropped).
    assert "# localm bug report:" in text


# --------------------------- send URLs ------------------------------------ #

def test_mailto_url_targets_maintainer_and_encodes():
    url = bugreport.mailto_url("a bug", "line one\nline two & more")
    assert url.startswith(f"mailto:{bugreport.MAINTAINER_EMAIL}?")
    assert "subject=" in url and "body=" in url
    assert " " not in url            # spaces must be percent-encoded


def test_prefill_body_is_capped():
    big = "x" * (bugreport._MAX_PREFILL_BODY * 3)
    capped = bugreport._truncate_body(big)
    assert len(capped) < len(big)
    assert "truncated" in capped


# --------------------------- saving --------------------------------------- #

def test_save_report_writes_editable_file(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_report("hello report", when="20260617-000000")
    assert path is not None
    assert path.exists()
    assert path.read_text(encoding="utf-8") == "hello report"
    assert path.parent.name == "bug-reports"


def test_save_user_report_puts_description_in_body(tmp_path, monkeypatch):
    # R47: the GUI "Report a bug" backend - the user's words land in the report,
    # the summary is derived from the first line, and the env snapshot is present.
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "Mic button does nothing.\nClicked it five times, no recording.")
    assert path is not None and path.exists()
    text = path.read_text(encoding="utf-8")
    assert "Mic button does nothing." in text                  # first line = summary
    assert "Clicked it five times" in text                     # full description in body
    assert "## Environment" in text
    assert "<!-- Please describe" not in text                   # placeholder replaced


def test_save_user_report_blank_description_still_saves(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report("")
    assert path is not None and path.exists()
    assert "user-reported issue" in path.read_text(encoding="utf-8")


# ------------------- concurrency: two GUI reports at once ----------------- #

def test_concurrent_save_user_report_calls_never_overlap(tmp_path, monkeypatch):
    """The GUI endpoint now offloads save_user_report() to a real worker thread (localm/inference/routes/admin.py, off the event loop), so two reports filed close together can run this function on two DIFFERENT threads at the same instant - not merely interleaved on one event loop the way the old synchrono..."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    in_critical_section = threading.Event()
    overlap_detected = threading.Event()
    real_save_report = bugreport.save_report

    def _instrumented_save_report(text, when=None):
        if in_critical_section.is_set():
            overlap_detected.set()
        in_critical_section.set()
        try:
            time.sleep(0.05)
            return real_save_report(text, when=when)
        finally:
            in_critical_section.clear()

    monkeypatch.setattr(bugreport, "save_report", _instrumented_save_report)

    errors = []

    def _file(n):
        try:
            bugreport.save_user_report(f"report from thread {n}")
        except Exception as e:      # pragma: no cover - failure path only
            errors.append(e)

    threads = [threading.Thread(target=_file, args=(i,)) for i in range(6)]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=5)

    assert not errors, f"save_user_report raised under concurrency: {errors}"
    assert not overlap_detected.is_set(), (
        "two save_user_report() calls executed their save_report() critical "
        "section concurrently - _SAVE_REPORT_LOCK did not serialize them, so "
        "two writers could interleave content into one corrupted report file")


def test_save_user_report_scrubs_home_path_in_description(tmp_path, monkeypatch):
    """HON-15: the GUI description is inserted AFTER build_report's own scrub pass and is uploaded verbatim in the report body when the user picks upload, so it must be scrubbed at its injection point too - both the derived summary and the full description must be redacted."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "It broke when I ran it from Z:\\Users\\bob\\localm and clicked send.")
    assert path is not None and path.exists()
    text = path.read_text(encoding="utf-8")
    assert "bob" not in text
    assert "<redacted>" in text


# ------------------- #958: what-I-did / expected / happened --------------- #

def test_save_user_report_splits_expected_and_happened_into_their_own_sections(
        tmp_path, monkeypatch):
    # Before this fix all three fields (title, "What I was doing", "What
    # happened") were the SAME truncated first line - a reader could never
    # tell what the user expected from what actually happened.
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "I clicked the mic button to start voice input.",
        what_i_expected="Recording should have started.",
        what_happened="Nothing happened - no recording indicator appeared.")
    assert path is not None and path.exists()
    text = path.read_text(encoding="utf-8")
    assert "## What I was doing" in text
    assert "## What I expected" in text
    assert "## What happened" in text
    did_section = text.split("## What I was doing")[1].split("## What I expected")[0]
    expected_section = text.split("## What I expected")[1].split("## What happened")[0]
    happened_section = text.split("## What happened")[1].split("## App state")[0]
    assert "clicked the mic button" in did_section
    assert "Recording should have started" in expected_section
    assert "no recording indicator" in happened_section
    # The three sections are genuinely distinct - none is a copy of another.
    assert "Recording should have started" not in did_section
    assert "no recording indicator" not in expected_section
    assert "clicked the mic button" not in happened_section
    # The title comes from "what happened" (the more useful title), not the
    # truncated "what I was doing" text.
    assert text.startswith("# localm bug report: Nothing happened")


def test_save_user_report_omits_expected_section_when_not_supplied(tmp_path, monkeypatch):
    # Backward-compatible degraded input: a caller that supplies only
    # description (the CLI, or an old client) gets no empty "## What I
    # expected" section cluttering the report.
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report("just a description, nothing else")
    text = path.read_text(encoding="utf-8")
    assert "## What I expected" not in text


def test_save_user_report_scrubs_what_expected_and_happened(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "did a thing",
        what_i_expected="it should work like Z:\\Users\\bob\\proj does",
        what_happened="it crashed, see Z:\\Users\\bob\\crash.log")
    text = path.read_text(encoding="utf-8")
    assert "bob" not in text
    assert "<redacted>" in text


# ------------------- #958: description-only must not duplicate ----------- #

def test_description_only_renders_not_stated_not_a_duplicate(tmp_path, monkeypatch):
    """#958's actual artifact, reproduced: before this fix, leaving 'what happened' blank made the title AND the 'What happened' section repeat the description verbatim - a report that LOOKS like it has three sections of content but is really one sentence copied three times."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    desc = "the image generator crashed when I clicked generate twice quickly"
    path = bugreport.save_user_report(desc)
    text = path.read_text(encoding="utf-8")
    did_section = text.split("## What I was doing")[1].split("## What happened")[0]
    happened_section = text.split("## What happened")[1].split("## App state")[0]
    assert desc in did_section
    assert "(not stated)" in happened_section
    assert desc not in happened_section
    assert text.startswith(f"# localm bug report: {desc}")


def test_description_and_happened_both_filled_no_duplication(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "clicked generate twice", what_happened="the app crashed with a CUDA error")
    text = path.read_text(encoding="utf-8")
    happened_section = text.split("## What happened")[1].split("## App state")[0]
    assert "clicked generate twice" not in happened_section
    assert "the app crashed with a CUDA error" in happened_section


def test_automatic_crash_report_keeps_the_summary_reason_fallback(monkeypatch):
    """The fallback build_report() drops for USER reports (what_i_did present, what_happened blank) must stay EXACTLY as before for an AUTOMATIC report (report_failure / a raised exception, no user-composed fields at all) - there was never a separate 'what happened' question to leave blank, and summary+rea..."""
    text = bugreport.build_report(
        "image generation crashed", reason="segfault in native worker")
    happened_section = text.split("## What happened")[1].split("## App state")[0]
    assert "image generation crashed" in happened_section
    assert "segfault in native worker" in happened_section
    assert "(not stated)" not in happened_section


def test_report_title_prefers_what_happened_over_description():
    assert bugreport.report_title("", "it crashed", "clicked the button") == "it crashed"


def test_report_title_falls_back_to_description_when_happened_blank():
    assert bugreport.report_title("", "", "clicked the button") == "clicked the button"


def test_report_title_explicit_summary_wins_over_both():
    assert bugreport.report_title("explicit title", "happened", "did") == "explicit title"


def test_report_title_never_empty():
    assert bugreport.report_title("", "", "") == "user-reported issue"


def test_report_title_matches_what_save_user_report_actually_titled_it(
        tmp_path, monkeypatch):
    """The whole reason report_title is a standalone function: a caller that needs the title AFTER the report is built (the CLI, to hand to offer_to_send/upload_report) must get the SAME value the saved report's own H1 carries - not a second, independently-derived guess."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    what_happened, description = "the app froze", "trying to load a model"
    path = bugreport.save_user_report(description, what_happened=what_happened)
    text = path.read_text(encoding="utf-8")
    computed = bugreport.report_title("", what_happened, description)
    assert text.startswith(f"# localm bug report: {computed}")


def test_extra_hang_trace_from_a_different_process_is_attached(tmp_path, monkeypatch):
    """The localm bug-report CLI's own case (REG-736): its pid never froze, so the internal self-pid check finds nothing, and the CLI must be able to hand save_user_report a trace it found elsewhere (the live server's own registry entry) instead."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "the app hung", extra_hang_trace="CLI-SUPPLIED-MARKER event loop stalled 30s")
    text = path.read_text(encoding="utf-8")
    assert "CLI-SUPPLIED-MARKER" in text


# --------------------------- the interactive offer ------------------------ #

def test_report_failure_noninteractive_saves_without_prompt(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    opened = []
    path = bugreport.report_failure(
        summary="thing broke", reason="reason Y",
        interactive=False, open_browser=lambda u: opened.append(u),
        prompt=lambda _t: (_ for _ in ()).throw(AssertionError("should not prompt")))
    out = capsys.readouterr().out
    assert "Sorry - thing broke" in out
    assert "reason Y" in out
    assert path is not None and path.exists()
    assert opened == []              # never opens a browser unattended


def test_report_failure_email_channel_opens_mailto(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    # Email is the always-present channel [2] (upload, when configured, is [1]).
    opened = []
    bugreport.report_failure(
        summary="bug", interactive=True,
        open_browser=lambda u: opened.append(u), prompt=lambda _t: "2")
    assert opened and opened[0].startswith(f"mailto:{bugreport.MAINTAINER_EMAIL}")


def test_report_failure_self_channel_prints_manual_instructions(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})   # [1] upload, [2] email, [3] self
    opened = []
    bugreport.report_failure(
        summary="bug", interactive=True,
        open_browser=lambda u: opened.append(u), prompt=lambda _t: "3")
    assert opened == []                              # no browser, no network
    out = capsys.readouterr().out
    assert bugreport.MAINTAINER_EMAIL in out
    assert "Discord" in out


def test_interactive_menu_never_offers_a_github_login_path(tmp_path, monkeypatch, capsys):
    """The whole point: no channel in this app ever opens a github.com page or otherwise asks for a GitHub login - the hosted proxy is the only channel that creates an issue, and it is account-less."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})
    bugreport.report_failure(
        summary="bug", interactive=True, prompt=lambda _t: "")   # decline; just look at the menu
    out = capsys.readouterr().out.lower()
    assert "open a github issue" not in out
    assert "github.com" not in out
    # The only permitted mention of GitHub is the reassurance that none is needed.
    assert "no github account" in out
    assert not hasattr(bugreport, "issue_url")
    assert not hasattr(bugreport, "ISSUES_NEW_URL")


def test_report_failure_decline_opens_nothing(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    opened = []
    bugreport.report_failure(
        summary="bug", interactive=True,
        open_browser=lambda u: opened.append(u), prompt=lambda _t: "")
    assert opened == []


def test_report_failure_neutral_header_when_not_a_failure(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    bugreport.report_failure(
        summary="user filed this", as_failure=False, interactive=False)
    out = capsys.readouterr().out
    assert "Filing a bug report" in out
    assert "Sorry -" not in out


# --------------------------- non-interactive message accuracy ------------- #
# A friend testing localm hit this for real: any crash (or `localm bug-report`)
# in a non-tty context (a script, an SSH session, the console-less native
# launcher) used to print ONLY "email or Discord, or open a GitHub issue once
# you have repo access" - completely omitting the account-less hosted channel
# even when it is configured and working, steering the user toward the one
# path that actually needs a GitHub login.

def test_noninteractive_message_offers_send_flag_when_upload_configured(
        tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})
    bugreport.report_failure(summary="thing broke", interactive=False)
    out = " ".join(capsys.readouterr().out.split())   # collapse rich's line-wrapping
    assert "localm bug-report --send" in out
    assert "no GitHub account needed" in out


def test_noninteractive_message_falls_back_when_no_upload_configured(
        tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {"bugreport_upload_url": ""})
    bugreport.report_failure(summary="thing broke", interactive=False)
    out = " ".join(capsys.readouterr().out.split())   # collapse rich's line-wrapping
    assert "--send" not in out
    assert "github" not in out.lower()
    assert "email or Discord" in out


# --------------------------- auto_send (--send) ---------------------------- #

def test_auto_send_uploads_without_prompting(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})
    monkeypatch.setattr(bugreport, "upload_report",
                        lambda *a, **k: {"url": "https://github.com/x/y/issues/9"})
    bugreport.report_failure(
        summary="bug", interactive=False, auto_send=True,
        prompt=lambda _t: (_ for _ in ()).throw(AssertionError("must not prompt")))
    out = capsys.readouterr().out
    assert "Sent to the maintainer" in out
    assert "https://github.com/x/y/issues/9" in out


def test_auto_send_without_upload_configured_is_honest(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {"bugreport_upload_url": ""})
    bugreport.report_failure(summary="bug", interactive=False, auto_send=True)
    out = capsys.readouterr().out
    assert "No hosted send channel is configured" in out
    assert "Sent to the maintainer" not in out


def test_auto_send_upload_failure_is_never_reported_as_success(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})

    def _boom(*a, **k):
        raise bugreport.LocalmError("upload failed", reason="502 from proxy")
    monkeypatch.setattr(bugreport, "upload_report", _boom)
    bugreport.report_failure(summary="bug", interactive=False, auto_send=True)
    out = " ".join(capsys.readouterr().out.split())   # collapse rich's line-wrapping
    assert "Sent to the maintainer" not in out
    assert "Could not send it" in out
    # The email fallback is offered (now naming the maintainer address).
    assert "email it to" in out and bugreport.MAINTAINER_EMAIL in out


# --------------------------- process-wide net ----------------------------- #

def test_thread_excepthook_reports_without_prompting(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    args = types.SimpleNamespace(
        exc_type=ValueError, exc_value=ValueError("worker boom"),
        exc_traceback=None, thread=types.SimpleNamespace(name="jobs-runner"))
    bugreport._handle_thread_exception(args)
    assert len(calls) == 1
    assert calls[0]["interactive"] is False
    assert calls[0]["context"]["thread"] == "jobs-runner"


def test_thread_excepthook_ignores_systemexit(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    args = types.SimpleNamespace(
        exc_type=SystemExit, exc_value=SystemExit(0),
        exc_traceback=None, thread=types.SimpleNamespace(name="t"))
    bugreport._handle_thread_exception(args)
    assert calls == []


def test_main_excepthook_reports_real_error(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    bugreport._handle_main_exception(ValueError, ValueError("boom"), None)
    assert len(calls) == 1
    assert "unexpected error" in calls[0]["summary"]


def test_main_excepthook_uses_localmerror_fields(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    err = bugreport.LocalmError("backend dead", reason="no driver", context={"x": 1})
    bugreport._handle_main_exception(bugreport.LocalmError, err, None)
    assert calls[0]["summary"] == "backend dead"
    assert calls[0]["reason"] == "no driver"
    assert calls[0]["context"] == {"x": 1}


def test_main_excepthook_keyboardinterrupt_does_not_report(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    monkeypatch.setattr(sys, "__excepthook__", lambda *a: None)
    bugreport._handle_main_exception(KeyboardInterrupt, KeyboardInterrupt(), None)
    assert calls == []


def test_install_global_handlers_noop_under_pytest(monkeypatch):
    monkeypatch.setattr(bugreport, "_handlers_installed", False)
    # pytest is in sys.modules, so the default (unforced) call is a deliberate no-op.
    assert bugreport.install_global_handlers() is False


def test_install_global_handlers_force_sets_hooks(monkeypatch):
    monkeypatch.setattr(bugreport, "_handlers_installed", False)
    orig_e, orig_t = sys.excepthook, threading.excepthook
    try:
        assert bugreport.install_global_handlers(force=True) is True
        assert sys.excepthook is bugreport._handle_main_exception
        assert threading.excepthook is bugreport._handle_thread_exception
    finally:
        sys.excepthook, threading.excepthook = orig_e, orig_t


# --------------------------- editable file is what's sent ----------------- #

def test_report_failure_sends_edited_file_not_original(tmp_path, monkeypatch):
    """'Edit it before sending' must be true: the email/issue body is read back from the (possibly edited) file, not the original generated text."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    edited = tmp_path / "bug-reports" / "edited.md"

    def fake_save(text, when=None):
        edited.parent.mkdir(parents=True, exist_ok=True)
        edited.write_text("EDITED REPORT BODY", encoding="utf-8")
        return edited
    monkeypatch.setattr(bugreport, "save_report", fake_save)

    opened = []
    bugreport.report_failure(
        summary="bug", interactive=True,
        open_browser=lambda u: opened.append(u), prompt=lambda _t: "2")  # [2] = email
    assert opened
    assert "EDITED REPORT BODY" in unquote(opened[0])   # the edit, not the original


# --------------------------- file permissions ----------------------------- #

@pytest.mark.skipif(os.name != "posix", reason="POSIX file mode bits")
def test_save_report_is_owner_only(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_report("secretish diagnostics", when="t")
    assert path is not None
    assert stat.S_IMODE(os.stat(path).st_mode) == 0o600


# --------------------------- the bug-report CLI command ------------------- #

def test_bug_report_command_via_cli(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    from localm.cli import main
    res = CliRunner().invoke(main, ["bug-report", "-m", "my problem"])
    assert res.exit_code == 0, res.output
    assert "Filing a bug report" in res.output
    assert "my problem" in res.output
    assert "Sorry -" not in res.output               # user-initiated, not a crash
    assert list((tmp_path / "bug-reports").glob("*.md"))


def test_bug_report_command_send_flag_uploads_immediately(tmp_path, monkeypatch):
    """`localm bug-report --send` is the fix's whole point: a working, login-free send path that a tester in a non-tty shell (or told the exact command by the maintainer) can actually run."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})
    monkeypatch.setattr(bugreport, "upload_report",
                        lambda *a, **k: {"url": "https://github.com/x/y/issues/3"})
    from localm.cli import main
    res = CliRunner().invoke(main, ["bug-report", "-m", "my problem", "--send"])
    assert res.exit_code == 0, res.output
    assert "Sent to the maintainer" in res.output
    assert "https://github.com/x/y/issues/3" in res.output


class TestRecommendedBackendMatchesInstallPolicy:
    """The report's 'Recommended backend' must be the policy the INSTALLER would apply, not the blanket 'vulkan whenever a GPU exists' detection value."""

    def _diag_with(self, monkeypatch, vendors, platform):
        from localm import hwdetect
        det = hwdetect.Detection(vendors=vendors, recommended="vulkan",
                                 source="test", gpu_names=" ".join(vendors))
        monkeypatch.setattr(hwdetect, "detect", lambda: det)
        monkeypatch.setattr(sys, "platform", platform)
        return bugreport.collect_diagnostics({})

    def test_nvidia_on_windows_reports_cuda_not_vulkan(self, monkeypatch):
        diag = self._diag_with(monkeypatch, ["nvidia"], "win32")
        assert diag["recommended_backend"] == "cuda", (
            "an NVIDIA Windows box reported a backend the installer would not "
            "provision - the #833 triage trap")

    def test_no_gpu_still_reports_cpu(self, monkeypatch):
        diag = self._diag_with(monkeypatch, [], "win32")
        assert diag["recommended_backend"] == "cpu"

    def test_nvidia_on_linux_reports_cuda_not_vulkan(self, monkeypatch):
        """llama.cpp ships a self-contained cudart bundle on Linux too (no system toolkit needed), and 2026-08-11 field testing confirmed CUDA outperforms vulkan on real NVIDIA Linux hardware - see dev-notes/BLACKWELL-FIELD-FIXES-fix_plan.md, U5."""
        diag = self._diag_with(monkeypatch, ["nvidia"], "linux")
        assert diag["recommended_backend"] == "cuda"
