# SPDX-License-Identifier: AGPL-3.0-or-later
"""Graceful failure + the autogenerated, editable bug report (localm/bugreport).

Pins: diagnostics are collected safely and never raise; the report renders with
the expected sections; the mailto / GitHub-issue URLs are well-formed and
length-capped; the report is saved to an editable file; and the interactive
offer routes to the chosen channel without leaking secrets.
"""

from __future__ import annotations

import os
import stat
import sys
import threading
import types
from urllib.parse import unquote

import pytest
from click.testing import CliRunner

from localm import bugreport


# --------------------------- the typed error ------------------------------ #

def test_localm_error_carries_summary_reason_context():
    e = bugreport.LocalmError("it broke", reason="because X", context={"a": 1})
    assert e.summary == "it broke"
    assert e.reason == "because X"
    assert e.context == {"a": 1}
    assert str(e) == "it broke"


# --------------------------- diagnostics ---------------------------------- #

def test_collect_diagnostics_is_safe_and_useful():
    diag = bugreport.collect_diagnostics({"operation": "test", "backend": "cuda"})
    assert "python" in diag and "platform" in diag
    assert diag.get("operation") == "test"
    assert diag.get("backend") == "cuda"
    # gpu_vendors is always present (possibly empty), never raises.
    assert "gpu_vendors" in diag


def test_collect_diagnostics_never_includes_env_secrets(monkeypatch):
    monkeypatch.setenv("LOCALM_API_KEY", "super-secret-value")
    diag = bugreport.collect_diagnostics({})
    assert "super-secret-value" not in repr(diag)


# --------------------------- report rendering ----------------------------- #

def test_build_report_has_sections_and_summary():
    text = bugreport.build_report("disk on fire", reason="too hot",
                                  context={"operation": "run"})
    assert "# localm bug report: disk on fire" in text
    assert "## What I was doing" in text
    assert "## Environment" in text
    assert "too hot" in text
    assert bugreport.MAINTAINER_EMAIL in text   # contact line, intentionally


def test_build_report_includes_error_traceback():
    try:
        raise ValueError("boom")
    except ValueError as e:
        text = bugreport.build_report("crashed", error=e)
    assert "## Error detail" in text
    assert "ValueError: boom" in text


def test_build_report_scrubs_credentialed_url_in_error_traceback():
    """HON-15: an exception message can embed a user-configured credentialed URL
    (a comfy_api_url / net_search_url / remote-server base with user:pass@), and the
    traceback ships in the uploaded 'Error detail' body. It must be credential-scrubbed
    like the sibling log tail, not merely home-scrubbed."""
    try:
        raise RuntimeError("Could not reach the localm server at "
                           "http://user:SECRETPASS@remote:8000/v1: timeout")
    except RuntimeError as e:
        text = bugreport.build_report("server unreachable", error=e)
    assert "## Error detail" in text
    assert "SECRETPASS" not in text
    assert "<redacted>" in text


def test_build_report_no_secret_when_none_given():
    text = bugreport.build_report("x")
    assert "## Error detail" not in text


def test_build_report_scrubs_home_path_in_summary_and_reason():
    """HON-15: the user-typed summary/reason are the only report fields not
    otherwise scrubbed; a home path (username) in them would ship in the uploaded
    body (and, via the derived title, a PUBLIC issue). They are scrubbed at the
    build_report choke point, so every caller is covered."""
    text = bugreport.build_report(
        r"crash running Z:\Users\bob\localm\app.py",
        reason=r"see backup at Z:\Users\bob\localm-backups\b1")
    assert "bob" not in text
    assert "<redacted>" in text
    # The scrubbed summary still lands in the title header (nothing is dropped).
    assert "# localm bug report:" in text


# --------------------------- send URLs ------------------------------------ #

def test_mailto_url_targets_maintainer_and_encodes():
    url = bugreport.mailto_url("a bug", "line one\nline two & more")
    assert url.startswith(f"mailto:{bugreport.MAINTAINER_EMAIL}?")
    assert "subject=" in url and "body=" in url
    assert " " not in url            # spaces must be percent-encoded


def test_prefill_body_is_capped():
    big = "x" * (bugreport._MAX_PREFILL_BODY * 3)
    capped = bugreport._truncate_body(big)
    assert len(capped) < len(big)
    assert "truncated" in capped


# --------------------------- saving --------------------------------------- #

def test_save_report_writes_editable_file(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_report("hello report", when="20260617-000000")
    assert path is not None
    assert path.exists()
    assert path.read_text(encoding="utf-8") == "hello report"
    assert path.parent.name == "bug-reports"


def test_save_user_report_puts_description_in_body(tmp_path, monkeypatch):
    # R47: the GUI "Report a bug" backend - the user's words land in the report,
    # the summary is derived from the first line, and the env snapshot is present.
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "Mic button does nothing.\nClicked it five times, no recording.")
    assert path is not None and path.exists()
    text = path.read_text(encoding="utf-8")
    assert "Mic button does nothing." in text                  # first line = summary
    assert "Clicked it five times" in text                     # full description in body
    assert "## Environment" in text
    assert "<!-- Please describe" not in text                   # placeholder replaced


def test_save_user_report_blank_description_still_saves(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report("")
    assert path is not None and path.exists()
    assert "user-reported issue" in path.read_text(encoding="utf-8")


def test_save_user_report_scrubs_home_path_in_description(tmp_path, monkeypatch):
    """HON-15: the GUI description is inserted AFTER build_report's own scrub pass
    and is uploaded verbatim in the report body when the user picks upload, so it
    must be scrubbed at its injection point too - both the derived summary and the
    full description must be redacted."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "It broke when I ran it from Z:\\Users\\bob\\localm and clicked send.")
    assert path is not None and path.exists()
    text = path.read_text(encoding="utf-8")
    assert "bob" not in text
    assert "<redacted>" in text


# ------------------- #958: what-I-did / expected / happened --------------- #

def test_save_user_report_splits_expected_and_happened_into_their_own_sections(
        tmp_path, monkeypatch):
    # Before this fix all three fields (title, "What I was doing", "What
    # happened") were the SAME truncated first line - a reader could never
    # tell what the user expected from what actually happened.
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "I clicked the mic button to start voice input.",
        what_i_expected="Recording should have started.",
        what_happened="Nothing happened - no recording indicator appeared.")
    assert path is not None and path.exists()
    text = path.read_text(encoding="utf-8")
    assert "## What I was doing" in text
    assert "## What I expected" in text
    assert "## What happened" in text
    did_section = text.split("## What I was doing")[1].split("## What I expected")[0]
    expected_section = text.split("## What I expected")[1].split("## What happened")[0]
    happened_section = text.split("## What happened")[1].split("## App state")[0]
    assert "clicked the mic button" in did_section
    assert "Recording should have started" in expected_section
    assert "no recording indicator" in happened_section
    # The three sections are genuinely distinct - none is a copy of another.
    assert "Recording should have started" not in did_section
    assert "no recording indicator" not in expected_section
    assert "clicked the mic button" not in happened_section
    # The title comes from "what happened" (the more useful title), not the
    # truncated "what I was doing" text.
    assert text.startswith("# localm bug report: Nothing happened")


def test_save_user_report_omits_expected_section_when_not_supplied(tmp_path, monkeypatch):
    # Backward-compatible degraded input: a caller that supplies only
    # description (the CLI, or an old client) gets no empty "## What I
    # expected" section cluttering the report.
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report("just a description, nothing else")
    text = path.read_text(encoding="utf-8")
    assert "## What I expected" not in text


def test_save_user_report_scrubs_what_expected_and_happened(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_user_report(
        "did a thing",
        what_i_expected="it should work like Z:\\Users\\bob\\proj does",
        what_happened="it crashed, see Z:\\Users\\bob\\crash.log")
    text = path.read_text(encoding="utf-8")
    assert "bob" not in text
    assert "<redacted>" in text


# --------------------------- the interactive offer ------------------------ #

def test_report_failure_noninteractive_saves_without_prompt(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    opened = []
    path = bugreport.report_failure(
        summary="thing broke", reason="reason Y",
        interactive=False, open_browser=lambda u: opened.append(u),
        prompt=lambda _t: (_ for _ in ()).throw(AssertionError("should not prompt")))
    out = capsys.readouterr().out
    assert "Sorry - thing broke" in out
    assert "reason Y" in out
    assert path is not None and path.exists()
    assert opened == []              # never opens a browser unattended


def test_report_failure_email_channel_opens_mailto(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    # Email is the always-present channel [2] (upload, when configured, is [1]).
    opened = []
    bugreport.report_failure(
        summary="bug", interactive=True,
        open_browser=lambda u: opened.append(u), prompt=lambda _t: "2")
    assert opened and opened[0].startswith(f"mailto:{bugreport.MAINTAINER_EMAIL}")


def test_report_failure_self_channel_prints_manual_instructions(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})   # [1] upload, [2] email, [3] self
    opened = []
    bugreport.report_failure(
        summary="bug", interactive=True,
        open_browser=lambda u: opened.append(u), prompt=lambda _t: "3")
    assert opened == []                              # no browser, no network
    out = capsys.readouterr().out
    assert bugreport.MAINTAINER_EMAIL in out
    assert "Discord" in out


def test_interactive_menu_never_offers_a_github_login_path(tmp_path, monkeypatch, capsys):
    """The whole point: no channel in this app ever opens a github.com page or
    otherwise asks for a GitHub login - the hosted proxy is the only channel
    that creates an issue, and it is account-less."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})
    bugreport.report_failure(
        summary="bug", interactive=True, prompt=lambda _t: "")   # decline; just look at the menu
    out = capsys.readouterr().out.lower()
    assert "open a github issue" not in out
    assert "github.com" not in out
    # The only permitted mention of GitHub is the reassurance that none is needed.
    assert "no github account" in out
    assert not hasattr(bugreport, "issue_url")
    assert not hasattr(bugreport, "ISSUES_NEW_URL")


def test_report_failure_decline_opens_nothing(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    opened = []
    bugreport.report_failure(
        summary="bug", interactive=True,
        open_browser=lambda u: opened.append(u), prompt=lambda _t: "")
    assert opened == []


def test_report_failure_neutral_header_when_not_a_failure(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    bugreport.report_failure(
        summary="user filed this", as_failure=False, interactive=False)
    out = capsys.readouterr().out
    assert "Filing a bug report" in out
    assert "Sorry -" not in out


# --------------------------- non-interactive message accuracy ------------- #
# A friend testing localm hit this for real: any crash (or `localm bug-report`)
# in a non-tty context (a script, an SSH session, the console-less native
# launcher) used to print ONLY "email or Discord, or open a GitHub issue once
# you have repo access" - completely omitting the account-less hosted channel
# even when it is configured and working, steering the user toward the one
# path that actually needs a GitHub login.

def test_noninteractive_message_offers_send_flag_when_upload_configured(
        tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})
    bugreport.report_failure(summary="thing broke", interactive=False)
    out = " ".join(capsys.readouterr().out.split())   # collapse rich's line-wrapping
    assert "localm bug-report --send" in out
    assert "no GitHub account needed" in out


def test_noninteractive_message_falls_back_when_no_upload_configured(
        tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {"bugreport_upload_url": ""})
    bugreport.report_failure(summary="thing broke", interactive=False)
    out = " ".join(capsys.readouterr().out.split())   # collapse rich's line-wrapping
    assert "--send" not in out
    assert "github" not in out.lower()
    assert "email or Discord" in out


# --------------------------- auto_send (--send) ---------------------------- #

def test_auto_send_uploads_without_prompting(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})
    monkeypatch.setattr(bugreport, "upload_report",
                        lambda *a, **k: {"url": "https://github.com/x/y/issues/9"})
    bugreport.report_failure(
        summary="bug", interactive=False, auto_send=True,
        prompt=lambda _t: (_ for _ in ()).throw(AssertionError("must not prompt")))
    out = capsys.readouterr().out
    assert "Sent to the maintainer" in out
    assert "https://github.com/x/y/issues/9" in out


def test_auto_send_without_upload_configured_is_honest(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {"bugreport_upload_url": ""})
    bugreport.report_failure(summary="bug", interactive=False, auto_send=True)
    out = capsys.readouterr().out
    assert "No hosted send channel is configured" in out
    assert "Sent to the maintainer" not in out


def test_auto_send_upload_failure_is_never_reported_as_success(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})

    def _boom(*a, **k):
        raise bugreport.LocalmError("upload failed", reason="502 from proxy")
    monkeypatch.setattr(bugreport, "upload_report", _boom)
    bugreport.report_failure(summary="bug", interactive=False, auto_send=True)
    out = " ".join(capsys.readouterr().out.split())   # collapse rich's line-wrapping
    assert "Sent to the maintainer" not in out
    assert "Could not send it" in out
    # The email fallback is offered (now naming the maintainer address).
    assert "email it to" in out and bugreport.MAINTAINER_EMAIL in out


# --------------------------- process-wide net ----------------------------- #

def test_thread_excepthook_reports_without_prompting(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    args = types.SimpleNamespace(
        exc_type=ValueError, exc_value=ValueError("worker boom"),
        exc_traceback=None, thread=types.SimpleNamespace(name="jobs-runner"))
    bugreport._handle_thread_exception(args)
    assert len(calls) == 1
    assert calls[0]["interactive"] is False
    assert calls[0]["context"]["thread"] == "jobs-runner"


def test_thread_excepthook_ignores_systemexit(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    args = types.SimpleNamespace(
        exc_type=SystemExit, exc_value=SystemExit(0),
        exc_traceback=None, thread=types.SimpleNamespace(name="t"))
    bugreport._handle_thread_exception(args)
    assert calls == []


def test_main_excepthook_reports_real_error(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    bugreport._handle_main_exception(ValueError, ValueError("boom"), None)
    assert len(calls) == 1
    assert "unexpected error" in calls[0]["summary"]


def test_main_excepthook_uses_localmerror_fields(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    err = bugreport.LocalmError("backend dead", reason="no driver", context={"x": 1})
    bugreport._handle_main_exception(bugreport.LocalmError, err, None)
    assert calls[0]["summary"] == "backend dead"
    assert calls[0]["reason"] == "no driver"
    assert calls[0]["context"] == {"x": 1}


def test_main_excepthook_keyboardinterrupt_does_not_report(monkeypatch):
    calls = []
    monkeypatch.setattr(bugreport, "report_failure", lambda **k: calls.append(k))
    monkeypatch.setattr(sys, "__excepthook__", lambda *a: None)
    bugreport._handle_main_exception(KeyboardInterrupt, KeyboardInterrupt(), None)
    assert calls == []


def test_install_global_handlers_noop_under_pytest(monkeypatch):
    monkeypatch.setattr(bugreport, "_handlers_installed", False)
    # pytest is in sys.modules, so the default (unforced) call is a deliberate no-op.
    assert bugreport.install_global_handlers() is False


def test_install_global_handlers_force_sets_hooks(monkeypatch):
    monkeypatch.setattr(bugreport, "_handlers_installed", False)
    orig_e, orig_t = sys.excepthook, threading.excepthook
    try:
        assert bugreport.install_global_handlers(force=True) is True
        assert sys.excepthook is bugreport._handle_main_exception
        assert threading.excepthook is bugreport._handle_thread_exception
    finally:
        sys.excepthook, threading.excepthook = orig_e, orig_t


# --------------------------- editable file is what's sent ----------------- #

def test_report_failure_sends_edited_file_not_original(tmp_path, monkeypatch):
    """'Edit it before sending' must be true: the email/issue body is read back
    from the (possibly edited) file, not the original generated text."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    edited = tmp_path / "bug-reports" / "edited.md"

    def fake_save(text, when=None):
        edited.parent.mkdir(parents=True, exist_ok=True)
        edited.write_text("EDITED REPORT BODY", encoding="utf-8")
        return edited
    monkeypatch.setattr(bugreport, "save_report", fake_save)

    opened = []
    bugreport.report_failure(
        summary="bug", interactive=True,
        open_browser=lambda u: opened.append(u), prompt=lambda _t: "2")  # [2] = email
    assert opened
    assert "EDITED REPORT BODY" in unquote(opened[0])   # the edit, not the original


# --------------------------- file permissions ----------------------------- #

@pytest.mark.skipif(os.name != "posix", reason="POSIX file mode bits")
def test_save_report_is_owner_only(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    path = bugreport.save_report("secretish diagnostics", when="t")
    assert path is not None
    assert stat.S_IMODE(os.stat(path).st_mode) == 0o600


# --------------------------- the bug-report CLI command ------------------- #

def test_bug_report_command_via_cli(tmp_path, monkeypatch):
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    from localm.cli import main
    res = CliRunner().invoke(main, ["bug-report", "-m", "my problem"])
    assert res.exit_code == 0, res.output
    assert "Filing a bug report" in res.output
    assert "my problem" in res.output
    assert "Sorry -" not in res.output               # user-initiated, not a crash
    assert list((tmp_path / "bug-reports").glob("*.md"))


def test_bug_report_command_send_flag_uploads_immediately(tmp_path, monkeypatch):
    """`localm bug-report --send` is the fix's whole point: a working, login-free
    send path that a tester in a non-tty shell (or told the exact command by the
    maintainer) can actually run."""
    monkeypatch.setattr("localm.config.home_dir", lambda: tmp_path)
    monkeypatch.setattr("localm.config.load_config", lambda: {
        "bugreport_upload_url": "https://proxy.example/"})
    monkeypatch.setattr(bugreport, "upload_report",
                        lambda *a, **k: {"url": "https://github.com/x/y/issues/3"})
    from localm.cli import main
    res = CliRunner().invoke(main, ["bug-report", "-m", "my problem", "--send"])
    assert res.exit_code == 0, res.output
    assert "Sent to the maintainer" in res.output
    assert "https://github.com/x/y/issues/3" in res.output


class TestRecommendedBackendMatchesInstallPolicy:
    """The report's "Recommended backend" must be the policy the INSTALLER would
    apply, not the blanket "vulkan whenever a GPU exists" detection value.

    A real report (#833) from an NVIDIA-on-Windows box said "Recommended backend:
    vulkan" while that box's policy is cuda (#765) and it was in fact running the
    CUDA runtime. A diagnostics field that contradicts what the installer would
    provision sends triage after the wrong thing."""

    def _diag_with(self, monkeypatch, vendors, platform):
        from localm import hwdetect
        det = hwdetect.Detection(vendors=vendors, recommended="vulkan",
                                 source="test", gpu_names=" ".join(vendors))
        monkeypatch.setattr(hwdetect, "detect", lambda: det)
        monkeypatch.setattr(sys, "platform", platform)
        return bugreport.collect_diagnostics({})

    def test_nvidia_on_windows_reports_cuda_not_vulkan(self, monkeypatch):
        diag = self._diag_with(monkeypatch, ["nvidia"], "win32")
        assert diag["recommended_backend"] == "cuda", (
            "an NVIDIA Windows box reported a backend the installer would not "
            "provision - the #833 triage trap")

    def test_no_gpu_still_reports_cpu(self, monkeypatch):
        diag = self._diag_with(monkeypatch, [], "win32")
        assert diag["recommended_backend"] == "cpu"

    def test_nvidia_on_linux_stays_vulkan(self, monkeypatch):
        """The Linux CUDA build needs a system toolkit localm cannot self-provide,
        so vulkan genuinely IS the policy there - the fix must not overreach."""
        diag = self._diag_with(monkeypatch, ["nvidia"], "linux")
        assert diag["recommended_backend"] == "vulkan"
