# SPDX-License-Identifier: AGPL-3.0-or-later
"""scripts/check_ci_requirements.py and the workflow that runs it."""

import importlib.util
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "check_ci_requirements.py"
WORKFLOW = ROOT / ".github" / "workflows" / "requirements-currency.yml"


def _load():
    spec = importlib.util.spec_from_file_location("check_ci_requirements", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


mod = _load()

SAMPLE = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile - -o /tmp/aaa/x.txt
click==8.5.0 \\
    --hash=sha256:255bc9599cf7748b4b1a446ccc735421bd08a2ae529a8b88597d3de5664ee360
    # via mutmut
Torch==2.13.0+cpu \\
    --hash=sha256:ba0d2089de75ea0310e2dde03160e6ca10009947fb95a182f9b54021bb272e34
"""


def test_pins_reads_every_pinned_name_lowercased():
    assert mod.pins(SAMPLE) == {"click": "8.5.0", "torch": "2.13.0+cpu"}


def test_the_committed_sets_pin_what_the_readme_commands_name():
    assert mod.pins((mod.REQUIREMENTS / "torch-cpu.txt").read_text(encoding="utf-8"))["torch"]
    assert mod.pins((mod.REQUIREMENTS / "mutmut.txt").read_text(encoding="utf-8"))["mutmut"]


def test_drift_ignores_only_the_header_lines_that_record_the_output_path():
    other_path = SAMPLE.replace("/tmp/aaa/x.txt", "/var/zzz/y.txt")
    assert mod.drift(SAMPLE, other_path) == []


def test_drift_reports_a_changed_pin():
    lines = mod.drift(SAMPLE, SAMPLE.replace("click==8.5.0", "click==8.4.0"))
    assert "-click==8.5.0 \\" in lines and "+click==8.4.0 \\" in lines


def test_drift_reports_a_changed_hash():
    assert mod.drift(SAMPLE, SAMPLE.replace("255bc9", "000000"))


def _fake_osv(vulnerable: set[str], pages: bool = False, short: bool = False):
    seen = []

    def post(url, body):
        seen.append((url, body))
        results = [{"vulns": [{"id": "GHSA-test"}]} if q["version"] in vulnerable else {}
                   for q in body["queries"]]
        if pages and results:
            results[0]["next_page_token"] = "more"
        return {"results": results[:-1] if short else results}

    return post, seen


def test_advisories_reports_only_the_pins_that_have_one_and_drops_the_local_label():
    post, seen = _fake_osv({"2.13.0"})
    hits = mod.advisories({"click": "8.5.0", "torch": "2.13.0+cpu"}, post)
    assert hits == {"torch==2.13.0+cpu": ["GHSA-test"]}
    assert {q["version"] for q in seen[0][1]["queries"]} == {"8.5.0", "2.13.0"}
    assert all(q["package"]["ecosystem"] == "PyPI" for q in seen[0][1]["queries"])


def test_advisories_is_empty_when_nothing_is_listed():
    post, _ = _fake_osv(set())
    assert mod.advisories({"click": "8.5.0"}, post) == {}


def test_advisories_refuses_a_partial_answer_instead_of_reporting_clean():
    post, _ = _fake_osv(set(), short=True)
    with pytest.raises(mod.CheckError):
        mod.advisories({"click": "8.5.0", "torch": "2.13.0"}, post)
    post, _ = _fake_osv(set(), pages=True)
    with pytest.raises(mod.CheckError):
        mod.advisories({"click": "8.5.0"}, post)


def test_main_exits_1_on_an_advisory_and_2_when_the_lookup_cannot_run(monkeypatch, capsys):
    monkeypatch.setattr(mod, "advisories", lambda found: {"click==8.5.0": ["GHSA-test"]})
    assert mod.main(["--only", "advisories"]) == 1
    assert "ADVISORY click==8.5.0" in capsys.readouterr().out

    def down(found):
        raise mod.CheckError("network down")

    monkeypatch.setattr(mod, "advisories", down)
    assert mod.main(["--only", "advisories"]) == 2


def test_the_workflow_runs_the_script_on_a_schedule_never_on_pull_request():
    doc = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))
    triggers = doc.get(True, doc.get("on"))
    assert {"schedule", "workflow_dispatch", "push"} <= set(triggers)
    assert "pull_request" not in triggers
    assert doc["permissions"] == {"contents": "read"}
    runs = "\n".join(s.get("run", "") for s in doc["jobs"]["committed-sets"]["steps"])
    assert "scripts/check_ci_requirements.py" in runs
    assert 'if [ "$rc" = "2" ]' in runs
