# SPDX-License-Identifier: AGPL-3.0-or-later
"""Graceful failure + an autogenerated, user-editable bug report.

On a failure localm reports what broke and why in plain language, then offers a
prefilled report the user can read and edit before anything leaves their machine.

Channels:
  * **hosted send** (`--send`, or menu [1]) - uploads through the account-less
    Cloudflare Worker proxy, which files the GitHub issue server-side. No
    GitHub account is needed; this is the only channel that creates an issue
    automatically.
  * **email** - opens the user's mail app prefilled to the maintainer.
  * **do it yourself** - the report is always saved to a file.

The maintainer's contact email is published here for bug reports.

Diagnostics collected:
  * OS / arch / Python, GPU vendor + NVIDIA driver / CUDA capability, the chosen
    and recommended backend, and the *names* of provisioned native libraries.
  * App state: the loaded model, effective backend, context ceiling, session
    (privacy) mode, debug flag, and enabled plugins.
  * An ALLOWLISTED, scrubbed subset of config (context sizing, ports, media URLs,
    privacy mode); path values are home-scrubbed and URL values
    credential-scrubbed.
  * Versions of the dependencies that shape a failure (native runtime, HF + server
    stacks).
  * The in-memory recent-activity log (INFO+ breadcrumbs; the raw model output is
    DEBUG-level and never enters this in-process ring buffer) and, for a GUI
    report, the browser context + recent JS console errors.

Never collected: the API key, environment variables, config secrets, or the raw
chat/transcript content. The user reviews and edits the report before sending.

Chat content lands in the on-disk debug log at DEBUG level when --debug (or
keep_diagnostics) is on and the session is not privacy mode. It never reaches a
REPORT: the digest builder (localm/_log_digest.py) drops every record from a
debug_content_enabled()-gated write site (the raw model reply, a memory-embed
content snippet, a web-tool query) before it is collapsed or classified, so none
of them can appear in ``_recent_log_tail`` whatever the content itself says.
"""

from __future__ import annotations

import platform
import re
import sys
import threading
import traceback
import urllib.parse
import webbrowser
from pathlib import Path
from typing import Optional

from rich.console import Console

from localm import pathscrub

console = Console(highlight=False)

# Maintainer contact address for bug reports.
MAINTAINER_EMAIL = "theilige@gmail.com"

# Maximum characters of report body placed in a mailto: prefill.
_MAX_PREFILL_BODY = 1500


class LocalmError(Exception):
    """A user-facing, reportable failure.

    Raised when a command hits a known, describable problem. The CLI's single
    graceful handler turns it into a "sorry, X went wrong because Y" message and
    offers a bug report. Carries a human *summary*, an optional *reason*, and
    diagnostic *context* for the report."""

    def __init__(self, summary: str, reason: str = "",
                 context: Optional[dict] = None, *,
                 stage: Optional[str] = None, hint: Optional[str] = None):
        super().__init__(summary)
        self.summary = summary
        self.reason = reason
        self.context = context or {}
        # For an upload failure: where it failed (offline_or_dns / unreachable /
        # tls / timeout / server_rejected / no_endpoint / rate_limited / unknown)
        # and an actionable hint. Both None for a non-upload LocalmError.
        self.stage = stage
        self.hint = hint


class RateLimitedError(LocalmError):
    """The bug-report proxy returned HTTP 429 (rate limited).

    Carries *retry_after* (seconds) for a caller that wants to wait and retry. A
    subclass of LocalmError, so ``except LocalmError`` handlers catch it as a
    send failure; a caller that wants the retry catches this class first."""

    def __init__(self, retry_after: int = 30, reason: str = ""):
        try:
            ra = max(1, int(retry_after))
        except (TypeError, ValueError):
            ra = 30
        super().__init__("the bug-report server is rate limiting reports",
                         reason=reason or f"try again in about {ra} seconds",
                         context={"retry_after": ra},
                         stage="rate_limited",
                         hint=(f"The bug-report server is busy right now and asked to "
                               f"wait about {ra}s before trying again. Your report is "
                               f"saved either way."))
        self.retry_after = ra


def _localm_version() -> str:
    # Live VERSION-file read, falling back to installed metadata.
    try:
        from localm._version import read_version
        return read_version()
    except Exception:
        return "unknown"


def _runtime_libs() -> tuple:
    """``(binary_dir, sorted native library file NAMES, lib_filename())``.

    THE ARITY VARIES: returns the 2-tuple ``(None, [])`` when no runtime
    directory is resolved, and the 3-tuple ``(None, [], "")`` when the listing
    raises. Index the result rather than unpacking it. Names only, never full
    paths beyond the resolved dir, never contents.
    """
    try:
        from localm.inference.backends.llamacpp._loader import (
            lib_filename, runtime_binary_dir)
        d = runtime_binary_dir()
        if d is None:
            return None, []
        # Shared libraries only; the bundled llama-*.exe tools are excluded.
        names = sorted(
            f.name for f in Path(d).iterdir()
            if f.is_file() and (f.suffix.lower() in (".dll", ".so", ".dylib")
                                or ".so." in f.name)
        )
        return d, names, lib_filename()
    except Exception:
        return None, [], ""


def collect_diagnostics(context: Optional[dict] = None) -> dict:
    """Gather a safe, useful environment snapshot. Never raises."""
    context = dict(context or {})
    diag: dict = {}
    try:
        diag["localm_version"] = _localm_version()
        diag["python"] = sys.version.split()[0]
        diag["platform"] = platform.platform()
        diag["machine"] = platform.machine()
    except Exception:
        # Best-effort: a failure here omits these fields.
        pass

    try:
        from localm import hwdetect
        det = hwdetect.detect()
        diag["gpu_vendors"] = det.vendors or []
        # The backend the installer would actually provision.
        diag["recommended_backend"] = hwdetect.recommended_install_backend(det)
        diag["detect_source"] = det.source
    except Exception:
        diag["gpu_vendors"] = []

    # NVIDIA driver / CUDA capability, when an NVIDIA GPU is involved.
    try:
        from localm.setup_llama import nvidia_preflight
        if "nvidia" in diag.get("gpu_vendors", []) or context.get("backend") == "cuda":
            nv = nvidia_preflight()
            if nv.present:
                diag["nvidia_gpu"] = nv.gpu_name
                diag["nvidia_driver"] = nv.driver_version
                diag["nvidia_cuda_capability"] = nv.cuda_capability
                diag["nvidia_compute_capability"] = nv.compute_capability
                diag["nvidia_cuda_line"] = nv.cuda_line
    except Exception:
        # Best-effort: a failure omits these fields.
        pass

    try:
        res = _runtime_libs()
        binary_dir = res[0]
        names = res[1]
        diag["native_runtime_provisioned"] = binary_dir is not None
        diag["native_libs"] = names
    except Exception:
        # Best-effort: a failure omits the native library names.
        pass

    # Which llama.cpp build is installed, and whether the user pinned one.
    try:
        from localm import setup_llama
        build = setup_llama.installed_build()
        backend = setup_llama.installed_backend()
        if backend:
            diag["native_runtime_backend"] = backend
        # "not recorded" marks an install that predates build-tag recording.
        diag["native_runtime_build"] = build or "not recorded"
        pin = setup_llama.pinned_tag()
        if pin:
            diag["native_runtime_pin"] = pin
    except Exception:
        # Best-effort: a failure omits these fields.
        pass

    # Caller-supplied context (chosen backend, the operation, etc.).
    for k in ("operation", "backend", "requested_backend", "with_cudart"):
        if k in context:
            diag[k] = context[k]

    # App / runtime state. Each collector is independently guarded and returns
    # empty on failure.
    diag["loaded_model"] = _loaded_model_info()
    diag.update(_runtime_state())          # session_mode, debug_mode
    diag["enabled_plugins"] = _enabled_plugins()
    diag["config_subset"] = _safe_config_subset()
    diag["config_unreadable"] = _config_unreadable()
    diag["dependencies"] = _dependency_versions()
    return diag


# Replaces Path.home() with "~" in both separator forms, case-insensitively on
# Windows, and always applies the known-home-root username strip as a backstop.
# Keeps the INSTALL dir, which pathscrub.scrub_paths drops.
_scrub_home = pathscrub.scrub_user_paths


def _scrub_url_creds(text: str) -> str:
    """Strip ``user:pass@`` credentials from any URL-ish value."""
    if not text:
        return text
    return re.sub(r"(://)[^/@\s]+@", r"\1<redacted>@", text)


# Credentials are redacted by PARAMETER NAME, never by the value's format. The
# name is kept, so the report still shows that the endpoint was credentialed and
# which endpoint it is.
#
# A name may sit anywhere a ``name=value`` pair can appear, not only after a
# ``?`` or ``&``. Three branches all feed ONE capture group, so the substitution
# keeps the name and drops only the value:
#
#   1. after a literal ?/&;
#   2. anywhere else, UNPREFIXED - only names that mean a credential and nothing
#      else (api_key, token, secret, password, passwd, pwd, ...);
#   3. anywhere else, PREFIXED - the same names plus the short generic ones
#      (key, auth, sig), admitted only behind a prefix.
_QUERY_SECRET_RE = re.compile(
    r"(?i)((?:"
    # 1. Immediately after a query delimiter.
    r"(?<=[?&])(?:api[_-]?key|key|token|secret|password|passwd|pwd|auth"
    r"|access[_-]?token|sig|signature)"
    # 2. Anywhere else, UNPREFIXED: only the names that mean a credential
    #    and nothing else.
    r"|(?<![A-Za-z0-9])(?:api[_-]?key|token|secret|password|passwd|pwd"
    r"|access[_-]?token|signature)"
    # 3. Anywhere else, PREFIXED. Matched from the SEPARATOR, never from the
    #    prefix: this branch must carry no repetition, so the match stays linear.
    #    The prefix is not consumed and survives outside the match, so
    #    ``SECRET_KEY=x`` matches ``_KEY=x`` and reads back as
    #    ``SECRET_KEY=<redacted>``. This branch admits the short generic names.
    r"|(?<=[A-Za-z0-9])[_-](?:api[_-]?key|token|secret|password|passwd|pwd"
    r"|access[_-]?token|signature|key|auth|sig)"
    r")=)"
    # A short list of literal values that cannot be a secret is left alone, so
    # ``LOCALM_REQUIRE_AUTH=1``, ``require_auth=true`` and ``has_token=false``
    # survive. The literal has to be the WHOLE value, so ``api_key=truesecret123``
    # and ``api_key=10`` still redact. Closing markup may follow it, so
    # ``(require_auth=1)`` is still a flag while ``api_key=1)SECRET`` stays
    # redacted.
    r"(?![\"']?(?:true|false|none|null|nil|yes|no|on|off|enabled|disabled|[01])"
    r"[`\"'\)\]\}]{0,4}(?:[\s&#]|$))"
    # The value may be quoted. An unterminated quote redacts to the next quote on
    # the line, or to the end of the line when there is none, never across a
    # newline.
    r"(?:\"[^\"\r\n]*\"?|'[^'\r\n]*'?|[^&\s#\"'\)\]\}]*)"
)

# Redacts a pasted HTTP header line, e.g. "X-Api-Key: <value>", for an explicit
# set of credential header names.
_HEADER_SECRET_RE = re.compile(
    r"(?i)((?:x-)?(?:api[_-]key|api[_-]token|auth[_-]token)\s*:\s*)\S+"
)


def _scrub_query_and_header_secrets(text: str) -> str:
    """Redact credential-ish URL query parameters and HTTP header lines, by NAME.

    Idempotent: the ``<redacted>`` replacement contains none of the delimiters
    the value patterns stop on, so a second pass leaves an already-redacted
    value unchanged."""
    if not text:
        return text
    text = _QUERY_SECRET_RE.sub(r"\1<redacted>", text)
    text = _HEADER_SECRET_RE.sub(r"\1<redacted>", text)
    return text


# Bearer tokens and API keys appearing anywhere in free-form text.
_BEARER_RE = re.compile(r"(?i)(bearer\s+)[A-Za-z0-9._\-]{8,}")
_APIKEY_RE = re.compile(r"(?i)\b(?:sk|localm[_-]sk)-[A-Za-z0-9._\-]{12,}")


def _scrub_secrets(text: str) -> str:
    """Run every scrubber over untrusted text: home paths (username), URL
    ``user:pass@`` credentials, credential-named query params / header lines,
    and bearer / API-key tokens. Used for client-supplied fields and the
    bundled log tails / activity ring a report carries."""
    if not text:
        return text
    text = _scrub_home(text)
    text = _scrub_url_creds(text)
    text = _scrub_query_and_header_secrets(text)
    text = _BEARER_RE.sub(r"\1<redacted>", text)
    text = _APIKEY_RE.sub("<redacted>", text)
    return text


# Allowlist of config keys echoed into a report. Path-like values are
# home-scrubbed and URL-like values credential-scrubbed before rendering.
_SAFE_CONFIG_KEYS = (
    "binary_dir", "n_ctx", "n_ctx_max", "ctx_auto", "n_gpu_layers",
    "n_gpu_layers_auto", "max_tokens",
    "model_swap_policy", "idle_unload_seconds", "reload_llm_after_imagine",
    "port", "require_auth", "cors_origins", "mode", "chat_mode", "coder_mode",
    "net_mode", "comfy_launch_cmd", "comfy_workdir", "comfy_api_url",
    "net_search_url", "coder_reviewer", "coder_review", "voice_stt_model",
)

# Distributions whose versions are reported. Absent packages are skipped.
_REPORTED_DISTS = (
    "localm", "localm-llama-runtime", "llama-cpp-python", "torch", "transformers",
    "huggingface-hub", "fastapi", "uvicorn", "ctranslate2", "faster-whisper",
)


def _loaded_model_info() -> dict:
    """Snapshot of the in-process inference engine (model, backend, loaded?, ctx).

    Empty when no server engine is loaded in THIS process (e.g. a CLI
    ``bug-report``) or it cannot be read. Never raises."""
    try:
        from localm.inference import http_server as hs
        eng = getattr(hs, "_engine", None)
        if eng is None:
            return {}
        info: dict = {
            "model": getattr(eng, "display_name", "") or "(unnamed)",
            "loaded": bool(getattr(eng, "loaded", False)),
        }
        backend = getattr(eng, "_backend", None)
        if backend is not None:
            info["backend"] = type(backend).__name__
        ctx = getattr(eng, "effective_ctx_max", None)
        if ctx:
            info["effective_ctx_max"] = ctx
        return info
    except Exception:
        return {}


def _runtime_state() -> dict:
    """Session mode + debug flag. Never raises."""
    state: dict = {}
    try:
        from localm.audit import effective_mode
        state["session_mode"] = effective_mode("server").value
    except Exception:
        # Best-effort: the report omits the session mode when it cannot be read.
        pass
    try:
        from localm.debuglog import debug_enabled
        state["debug_mode"] = bool(debug_enabled())
    except Exception:
        # Best-effort: the report omits the debug flag when it cannot be read.
        pass
    return state


def _enabled_plugins() -> list:
    """Names of enabled engine plugins, from config. Never raises."""
    try:
        from localm.config import load_config
        pl = load_config().get("plugins_enabled", [])
        return [str(p) for p in pl] if isinstance(pl, list) else []
    except Exception:
        return []


def _safe_config_subset() -> dict:
    """An allowlisted, scrubbed slice of the user config: enough to debug a setup
    problem (context sizing, ports, media URLs, privacy mode) without any secret.
    Never raises."""
    try:
        from localm.config import load_config
        cfg = load_config()
    except Exception:
        return {}
    out: dict = {}
    for key in _SAFE_CONFIG_KEYS:
        if key not in cfg:
            continue
        val = cfg[key]
        if isinstance(val, str) and val:
            val = _scrub_query_and_header_secrets(_scrub_url_creds(_scrub_home(val)))
        out[key] = val
    return out


def _config_unreadable() -> bool:
    """True only when config.json (or its .bak) EXISTS and could not be parsed,
    in which case _safe_config_subset() is showing built-in defaults rather than
    the user's real settings. Never raises."""
    try:
        from localm.config import load_config_checked
        return not load_config_checked()[1]
    except Exception:
        # read_ok could not be determined; report no corruption.
        return False


def _dependency_versions() -> dict:
    """Versions of the packages that shape a localm failure (native runtime, HF
    stack, server stack). Absent packages are omitted. Never raises."""
    out: dict = {}
    try:
        from importlib.metadata import PackageNotFoundError, version
    except Exception:
        return out
    for dist in _REPORTED_DISTS:
        try:
            out[dist] = version(dist)
        except PackageNotFoundError:
            continue
        except Exception:
            continue
    return out


def _format_error(error: Optional[BaseException]) -> str:
    if error is None:
        return ""
    tb = "".join(traceback.format_exception(type(error), error, error.__traceback__))
    # Full scrub: a traceback can embed a credentialed URL or a pasted token.
    tb = _scrub_secrets(tb)
    # Keep the last frames only.
    lines = tb.strip().splitlines()
    if len(lines) > 25:
        lines = ["... (earlier frames trimmed) ..."] + lines[-24:]
    return "\n".join(lines)


# Cap on how much of the raw log file is read before digesting.
_LOG_TAIL_READ_BYTES = 2_000_000


def _find_run_log(home=None, pid=None):
    """The Path to a run's OWN log, matched by the pid embedded in the log
    filename (localm_<date>_<time>_<pid>.log), or None if none is found.

    With no pid match, falls back to the most recent log that is not this
    process's own."""
    from pathlib import Path as _P
    if home is None:
        from localm.debuglog import logs_dir
        d = logs_dir()
    else:
        d = _P(home) / "logs"
    if not d.is_dir():
        return None
    logs = sorted(d.glob("*.log"), key=lambda p: p.stat().st_mtime, reverse=True)
    if pid is not None:
        for p in logs:
            if p.stem.endswith(f"_{pid}"):
                return p
    # No pid match: fall back to the most recent log that is not this run's.
    import os as _os
    cur = f"_{_os.getpid()}.log"
    return next((p for p in logs if not p.name.endswith(cur)), None)


# Reason attached to a report when no log file matched the run's pid.
_LOG_UNAVAILABLE_NO_FILE = "no log file was found for that run"


def _log_failure_reason(exc: BaseException) -> str:
    """A one-line, PATH-FREE description of why reading the log failed, safe to
    put in a share-intended report.

    Built from the exception CLASS NAME plus ``strerror`` (the OS's own errno
    text, which carries no path); on a non-OSError the class name alone is used.
    A detail containing a path separator is dropped outright, _scrub_secrets is
    applied as a backstop, and the result is truncated to 200 characters.
    """
    name = type(exc).__name__
    detail = getattr(exc, "strerror", None)
    if not isinstance(detail, str):
        detail = ""
    detail = detail.strip()
    # Anything path-shaped is discarded whole.
    if any(sep in detail for sep in ("/", "\\")):
        detail = ""
    reason = f"{name}: {detail}" if detail else name
    return _scrub_secrets(reason)[:200]


def _recent_log_tail_result(home=None, pid=None, max_chars: int = 6000) -> tuple:
    """``(digest, unavailable_reason)`` - the digest _recent_log_tail returns,
    plus WHY it is empty when it is empty.

    At most one of the two is non-empty. Both empty means the log was collected
    and held nothing notable. Never raises."""
    try:
        chosen = _find_run_log(home, pid)
        if chosen is None:
            return "", _LOG_UNAVAILABLE_NO_FILE
        raw = chosen.read_text(encoding="utf-8", errors="replace")
        truncated = len(raw) > _LOG_TAIL_READ_BYTES
        if truncated:
            raw = raw[-_LOG_TAIL_READ_BYTES:]
        from localm._log_digest import build_digest
        # A truncated tail can start mid-way through a content-gated write with
        # no header of its own, so the digest builder starts tainted.
        return _scrub_secrets(
            build_digest(raw, max_chars=max_chars, start_tainted=truncated)), ""
    except Exception as e:
        # Best-effort: the caller is told why the digest came back empty.
        return "", f"the log file could not be read ({_log_failure_reason(e)})"


def _recent_log_tail(home=None, pid=None, max_chars: int = 6000) -> str:
    """A digest of the crashed run's OWN log, matched by the pid embedded in the
    log filename (localm_<date>_<time>_<pid>.log): EVERY warning/error (with its
    full traceback) from the whole run, with runs of near-duplicate benign lines
    (e.g. routine ``GET /api/stats`` polling) collapsed to one line plus a repeat
    count. Chat content (a raw model reply, a memory-embed snippet, a web-tool
    query) is dropped by build_digest before this ever sees it, whatever the
    content itself says. Home paths are scrubbed. Never raises.

    Returns only the digest; _recent_log_tail_result also reports why an empty
    digest is empty."""
    return _recent_log_tail_result(home, pid, max_chars)[0]


# Maximum age of a hang trace that may be attached to a report.
_HANG_TRACE_MAX_AGE_S = 24 * 3600


def _recent_hang_traces(home=None, max_chars: int = 8000, *, pid=None) -> str:
    """The event-loop hang trace captured by the run being reported
    (``<logs>/hang_<date>_<pid>.log``), if the always-on stall watchdog captured
    one - every thread's stack at the moment the server froze, which is exactly
    what diagnoses an intermittent "it hung" report. Kept HEAD-first (the first
    snapshot names where the loop first stuck). Home paths are scrubbed. Empty
    when that run captured no freeze. Never raises.

    Matched to *pid* - the run this report is about - and additionally bounded
    by _HANG_TRACE_MAX_AGE_S. Both filters apply: a pid is not an identity (pids
    are reused), and a recent freeze in a DIFFERENT localm instance is not this
    report's. A caller that cannot name the run (no pid) gets nothing."""
    try:
        import time as _time
        from pathlib import Path as _P
        if home is None:
            from localm.debuglog import logs_dir
            d = logs_dir()
        else:
            d = _P(home) / "logs"
        if not d.is_dir() or pid is None:
            return ""
        cutoff = _time.time() - _HANG_TRACE_MAX_AGE_S
        traces = sorted(
            (p for p in d.glob(f"hang_*_{pid}.log") if p.stat().st_mtime >= cutoff),
            key=lambda p: p.stat().st_mtime, reverse=True)
        if not traces:
            return ""
        text = traces[0].read_text(encoding="utf-8", errors="replace").strip()
        if not text:
            return ""
        scrubbed = _scrub_secrets(text)
        if len(scrubbed) > max_chars:
            scrubbed = scrubbed[:max_chars] + \
                "\n... (trace truncated - full stacks in the hang_*.log file)"
        return scrubbed
    except Exception:
        return ""


def live_server_hang_trace(home=None) -> str:
    """The event-loop hang trace captured by a LIVE server of this install, for a
    user-initiated ``localm bug-report`` filed from a SEPARATE process.

    Looks the server up in the live instance registry (``<home>/run/*.json``),
    keeps only entries whose pid is alive, and returns that server's pid-matched
    trace. With more than one live server, the most recently started one wins.
    Empty when no live server captured a freeze. Never raises."""
    try:
        from localm import instances
        if home is None:
            from localm.config import HOME_DIR
            home = HOME_DIR
        entries = sorted(instances.list_entries(home),
                         key=lambda e: e.get("started") or "", reverse=True)
        for entry in entries:
            pid = entry.get("pid")
            if not isinstance(pid, int) or not instances.pid_alive(pid):
                continue
            trace = _recent_hang_traces(home, pid=pid)
            if trace:
                return trace
        return ""
    except Exception:
        return ""


def _kv_lines(d: dict) -> list:
    """Render a flat dict as ``- key: value`` markdown lines (stable order)."""
    lines = []
    for k, v in d.items():
        if isinstance(v, list):
            v = ", ".join(str(x) for x in v) if v else "(none)"
        elif isinstance(v, bool):
            v = "yes" if v else "no"
        lines.append(f"- {k}: {v}")
    return lines


def _app_state_lines(diag: dict) -> list:
    """The "what the app was doing" half of the report: loaded model, effective
    backend, session mode, debug state, and enabled plugins."""
    lines = []
    lm = diag.get("loaded_model") or {}
    if lm:
        loaded = "loaded" if lm.get("loaded") else "NOT loaded"
        line = f"- Model: {lm.get('model', '(unnamed)')} ({loaded})"
        if lm.get("backend"):
            line += f", backend {lm['backend']}"
        if lm.get("effective_ctx_max"):
            line += f", ctx<={lm['effective_ctx_max']}"
        lines.append(line)
    else:
        lines.append("- Model: (no engine loaded in this process)")
    if "session_mode" in diag:
        lines.append(f"- Session mode: {diag['session_mode']}")
    if "debug_mode" in diag:
        lines.append(f"- Debug logging: {'on' if diag['debug_mode'] else 'off'}")
    plugins = diag.get("enabled_plugins")
    if plugins is not None:
        lines.append(f"- Enabled plugins: {', '.join(plugins) if plugins else '(none)'}")
    return lines


def build_report(summary: str, reason: str = "",
                 error: Optional[BaseException] = None,
                 context: Optional[dict] = None) -> str:
    """Render an editable markdown bug report."""
    # The user-typed summary and reason are scrubbed here, the single choke point
    # every caller passes through. _scrub_secrets is idempotent.
    summary = _scrub_secrets(summary)
    reason = _scrub_secrets(reason)
    ctx = context or {}
    # A user-composed report supplies these three fields via context; they are
    # absent for an automatic report.
    what_i_did = _scrub_secrets((ctx.get("what_i_did") or "").strip())
    what_i_expected = _scrub_secrets((ctx.get("what_i_expected") or "").strip())
    what_happened = _scrub_secrets((ctx.get("what_happened") or "").strip())
    diag = collect_diagnostics(context)
    err = _format_error(error)

    env_lines = []
    label = {
        "localm_version": "localm", "python": "Python", "platform": "OS",
        "machine": "Arch", "gpu_vendors": "GPU vendor(s)",
        "recommended_backend": "Recommended backend", "detect_source": "Detected via",
        "nvidia_gpu": "NVIDIA GPU", "nvidia_driver": "NVIDIA driver",
        "nvidia_cuda_capability": "Driver CUDA capability",
        "nvidia_compute_capability": "GPU compute capability",
        "nvidia_cuda_line": "Selected CUDA line",
        "native_runtime_provisioned": "Native runtime provisioned",
        "native_runtime_backend": "Native runtime backend",
        "native_runtime_build": "Native runtime build",
        "native_runtime_pin": "Native runtime pinned to",
        "native_libs": "Native libraries", "operation": "Operation",
        "backend": "Backend (effective)", "requested_backend": "Backend (requested)",
        "with_cudart": "Fetched CUDA runtime bundle",
    }
    for key, name in label.items():
        if key in diag:
            val = diag[key]
            if isinstance(val, list):
                val = ", ".join(str(x) for x in val) if val else "(none)"
            env_lines.append(f"- {name}: {val}")

    parts = [
        f"# localm bug report: {summary}",
        "",
        "## What I was doing",
        what_i_did or "<!-- Please describe what you ran and what you expected. -->",
        "",
    ]
    if what_i_expected:
        parts += ["## What I expected", what_i_expected, ""]
    if what_happened:
        happened_body = what_happened
    elif what_i_did:
        # The user described what they were doing but not what happened.
        happened_body = "(not stated)"
    else:
        # An automatic crash or LocalmError report: summary and reason describe
        # what happened.
        happened_body = summary + ((f"\n\nReason: {reason}") if reason else "")
    parts += [
        "## What happened",
        happened_body,
        "",
        "## App state",
        "\n".join(_app_state_lines(diag)),
        "",
        "## Environment",
        "\n".join(env_lines) if env_lines else "(could not collect environment)",
    ]

    config_subset = diag.get("config_subset") or {}
    if config_subset:
        section = ["", "## Configuration (safe subset)"]
        if diag.get("config_unreadable"):
            # Mark the values as defaults when config.json could not be read.
            section.append("(config.json exists but could not be read; the "
                            "values below are DEFAULTS, not the user's settings)")
        section.append("\n".join(_kv_lines(config_subset)))
        parts += section
    deps = diag.get("dependencies") or {}
    if deps:
        parts += ["", "## Dependencies", "\n".join(_kv_lines(deps))]

    if err:
        parts += ["", "## Error detail", "```", err, "```"]
    # Crash diagnostics passed via context: a faulthandler native trace and the
    # crashed run's own log tail, both home-scrubbed at their source.
    ctx = context or {}
    native = ctx.get("native_trace")
    if native:
        parts += ["", "## Native fault trace", "```", _scrub_home(str(native))[:4000], "```"]
    tail = ctx.get("recent_log_tail")
    if tail:
        parts += ["", "## Recent log (tail)", "```", _scrub_home(str(tail))[:4000], "```"]
    elif ctx.get("log_unavailable"):
        # Render why the log was not collected rather than omitting the section.
        parts += ["", "## Recent log (tail)",
                  f"(not collected: {_scrub_secrets(str(ctx['log_unavailable']))[:200]})"]
    hang = ctx.get("hang_traces")
    if hang:
        parts += ["", "## Server hang trace (event-loop stall)",
                  "The hang watchdog captured every thread's stack when the server "
                  "froze (the top of the main thread is the blocking call):",
                  "```", _scrub_home(str(hang))[:8000], "```"]

    # Always-on in-memory breadcrumbs (INFO+; no chat content).
    ring = _ring_activity()
    if ring:
        parts += ["", "## Recent activity (in-memory log)", "```",
                  _scrub_secrets("\n".join(ring[-80:]))[-4000:], "```"]

    # Browser/client context for a GUI-filed report (user agent, page, viewport,
    # recent JS console errors).
    client = ctx.get("client")
    if isinstance(client, dict) and client:
        parts += ["", "## Browser / client"] + _client_lines(client)

    parts += [
        "",
        "---",
        _report_footer(),
        "",
    ]
    return "\n".join(parts)


def _report_footer() -> str:
    """The in-app edit disclaimer build_report() appends."""
    return (f"Sent to the localm maintainer ({MAINTAINER_EMAIL}). "
            "You can edit anything above before sending.")


def _strip_report_footer(text: str) -> str:
    """Remove build_report()'s trailing edit-disclaimer block, if present.

    Called ONLY at the upload boundary (upload_report()); the local saved file
    and the GUI's download-for-manual-send copy keep the footer.

    Exact-suffix match built from the same _report_footer() text build_report()
    appends. Tolerates a missing trailing newline; a body that never had the
    footer, or had it edited away, is returned unchanged. Never raises."""
    footer = _report_footer()
    for suffix in (f"\n\n---\n{footer}\n", f"\n\n---\n{footer}"):
        if text.endswith(suffix):
            return text[: -len(suffix)]
    return text


def _ring_activity() -> list:
    """The in-memory recent-activity buffer, or [] if unavailable. Never raises."""
    try:
        from localm.debuglog import recent_activity
        lines = recent_activity()
        try:
            from localm.config import home_dir
            pre_log = home_dir() / "logs" / "pre_restart.log"
            if pre_log.exists():
                lines = pre_log.read_text(encoding="utf-8").splitlines() + ["--- RESTART ---"] + lines
                try:
                    pre_log.unlink(missing_ok=True)
                except OSError as e:
                    # The plaintext pre-restart log is deleted after being folded
                    # into the report; a failed delete is surfaced.
                    from localm.debuglog import logger
                    logger.warning(
                        "bugreport: could not delete %s after reading it (%s); "
                        "the plaintext log remains on disk", pre_log, e)
        except Exception:
            # Best-effort: on failure the in-memory activity is returned alone.
            pass
        return lines
    except Exception:
        return []


def _client_lines(client: dict) -> list:
    """Render the GUI-supplied browser context (user agent, page, viewport, recent
    console errors) for the report. All values are treated as untrusted text."""
    lines = []
    for field, label_ in (("userAgent", "User agent"), ("page", "Page"),
                          ("viewport", "Viewport"), ("appVersion", "GUI build")):
        val = client.get(field)
        if val:
            lines.append(f"- {label_}: {_scrub_secrets(str(val))[:300]}")
    console_errs = client.get("console")
    if isinstance(console_errs, list) and console_errs:
        rendered = "\n".join(_scrub_secrets(str(e)) for e in console_errs[-40:])
        lines += ["", "Recent browser console errors:", "```", rendered[-3000:], "```"]
    return lines


def save_report(text: str, when: Optional[str] = None) -> Optional[Path]:
    """Write the report to the data dir and return its path (or None on failure).
    *when* is a caller-supplied timestamp string (kept injectable for tests)."""
    try:
        from localm.config import home_dir
        base = home_dir() / "bug-reports"
    except Exception:
        # Fallback when config cannot be imported: stay inside the install dir.
        base = Path(__file__).resolve().parents[1] / "home" / "bug-reports"
    try:
        base.mkdir(parents=True, exist_ok=True)
        if when is None:
            import time
            when = time.strftime("%Y%m%d-%H%M%S")
        path = base / f"bug-{when}.md"
        path.write_text(text, encoding="utf-8")
        # Restrict the report to its owner. chmod is a no-op on Windows.
        try:
            path.chmod(0o600)
        except OSError:
            # Best-effort hardening; the data dir's own permissions still apply.
            pass
        return path
    except Exception:
        return None


def report_title(summary: str, what_happened: str, description: str) -> str:
    """The final report/issue title: *summary* verbatim if the caller gave one
    explicitly, else derived from *what_happened* (a more useful issue title
    than "what I was doing"), falling back to *description* - first line
    only, truncated to 120 chars, never empty."""
    if not summary:
        title_source = what_happened or description
        summary = title_source.splitlines()[0] if title_source else ""
    return summary.strip()[:120] or "user-reported issue"


# Serialises save_user_report(), which the GUI route runs on worker threads:
# _ring_activity() reads then deletes the shared pre_restart.log, and
# save_report() can collide on a same-second timestamped filename. Not shared
# with report_failure.
_SAVE_REPORT_LOCK = threading.Lock()


def save_user_report(description: str = "", *, summary: str = "",
                     what_i_expected: str = "", what_happened: str = "",
                     include_log: bool = False,
                     client: Optional[dict] = None,
                     extra_hang_trace: str = "") -> Optional[Path]:
    """Build and save a USER-initiated bug report and return its path.

    The shared backend for the GUI "Report a bug" control and the
    ``localm bug-report`` CLI: *description* fills the "What I was doing"
    section, and *what_i_expected* and *what_happened* fill their own sections.
    *summary* overrides the title; when omitted it is derived from
    *what_happened*, falling back to *description* when that too is empty. The
    safe environment snapshot is collected as usual (loaded model, effective
    backend, session mode, a safe config subset, key dependency versions, and
    the in-memory recent-activity log), and with *include_log* the current run's
    on-disk debug log tail is attached (home-scrubbed at source, with every
    chat-content record dropped by build_digest regardless of what it says -
    never the API key, config secrets, or chat content). *client* is an optional
    GUI-supplied browser context (user agent, page, viewport, recent JS console
    errors). *extra_hang_trace* supplies a freeze trace found in a DIFFERENT
    process. Returns None on a write failure. Serialized on
    ``_SAVE_REPORT_LOCK``."""
    with _SAVE_REPORT_LOCK:
        description = (description or "").strip()
        what_i_expected = (what_i_expected or "").strip()
        what_happened = (what_happened or "").strip()
        summary = report_title(summary, what_happened, description)
        context: dict = {"operation": "gui-bug-report"}
        if description:
            context["what_i_did"] = description
        if what_i_expected:
            context["what_i_expected"] = what_i_expected
        if what_happened:
            context["what_happened"] = what_happened
        if include_log:
            import os
            tail, log_unavailable = _recent_log_tail_result(pid=os.getpid())
            if tail:
                context["recent_log_tail"] = tail
            elif log_unavailable:
                context["log_unavailable"] = log_unavailable
        # A hang trace captured by THIS run, attached independently of
        # include_log and scoped to our own pid.
        import os as _os
        hang = _recent_hang_traces(pid=_os.getpid())
        # extra_hang_trace carries a freeze trace found in another process.
        if extra_hang_trace:
            hang = f"{hang}\n\n{extra_hang_trace}" if hang else extra_hang_trace
        if hang:
            context["hang_traces"] = hang
        if isinstance(client, dict) and client:
            context["client"] = client
        text = build_report(summary, context=context)
        return save_report(text)


def _truncate_body(body: str) -> str:
    if len(body) <= _MAX_PREFILL_BODY:
        return body
    return body[:_MAX_PREFILL_BODY] + "\n\n... (truncated - see the saved report file)"


def mailto_url(summary: str, body: str) -> str:
    q = urllib.parse.urlencode(
        {"subject": f"localm bug: {summary}", "body": _truncate_body(body)},
        quote_via=urllib.parse.quote)
    return f"mailto:{MAINTAINER_EMAIL}?{q}"


# --------------------------------------------------------------------------- #
#  Upload channel: file the report as a GitHub issue WITHOUT a tester account  #
#                                                                              #
#  The app POSTs the user-reviewed report to a configured endpoint - a small   #
#  Cloudflare Worker that holds a fine-grained GitHub token server-side and    #
#  creates the issue. No token ships in the app, and the token can only file   #
#  issues through the rate-limited proxy. Uploading is always an explicit user #
#  action; a crash report is only saved to a file.                             #
# --------------------------------------------------------------------------- #

def upload_config() -> tuple:
    """(url, token) for the upload channel from config, or (None, None) when not
    configured. The token is an optional shared secret. Never raises."""
    try:
        from localm.config import load_config
        cfg = load_config()
        url = (cfg.get("bugreport_upload_url") or "").strip() or None
        token = (cfg.get("bugreport_upload_token") or "").strip() or None
        return url, token
    except Exception:
        return None, None


def upload_available() -> bool:
    """True when an upload endpoint is configured (the GUI uses this to decide
    whether to offer a 'Send to maintainer' button)."""
    return upload_config()[0] is not None


def _retry_after_from(headers, body_text) -> int:
    """Best-effort retry delay (seconds) for a 429: the ``Retry-After`` response
    header, else a ``retry_after`` field in the JSON body, else a 30s default."""
    val = None
    try:
        if headers is not None:
            val = headers.get("Retry-After")
    except Exception:
        # Header access is best-effort; a missing/odd header just falls through to
        # the body/default below - never let it break the (already-failed) upload.
        val = None
    if val:
        try:
            return max(1, int(str(val).strip()))
        except (TypeError, ValueError):
            pass
    if body_text:
        try:
            import json as _json
            obj = _json.loads(body_text)
            if isinstance(obj, dict) and obj.get("retry_after"):
                return max(1, int(obj["retry_after"]))
        except Exception:
            # A non-JSON or malformed body simply yields the default delay.
            pass
    return 30


def _classify_url_error(exc) -> tuple:
    """(stage, hint) diagnosing WHERE a failed upload broke, from the ACTUAL error
    only - we never contact a third-party host to test connectivity (offline-first
    + privacy). ``stage`` is offline_or_dns / tls / timeout / unreachable / unknown;
    ``hint`` is a friendly, actionable line (the caller adds the "report is saved /
    email it" part)."""
    import socket
    import ssl

    # A urllib URLError wraps the real cause in .reason (usually an OSError); unwrap
    # so isinstance checks see gaierror/SSLError/timeout, not the URLError shell.
    reason = getattr(exc, "reason", None)
    inner = reason if isinstance(reason, BaseException) else exc

    if isinstance(inner, socket.gaierror):
        return ("offline_or_dns",
                "Could not look up the bug-report server's address. You may be "
                "offline, or a DNS/network setting is blocking the connection.")
    if isinstance(inner, ssl.SSLError):
        return ("tls",
                "A secure (TLS) connection to the bug-report server could not be "
                "established.")
    if isinstance(inner, (TimeoutError, socket.timeout)):
        return ("timeout",
                "The bug-report server did not respond in time. It may be slow or "
                "temporarily unreachable.")
    if isinstance(inner, ConnectionError):
        return ("unreachable",
                "Reached the network but could not connect to the bug-report "
                "server. It may be down, or a firewall/proxy is blocking it.")
    if isinstance(inner, OSError):
        txt = str(getattr(inner, "strerror", "") or inner).lower()
        if "unreachable" in txt or "not known" in txt or "no address" in txt:
            return ("offline_or_dns",
                    "The network appears to be unavailable (could not reach the "
                    "bug-report server). Check your internet connection.")
        return ("unreachable",
                "Could not connect to the bug-report server. It may be down, or a "
                "firewall/proxy is blocking it.")
    return ("unknown",
            "The report could not be sent for an unexpected reason.")


def upload_report(title: str, body: str, *, url: Optional[str] = None,
                  token: Optional[str] = None, timeout: float = 15.0,
                  opener=None) -> dict:
    """POST a user-reviewed report to the upload endpoint and return its JSON
    response (e.g. ``{"url": "<issue url>"}``).

    Only the report text (plus an optional shared secret) is sent; the GitHub
    token lives at the proxy. Raises :class:`LocalmError` on any failure - no
    endpoint, a network error, or a non-2xx response. *opener* is injectable for
    tests (defaults to urllib)."""
    import json as _json

    # The upload boundary is the single choke point every uploaded title flows
    # through. Idempotent.
    title = _scrub_secrets(title)

    # The body's trailing edit-disclaimer is stripped here, the one choke point
    # every uploaded body flows through.
    body = _strip_report_footer(body or "")

    # url and token are each filled from config independently when not passed.
    if url is None or token is None:
        cfg_url, cfg_token = upload_config()
        if url is None:
            url = cfg_url
        if token is None:
            token = cfg_token
    if not url:
        raise LocalmError("no upload endpoint is configured",
                          reason="set bugreport_upload_url to enable the Send channel",
                          stage="no_endpoint",
                          hint="No bug-report server is configured in this build, so "
                               "the report cannot be filed automatically.")
    payload = _json.dumps(
        {"title": (title or "localm bug report")[:200], "body": body or ""}
    ).encode("utf-8")
    headers = {"Content-Type": "application/json", "User-Agent": "localm-bugreport"}
    if token:
        headers["X-Localm-Token"] = token

    if opener is None:
        import urllib.error
        import urllib.request

        from localm.http_ssl import verified_urlopen

        def opener(u, data, hdrs, to):  # noqa: E306
            req = urllib.request.Request(u, data=data, headers=hdrs, method="POST")
            try:
                with verified_urlopen(req, timeout=to) as resp:
                    return resp.status, resp.read().decode("utf-8", "replace")
            except urllib.error.HTTPError as e:
                detail = ""
                try:
                    detail = e.read().decode("utf-8", "replace")[:300]
                except Exception:
                    # Best-effort extra context; the failure is still raised below
                    # with an empty detail.
                    pass
                if e.code == 429:
                    raise RateLimitedError(
                        _retry_after_from(getattr(e, "headers", None), detail),
                        reason=detail)
                raise LocalmError(
                    "the bug-report server rejected the upload",
                    reason=f"HTTP {e.code}: {detail}".strip(),
                    stage="server_rejected",
                    hint=(f"The bug-report server received the report but rejected it "
                          f"(HTTP {e.code}). This is likely a temporary server-side "
                          f"issue, not your connection."))
            except (urllib.error.URLError, OSError) as e:
                stage, hint = _classify_url_error(e)
                raise LocalmError("could not reach the bug-report server",
                                  reason=str(getattr(e, "reason", e)),
                                  stage=stage, hint=hint)

    status, raw = opener(url, payload, headers, timeout)
    if int(status) == 429:
        raise RateLimitedError(_retry_after_from(None, raw), reason=str(raw)[:300])
    if not (200 <= int(status) < 300):
        raise LocalmError(
            "the bug-report server rejected the upload",
            reason=f"HTTP {status}: {raw[:300]}".strip(),
            stage="server_rejected",
            hint=(f"The bug-report server rejected the report (HTTP {status}). This is "
                  f"likely a temporary server-side issue, not your connection."))
    try:
        return _json.loads(raw) if raw.strip() else {}
    except ValueError:
        return {"raw": raw[:300]}


def report_failure(*, summary: str, reason: str = "",
                   error: Optional[BaseException] = None,
                   context: Optional[dict] = None,
                   interactive: bool = True,
                   assume_yes: bool = False,
                   auto_send: bool = False,
                   as_failure: bool = True,
                   open_browser=webbrowser.open,
                   prompt=None) -> Optional[Path]:
    """Say sorry (what + why), save an editable report, and offer to send it.

    Returns the saved report path (or None). ``interactive`` False (or
    ``assume_yes``) saves and points at the file without prompting or opening a
    browser. ``as_failure`` False is for a user-initiated report (``localm
    bug-report``): neutral header, no apology. ``auto_send`` True uploads
    immediately via the account-less proxy channel, with no menu and no browser.
    ``open_browser`` and ``prompt`` are injectable for tests."""
    console.print()
    if as_failure:
        console.print(f"[bold red]Sorry - {summary}.[/bold red]")
        if reason:
            console.print(f"[red]Reason:[/red] {reason}")
    else:
        console.print(f"[bold]Filing a bug report:[/bold] {summary}")
        if reason:
            console.print(f"[dim]{reason}[/dim]")

    text = build_report(summary, reason=reason, error=error, context=context)
    path = save_report(text)
    if path is not None:
        console.print(f"[dim]A bug report was saved (edit it before sending):[/dim] {path}")
    else:
        console.print("[yellow]Could not save a report file; you can still copy the "
                      "details above.[/yellow]")

    offer_to_send(summary, path, text, interactive=interactive,
                   assume_yes=assume_yes, auto_send=auto_send,
                   open_browser=open_browser, prompt=prompt)
    return path


def offer_to_send(summary: str, path: Optional[Path], text: str, *,
                   interactive: bool = True, assume_yes: bool = False,
                   auto_send: bool = False,
                   open_browser=webbrowser.open, prompt=None) -> None:
    """Offer to send an ALREADY-BUILT, already-saved report (upload / email /
    self), or send it immediately with ``auto_send``.

    The one send flow shared by report_failure (automatic crash/LocalmError
    reports) and the ``localm bug-report`` CLI (user-composed reports). *text*
    is the in-memory report body, used when *path* is None because the save
    failed; when a file exists, the sent body is RE-READ from it, so a user's
    edits made before picking a channel are what gets sent."""
    up_url, up_token = upload_config()
    can_upload = up_url is not None

    if auto_send:
        body = path.read_text(encoding="utf-8") if path is not None else text
        where = str(path) if path is not None else "the text above"
        if not can_upload:
            console.print("[yellow]No hosted send channel is configured - the report is "
                          f"saved at {where}; email it to {MAINTAINER_EMAIL} instead.[/yellow]")
            return
        try:
            res = upload_report(summary, body, url=up_url, token=up_token)
        except RateLimitedError as e:
            import time as _time
            console.print(f"[yellow]Rate limited. Retrying in {e.retry_after}s...[/yellow]")
            _time.sleep(e.retry_after)
            try:
                res = upload_report(summary, body, url=up_url, token=up_token)
            except LocalmError as e2:
                console.print(f"[yellow]Still could not send it.[/yellow] "
                              f"{e2.hint or e2.reason}")
                console.print(f"[dim]The report is at {where} - email it to "
                              f"{MAINTAINER_EMAIL} instead.[/dim]")
                return
        except LocalmError as e:
            console.print(f"[yellow]Could not send it.[/yellow] {e.hint or e.reason}")
            console.print(f"[dim]The report is at {where} - email it to "
                          f"{MAINTAINER_EMAIL} instead.[/dim]")
            return
        link = res.get("url") if isinstance(res, dict) else None
        console.print("[green]Sent to the maintainer.[/green]"
                      + (f" Tracking issue: {link}" if link else ""))
        return

    if not interactive or assume_yes:
        if can_upload:
            console.print(
                "[dim]Run[/dim] [bold]localm bug-report --send[/bold] [dim]to send it now "
                "(no GitHub account needed) - or email/Discord it yourself.[/dim]")
        else:
            console.print(f"[dim]Send it to the maintainer ({MAINTAINER_EMAIL}) by email or "
                          "Discord.[/dim]")
        return

    # Re-read the saved file so the user's edits are what actually gets sent.
    body = text
    if path is not None:
        try:
            body = path.read_text(encoding="utf-8")
        except OSError:
            body = text

    console.print("How would you like to send it (edit the file first if you want)?")
    # Displayed number -> action. Email is [2] and self [3] regardless of
    # whether the upload option is present.
    actions = {}
    if can_upload:
        console.print("  [1] Send to the maintainer now  "
                      "[dim](uploads the report - no GitHub account needed)[/dim]")
        actions["1"] = "upload"
    console.print("  [2] Email the maintainer  [dim](opens your mail app, works anywhere)[/dim]")
    console.print(f"  [3] I'll send it myself   [dim](Discord / email to {MAINTAINER_EMAIL})[/dim]")
    console.print("  [Enter] not now")
    actions.update({"2": "email", "3": "self"})

    ask = prompt
    if ask is None:
        import click
        def ask(text_):  # noqa: E306
            return click.prompt(text_, default="", show_default=False)
    choice = (ask("  Pick a number") or "").strip()
    action = actions.get(choice, "none")

    # With path None the save failed, so the messages name the in-memory text
    # rather than a file.
    where = (str(path) if path is not None
             else "the text above (it could not be saved to a file)")

    try:
        if action == "upload":
            attempt = 0
            while True:
                attempt += 1
                try:
                    res = upload_report(summary, body, url=up_url, token=up_token)
                    link = res.get("url") if isinstance(res, dict) else None
                    console.print("[green]Sent to the maintainer.[/green]"
                                  + (f" Tracking issue: {link}" if link else ""))
                    break
                except RateLimitedError as e:
                    # Wait the server-advised delay and retry once.
                    import time as _time
                    msg = e.hint or "The bug-report server is rate limiting."
                    console.print(f"[yellow]{msg} Retrying in {e.retry_after}s...[/yellow]")
                    _time.sleep(e.retry_after)
                    if attempt >= 2:
                        console.print(f"[yellow]Still rate limited.[/yellow] The report "
                                      f"is at {where} - email it to {MAINTAINER_EMAIL}.")
                        break
                    continue
                except LocalmError as e:
                    # Report where the send failed, keep the file, and offer a
                    # retry.
                    console.print(f"[yellow]Could not send it.[/yellow] {e.hint or e.reason}")
                    console.print(f"[dim]The report is saved at {where}.[/dim]")
                    if attempt >= 3:
                        console.print(f"[dim]Email it to {MAINTAINER_EMAIL} when you can.[/dim]")
                        break
                    again = (ask("  Retry sending now? [y/N]") or "").strip().lower()
                    if again in ("y", "yes"):
                        continue
                    console.print(f"[dim]Not retried - email {where} to "
                                  f"{MAINTAINER_EMAIL} when you can.[/dim]")
                    break
        elif action == "email":
            open_browser(mailto_url(summary, body))
            console.print(f"[green]Opened your mail app to {MAINTAINER_EMAIL}.[/green]")
        elif action == "self":
            console.print(f"[dim]Thanks. Send {where} to {MAINTAINER_EMAIL} or on Discord "
                          "when you can.[/dim]")
        else:
            console.print("[dim]No report sent. It is saved if you change your mind.[/dim]")
    except Exception:
        console.print("[yellow]Could not open that automatically - the report is at "
                      f"{where}.[/yellow]")


# --------------------------------------------------------------------------- #
#  Process-wide net: catch a bug ANYWHERE, not just in a CLI command           #
#                                                                              #
#  These hooks route every Python-level failure - a crash in a background       #
#  thread as well as an uncaught main-thread exception - through the same      #
#  "sorry X for Y" plus report path.                                           #
#                                                                              #
#  Limit: this catches PYTHON exceptions. A native crash inside llama.dll, an  #
#  OS OOM-kill, or os._exit cannot be caught in-process.                       #
# --------------------------------------------------------------------------- #

_handlers_installed = False


def _handle_main_exception(exc_type, exc, tb) -> None:
    """sys.excepthook: last-resort net for an uncaught main-thread exception.
    Ctrl+C stays quiet; everything else becomes a friendly report. Fully guarded:
    if reporting itself fails, defer to the interpreter's default hook."""
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc, tb)
        return
    try:
        interactive = bool(getattr(sys.stdin, "isatty", lambda: False)())
        report_failure(
            summary=getattr(exc, "summary", None) or "localm hit an unexpected error",
            reason=getattr(exc, "reason", None) or str(exc),
            error=exc, context=getattr(exc, "context", None) or {},
            interactive=interactive)
    except Exception:
        sys.__excepthook__(exc_type, exc, tb)


def _handle_thread_exception(args) -> None:
    """threading.excepthook: log a background-thread crash and save a report.
    Never prompts, and never takes the app down."""
    exc = getattr(args, "exc_value", None)
    if exc is None or isinstance(exc, SystemExit):
        return
    try:
        tname = getattr(getattr(args, "thread", None), "name", "?")
        report_failure(
            summary=f"a background task crashed (thread '{tname}')",
            reason=str(exc), error=exc, context={"thread": tname},
            interactive=False)
    except Exception:
        try:
            threading.__excepthook__(args)
        except Exception:
            # The bug reporter and the stdlib default hook both failed; an
            # excepthook must not raise.
            pass


def install_global_handlers(force: bool = False) -> bool:
    """Install the process-wide graceful-failure net (main thread + background
    threads). Idempotent. A no-op under pytest unless *force* (so the test runner
    keeps its own exception/thread handling). Returns True if it installed."""
    global _handlers_installed
    if _handlers_installed:
        return False
    if not force and "pytest" in sys.modules:
        return False
    sys.excepthook = _handle_main_exception
    threading.excepthook = _handle_thread_exception
    _handlers_installed = True
    return True


# --------------------------------------------------------------------------- #
#  asyncio + native-crash net                                                  #
#                                                                              #
#  Two failure modes the excepthooks above do not cover: an uncaught exception #
#  inside an asyncio task, which only logs "Task exception was never           #
#  retrieved"; and a native crash, an OS kill or a force-closed console        #
#  window, which cannot be caught in-process at all. The first is closed with  #
#  an asyncio exception handler, the second with a crash marker: the server    #
#  arms one on start and disarms it on a clean shutdown, so a marker still     #
#  present on the next start means the previous run died hard.                 #
# --------------------------------------------------------------------------- #

_crash_trace_fh = None   # kept alive so faulthandler can write to it


def install_asyncio_handler(loop) -> bool:
    """Route an uncaught asyncio task/loop exception through the bug reporter
    (saved, never prompted). Returns True if installed. Non-exception loop
    messages fall through to the default handler."""
    import asyncio
    try:
        def _h(loop, ctx):
            exc = ctx.get("exception")
            if isinstance(exc, (KeyboardInterrupt, SystemExit,
                                asyncio.CancelledError)):
                return   # normal control flow, not a crash
            if exc is None:
                loop.default_exception_handler(ctx)   # message-only: keep default
                return
            try:
                report_failure(
                    summary="an async task crashed",
                    reason=ctx.get("message") or str(exc),
                    error=exc, context={"asyncio": ctx.get("message", "")},
                    interactive=False)
            except Exception:
                loop.default_exception_handler(ctx)
        loop.set_exception_handler(_h)
        return True
    except Exception:
        return False


def _crash_dir(home=None):
    from pathlib import Path
    if home is None:
        from localm.config import HOME_DIR
        home = HOME_DIR
    d = Path(home) / "run"
    d.mkdir(parents=True, exist_ok=True)
    return d


# The marker and its companion native-fault-trace file are scoped per
# instance_id, the same per-process identity instances.py's registry uses, so
# more than one localm server can run against the same LOCALM_HOME.


def _crash_marker_path(d, instance_id: Optional[str]):
    if instance_id:
        return d / f"server-crash.{instance_id}.marker"
    # No instance identity available: fall back to the unscoped shared name.
    return d / "server-crash.marker"


def _crash_trace_path(d, instance_id: Optional[str]):
    if instance_id:
        return d / f"server-crash-trace.{instance_id}.txt"
    return d / "server-crash-trace.txt"


def _trace_path_for_marker(d, marker):
    """The native-fault-trace file that belongs WITH *marker* (same instance),
    derived from the marker's own filename."""
    name = marker.name
    prefix, suffix = "server-crash.", ".marker"
    if name.startswith(prefix) and name.endswith(suffix) and name != "server-crash.marker":
        return d / f"server-crash-trace.{name[len(prefix):-len(suffix)]}.txt"
    return d / "server-crash-trace.txt"


def _all_crash_markers(d):
    """Every armed marker under *d*: one per instance that has ever armed
    against this LOCALM_HOME (plus the legacy unscoped name, if present)."""
    markers = list(d.glob("server-crash.*.marker"))
    legacy = d / "server-crash.marker"
    if legacy.exists():
        markers.append(legacy)
    return markers


def arm_crash_guard(context: Optional[dict] = None, home=None,
                    instance_id: Optional[str] = None) -> bool:
    """Mark that a server run is in progress and enable faulthandler so a native
    fault leaves a trace. If the process dies hard the marker survives;
    check_and_report_prior_crash() reports it on the next start. *instance_id*
    (``app.state.instance_id``, set by instances.advertise() before this is
    called) scopes the marker to THIS running instance, so a sibling instance
    sharing the same LOCALM_HOME is never mistaken for a crash. Returns True if
    armed. Never raises into the caller."""
    global _crash_trace_fh
    import faulthandler
    import json
    import os

    from localm.debuglog import logger
    try:
        d = _crash_dir(home)
        _crash_trace_fh = open(_crash_trace_path(d, instance_id), "w", encoding="utf-8")
        try:
            faulthandler.enable(file=_crash_trace_fh, all_threads=True)
            if not faulthandler.is_enabled():
                # enable() can return without raising yet still not be armed;
                # is_enabled() is the call that reports the truth.
                logger.warning(
                    "bugreport: faulthandler.enable() returned without raising "
                    "but is_enabled() is False - a native crash will produce no "
                    "trace this run")
        except Exception as e:
            # Arming must not fail the start: the crash marker below is still
            # written, so a hard death is still reported, without a trace.
            logger.warning(
                "bugreport: faulthandler could not attach (%s: %s) - a native "
                "crash this run will produce no trace", type(e).__name__, e)
        _crash_marker_path(d, instance_id).write_text(
            json.dumps({"pid": os.getpid(), "context": context or {}}),
            encoding="utf-8")
        return True
    except Exception:
        return False


def disarm_crash_guard(home=None, instance_id: Optional[str] = None) -> None:
    """Clean shutdown: drop THIS instance's own marker (never a sibling's) so
    the next start does not report a crash. *instance_id* must be the SAME id
    passed to the matching arm_crash_guard() call."""
    global _crash_trace_fh
    import faulthandler
    try:
        d = _crash_dir(home)
        _crash_marker_path(d, instance_id).unlink(missing_ok=True)
    except Exception:
        # Best-effort: a surviving marker files one spurious "prior crash"
        # report on the next start. disarm must not raise during shutdown.
        pass
    try:
        if _crash_trace_fh is not None:
            faulthandler.disable()
            _crash_trace_fh.close()
            _crash_trace_fh = None
    except Exception:
        # Best-effort: a failure leaks a file handle until process exit.
        pass


# A native/ggml status line printed via raw fprintf, i.e. with no
# "TIMESTAMP LEVEL NAME:" prefix.
_NATIVE_OP_LINE_RE = re.compile(
    r'^(llama_|ggml_|graph_reserve|sched_reserve|load_tensors|load_all_data|create_tensor)')

# How much of the raw log tail the truncation check below reads.
_TRUNCATION_CHECK_READ_BYTES = 4000


def _raw_tail_truncation_signal(home=None, pid=None) -> "tuple[bool, str]":
    """(truncated, last_line): whether the crashed run's OWN raw log file (the
    file _find_run_log resolves) ends WITHOUT a trailing newline, and what that
    final (possibly mid-word) line is. A clean shutdown's last logged line
    always ends with a newline. Never raises; returns (False, "") on any failure
    or when there is nothing to check."""
    try:
        chosen = _find_run_log(home, pid)
        if chosen is None:
            return False, ""
        with open(chosen, "rb") as fh:
            fh.seek(0, 2)
            size = fh.tell()
            fh.seek(max(0, size - _TRUNCATION_CHECK_READ_BYTES))
            raw = fh.read().decode("utf-8", errors="replace")
        if not raw:
            return False, ""
        truncated = not raw.endswith(("\n", "\r"))
        last_line = raw.replace("\r\n", "\n").rstrip("\n").rsplit("\n", 1)[-1]
        return truncated, last_line
    except Exception:
        return False, ""


def _classify_prior_death(*, native_trace: str, hang_trace: str,
                          raw_tail_truncated: bool,
                          raw_tail_last_line: str) -> "tuple[str, str]":
    """(summary, reason) for report_failure(), classified from the evidence
    actually collected. Pure function, no I/O.

    Ordered by how direct the evidence is: a captured native trace, then an
    inferred mid-operation cutoff, then a captured hang. When none of those
    fired the result names the remaining ambiguity (an OS kill or a
    force-closed window leaves no trace at all)."""
    if native_trace.strip():
        first_line = next(
            (ln.strip() for ln in native_trace.strip().splitlines() if ln.strip()), "")
        return (
            f"localm server crashed - native fault captured: {first_line}",
            "a native crash was caught by the fault handler; see the captured "
            "trace below for the exact fault and thread/frame."
        )
    if raw_tail_truncated and _NATIVE_OP_LINE_RE.match(raw_tail_last_line.strip()):
        return (
            "localm server crashed during model load/construction "
            "(native crash suspected, no trace captured)",
            f'the previous run\'s log stops abruptly mid-line inside '
            f'"{raw_tail_last_line.strip()}" - no faulthandler trace was '
            f'captured for this crash (a known open gap - see this report\'s '
            f'"Native fault trace" section, or its absence), but a log cut off '
            f'mid-operation during native model construction is the signature '
            f'of a hard native crash, not a clean stop.'
        )
    if hang_trace.strip():
        return (
            "localm server appeared frozen (unresponsive) before this run ended",
            "the always-on hang watchdog captured a stall before the process "
            "stopped - it was most likely force-closed after becoming "
            "unresponsive, not a native crash. See the captured stacks below."
        )
    return (
        "localm server crashed (recovered on the next start)",
        "the previous server run ended without a clean shutdown, and none of "
        "a native trace, a mid-operation log cutoff, or a captured hang were "
        "found in the evidence collected - most likely an OS kill or a "
        "force-closed window (both legitimately leave no trace)."
    )


def _report_one_crash_marker(d, marker, home, interactive: bool):
    """Report *marker* as a crash IF its recorded pid is no longer alive, then
    clear it. Returns the report path, or None if this marker was skipped (a
    live sibling instance) or nothing could be filed. Never raises."""
    import json
    from localm.instances import pid_alive
    try:
        if not marker.exists():
            return None
        info = {}
        try:
            info = json.loads(marker.read_text(encoding="utf-8"))
        except Exception:
            # A corrupt or half-written marker still means a crash happened:
            # report it with an empty context.
            pass
        pid = info.get("pid")
        try:
            if pid_alive(int(pid)):
                # The recorded pid is still running: a sibling instance that is
                # still up, not a crash. Its marker is left alone.
                return None
        except (TypeError, ValueError):
            # No or unparseable pid recorded: liveness cannot be confirmed, so
            # the crash is reported.
            pass
        trace = ""
        tp = _trace_path_for_marker(d, marker)
        try:
            if tp.exists():
                trace = tp.read_text(encoding="utf-8").strip()
        except Exception:
            # Best-effort: an unreadable trace file is reported without it.
            pass
        # Clear the marker before reporting.
        try:
            marker.unlink(missing_ok=True)
        except Exception:
            # A marker that cannot be removed makes the next start re-report
            # this same crash.
            pass
        # Delete the trace with its marker, its content having been folded into
        # ctx below. Nothing else ever removes a
        # server-crash-trace.<instance_id>.txt. Best-effort.
        try:
            tp.unlink(missing_ok=True)
        except Exception:
            pass
        ctx = {"prior_run": info}
        if trace:
            ctx["native_trace"] = trace[:4000]
        # The crashed run's own log tail, matched by pid.
        tail, log_unavailable = _recent_log_tail_result(home, pid=info.get("pid"))
        if tail:
            ctx["recent_log_tail"] = tail
        elif log_unavailable:
            # Record why the log is missing.
            ctx["log_unavailable"] = log_unavailable
        # The CRASHED run's freeze stacks, matched by its pid like the log tail
        # above.
        hang = _recent_hang_traces(home, pid=info.get("pid"))
        if hang:
            ctx["hang_traces"] = hang
        # Classify the death from the evidence actually collected.
        raw_truncated, raw_last_line = _raw_tail_truncation_signal(
            home, pid=info.get("pid"))
        summary, reason = _classify_prior_death(
            native_trace=trace, hang_trace=hang,
            raw_tail_truncated=raw_truncated, raw_tail_last_line=raw_last_line)
        return report_failure(
            summary=summary, reason=reason,
            error=None, context=ctx, interactive=interactive)
    except Exception:
        return None


def check_and_report_prior_crash(home=None, interactive: bool = False):
    """Scan every crash marker left under this LOCALM_HOME's run/ dir (one per
    instance that has ever armed here) and report+clear any whose recorded pid
    is no longer alive - a hard crash: a native fault, an OS kill, or a
    force-closed window. A marker whose pid IS still alive is a sibling
    instance still running, and is left untouched: not reported, not deleted.
    Returns the last report path filed, or None if nothing was reported. Never
    raises into the caller."""
    try:
        d = _crash_dir(home)
        markers = _all_crash_markers(d)
    except Exception:
        return None
    filed = None
    for marker in markers:
        result = _report_one_crash_marker(d, marker, home, interactive)
        if result is not None:
            filed = result
    return filed
