# SPDX-License-Identifier: AGPL-3.0-or-later
"""Graceful failure + an autogenerated, user-editable bug report.

When something goes wrong, localm should fail like a good citizen: say *what*
broke and *why* in plain language, then offer to send a prefilled report the
user can read and edit before anything leaves their machine.

Channels, in the order that actually works for a tester:
  * **email** - opens the user's mail app prefilled to the maintainer. Works for
    anyone, including a tester on a still-private repo.
  * **GitHub issue** - opens a prefilled new-issue page. Best once the repo is
    public (or the tester is a collaborator); noted as such.
  * **do it yourself** - the report is always saved to a file, so the user can
    drop it on Discord, paste it, or attach it however they like.

The maintainer's contact email is intentionally published here for bug reports
(the maintainer opted in); see scripts/check_hygiene.py.

Diagnostics aim to be *actually useful* - the data a maintainer needs to act on a
report - while staying safe:
  * OS / arch / Python, GPU vendor + NVIDIA driver / CUDA capability, the chosen
    and recommended backend, and the *names* of provisioned native libraries.
  * App state: the loaded model, effective backend, context ceiling, session
    (privacy) mode, debug flag, and enabled plugins.
  * An ALLOWLISTED, scrubbed subset of config (context sizing, ports, media URLs,
    privacy mode) - never the whole config, so a future secret-bearing key cannot
    leak; path values are home-scrubbed and URL values credential-scrubbed.
  * Versions of the dependencies that shape a failure (native runtime, HF + server
    stacks).
  * The in-memory recent-activity log (INFO+ breadcrumbs; the raw model output is
    DEBUG-level, so chat content never enters it) and, for a GUI report, the
    browser context + recent JS console errors.

What is NEVER collected: the API key, environment variables (which can hold one),
config secrets, the raw chat/transcript content, or anything written only at DEBUG
level. The user also reviews and edits the report before sending, regardless.
"""

from __future__ import annotations

import platform
import re
import sys
import threading
import traceback
import urllib.parse
import webbrowser
from pathlib import Path
from typing import Optional

from rich.console import Console

console = Console(highlight=False)

# Intentionally published maintainer contact for bug reports (hygiene-ok).
MAINTAINER_EMAIL = "theilige@gmail.com"
REPO_SLUG = "Matlan1/localm"
ISSUES_NEW_URL = f"https://github.com/{REPO_SLUG}/issues/new"

# mailto/issue bodies cannot be arbitrarily long (mail clients and some browsers
# truncate very long query strings), so the prefilled body is a short pointer and
# the full detail lives in the saved file the user attaches or pastes.
_MAX_PREFILL_BODY = 1500


class LocalmError(Exception):
    """A user-facing, reportable failure.

    Raise this (not a bare Exception) when a command hits a known, describable
    problem. The CLI's single graceful handler turns it into a "sorry, X went
    wrong because Y" message and offers a bug report - the command that raises it
    knows nothing about reporting. Carries a human *summary*, an optional
    *reason*, and diagnostic *context* for the report."""

    def __init__(self, summary: str, reason: str = "",
                 context: Optional[dict] = None):
        super().__init__(summary)
        self.summary = summary
        self.reason = reason
        self.context = context or {}


def _localm_version() -> str:
    try:
        from importlib.metadata import version
        return version("localm")
    except Exception:
        return "unknown"


def _runtime_libs() -> tuple:
    """(binary_dir or None, sorted list of native library file NAMES present).
    Names only - never full paths beyond the resolved dir, never contents."""
    try:
        from localm.inference.backends.llamacpp._loader import (
            lib_filename, runtime_binary_dir)
        d = runtime_binary_dir()
        if d is None:
            return None, []
        # Load-bearing shared libraries only - the bundled llama-*.exe tools are
        # noise in a report (dozens of them) and not relevant to a load failure.
        names = sorted(
            f.name for f in Path(d).iterdir()
            if f.is_file() and (f.suffix.lower() in (".dll", ".so", ".dylib")
                                or ".so." in f.name)
        )
        return d, names, lib_filename()
    except Exception:
        return None, [], ""


def collect_diagnostics(context: Optional[dict] = None) -> dict:
    """Gather a safe, useful environment snapshot. Never raises."""
    context = dict(context or {})
    diag: dict = {}
    try:
        diag["localm_version"] = _localm_version()
        diag["python"] = sys.version.split()[0]
        diag["platform"] = platform.platform()
        diag["machine"] = platform.machine()
    except Exception:
        pass

    try:
        from localm import hwdetect
        det = hwdetect.detect()
        diag["gpu_vendors"] = det.vendors or []
        diag["recommended_backend"] = det.recommended
        diag["detect_source"] = det.source
    except Exception:
        diag["gpu_vendors"] = []

    # NVIDIA driver / CUDA capability, when an NVIDIA GPU is involved.
    try:
        from localm.setup_llama import nvidia_preflight
        if "nvidia" in diag.get("gpu_vendors", []) or context.get("backend") == "cuda":
            nv = nvidia_preflight()
            if nv.present:
                diag["nvidia_gpu"] = nv.gpu_name
                diag["nvidia_driver"] = nv.driver_version
                diag["nvidia_cuda_capability"] = nv.cuda_capability
    except Exception:
        pass

    try:
        res = _runtime_libs()
        binary_dir = res[0]
        names = res[1]
        diag["native_runtime_provisioned"] = binary_dir is not None
        diag["native_libs"] = names
    except Exception:
        pass

    # Caller-supplied context (chosen backend, the operation, etc.).
    for k in ("operation", "backend", "requested_backend", "with_cudart"):
        if k in context:
            diag[k] = context[k]

    # App / runtime state - the "what was the app actually doing" half of a useful
    # report. Each collector is independently guarded and returns empty on failure,
    # so a missing piece never costs the rest of the report.
    diag["loaded_model"] = _loaded_model_info()
    diag.update(_runtime_state())          # session_mode, debug_mode
    diag["enabled_plugins"] = _enabled_plugins()
    diag["config_subset"] = _safe_config_subset()
    diag["dependencies"] = _dependency_versions()
    return diag


def _scrub_home(text: str) -> str:
    """Drop the home directory (which contains the username) from any paths so a
    tester's report does not leak their account name; the file/line structure that
    matters for debugging is kept. Guard ONLY the home lookup: if Path.home() raises
    or is empty we must NOT ship the raw text as if scrubbed (privacy fail), so fail
    safe and strip the username with a fallback regex over common home-path roots."""
    if not text:
        return text
    home = ""
    try:
        home = str(Path.home())
    except Exception:
        home = ""
    if home:
        return text.replace(home, "~")  # cannot fail once home is a non-empty string
    # Home lookup failed: redact the username segment in known home roots so the
    # account name still does not leak (e.g. C:\Users\<name>, /home/<name>).
    return re.sub(r"([Cc]:\\Users\\|/home/|/Users/)[^\\/\r\n]+", r"\1<redacted>", text)


def _scrub_url_creds(text: str) -> str:
    """Strip ``user:pass@`` credentials from any URL-ish value before it goes in a
    report (a SearXNG / ComfyUI / reviewer URL can carry an inline secret)."""
    if not text:
        return text
    return re.sub(r"(://)[^/@\s]+@", r"\1<redacted>@", text)


# Config keys SAFE to echo into a report and useful for debugging a setup. An
# allowlist (never the whole config) so a future secret-bearing key cannot be
# auto-leaked; path-like values are home-scrubbed and URL-like values
# credential-scrubbed before they are rendered. The API key lives in auth.key,
# never config.json - we stay conservative regardless.
_SAFE_CONFIG_KEYS = (
    "binary_dir", "n_ctx", "n_ctx_max", "ctx_auto", "n_gpu_layers", "max_tokens",
    "model_swap_policy", "idle_unload_seconds", "reload_llm_after_imagine",
    "port", "require_auth", "cors_origins", "mode", "chat_mode", "coder_mode",
    "net_mode", "comfy_launch_cmd", "comfy_workdir", "comfy_api_url",
    "net_search_url", "coder_reviewer", "coder_review", "voice_stt_model",
)

# Distributions whose versions actually shape a localm failure. Optional / absent
# packages are simply skipped, so this stays correct across install profiles.
_REPORTED_DISTS = (
    "localm", "localm-llama-runtime", "llama-cpp-python", "torch", "transformers",
    "huggingface-hub", "fastapi", "uvicorn", "ctranslate2", "faster-whisper",
)


def _loaded_model_info() -> dict:
    """Snapshot of the in-process inference engine (model, backend, loaded?, ctx).

    Empty when no server engine is loaded in THIS process (e.g. a CLI
    ``bug-report``) or it cannot be read. Never raises."""
    try:
        from localm.inference import http_server as hs
        eng = getattr(hs, "_engine", None)
        if eng is None:
            return {}
        info: dict = {
            "model": getattr(eng, "display_name", "") or "(unnamed)",
            "loaded": bool(getattr(eng, "loaded", False)),
        }
        backend = getattr(eng, "_backend", None)
        if backend is not None:
            info["backend"] = type(backend).__name__
        ctx = getattr(eng, "effective_ctx_max", None)
        if ctx:
            info["effective_ctx_max"] = ctx
        return info
    except Exception:
        return {}


def _runtime_state() -> dict:
    """Session mode + debug flag. These explain WHY a report may carry little
    history (privacy mode writes nothing; a non-debug run keeps no log file), so
    they are diagnostic in their own right. Never raises."""
    state: dict = {}
    try:
        from localm.audit import effective_mode
        state["session_mode"] = effective_mode("server").value
    except Exception:
        pass
    try:
        from localm.debuglog import debug_enabled
        state["debug_mode"] = bool(debug_enabled())
    except Exception:
        pass
    return state


def _enabled_plugins() -> list:
    """Names of enabled engine plugins, from config. Never raises."""
    try:
        from localm.config import load_config
        pl = load_config().get("plugins_enabled", [])
        return [str(p) for p in pl] if isinstance(pl, list) else []
    except Exception:
        return []


def _safe_config_subset() -> dict:
    """An allowlisted, scrubbed slice of the user config: enough to debug a setup
    problem (context sizing, ports, media URLs, privacy mode) without any secret.
    Never raises."""
    try:
        from localm.config import load_config
        cfg = load_config()
    except Exception:
        return {}
    out: dict = {}
    for key in _SAFE_CONFIG_KEYS:
        if key not in cfg:
            continue
        val = cfg[key]
        if isinstance(val, str) and val:
            val = _scrub_url_creds(_scrub_home(val))
        out[key] = val
    return out


def _dependency_versions() -> dict:
    """Versions of the packages that shape a localm failure (native runtime, HF
    stack, server stack). Absent packages are omitted. Never raises."""
    out: dict = {}
    try:
        from importlib.metadata import PackageNotFoundError, version
    except Exception:
        return out
    for dist in _REPORTED_DISTS:
        try:
            out[dist] = version(dist)
        except PackageNotFoundError:
            continue
        except Exception:
            continue
    return out


def _format_error(error: Optional[BaseException]) -> str:
    if error is None:
        return ""
    tb = "".join(traceback.format_exception(type(error), error, error.__traceback__))
    tb = _scrub_home(tb)
    # Keep the tail - the last frames are the useful ones, and a shorter report
    # is more likely to be read and sent.
    lines = tb.strip().splitlines()
    if len(lines) > 25:
        lines = ["... (earlier frames trimmed) ..."] + lines[-24:]
    return "\n".join(lines)


def _recent_log_tail(home=None, pid=None, max_lines: int = 120,
                     max_chars: int = 4000) -> str:
    """Tail of the crashed run's OWN log, matched by the pid embedded in the log
    filename (localm_<date>_<time>_<pid>.log). This gives a recovered-crash report
    the activity leading up to the death even when no native trace was captured -
    a window-close or OS-kill does not trigger faulthandler, so the trace file is
    empty (BUG-1). Home paths are scrubbed. Never raises."""
    try:
        from pathlib import Path as _P
        if home is None:
            from localm.debuglog import logs_dir
            d = logs_dir()
        else:
            d = _P(home) / "logs"
        if not d.is_dir():
            return ""
        logs = sorted(d.glob("*.log"), key=lambda p: p.stat().st_mtime, reverse=True)
        chosen = None
        if pid is not None:
            for p in logs:
                if p.stem.endswith(f"_{pid}"):
                    chosen = p
                    break
        if chosen is None:
            # No pid match (older marker): fall back to the most recent log that is
            # NOT this current run's, so we do not just echo the recovering start.
            import os as _os
            cur = f"_{_os.getpid()}.log"
            chosen = next((p for p in logs if not p.name.endswith(cur)), None)
        if chosen is None:
            return ""
        lines = chosen.read_text(encoding="utf-8", errors="replace").splitlines()
        return _scrub_home("\n".join(lines[-max_lines:]).strip())[-max_chars:]
    except Exception:
        return ""


def _kv_lines(d: dict) -> list:
    """Render a flat dict as ``- key: value`` markdown lines (stable order)."""
    lines = []
    for k, v in d.items():
        if isinstance(v, list):
            v = ", ".join(str(x) for x in v) if v else "(none)"
        elif isinstance(v, bool):
            v = "yes" if v else "no"
        lines.append(f"- {k}: {v}")
    return lines


def _app_state_lines(diag: dict) -> list:
    """The "what the app was doing" half of the report: loaded model, effective
    backend, session mode, debug state, and enabled plugins."""
    lines = []
    lm = diag.get("loaded_model") or {}
    if lm:
        loaded = "loaded" if lm.get("loaded") else "NOT loaded"
        line = f"- Model: {lm.get('model', '(unnamed)')} ({loaded})"
        if lm.get("backend"):
            line += f", backend {lm['backend']}"
        if lm.get("effective_ctx_max"):
            line += f", ctx<={lm['effective_ctx_max']}"
        lines.append(line)
    else:
        lines.append("- Model: (no engine loaded in this process)")
    if "session_mode" in diag:
        lines.append(f"- Session mode: {diag['session_mode']}")
    if "debug_mode" in diag:
        lines.append(f"- Debug logging: {'on' if diag['debug_mode'] else 'off'}")
    plugins = diag.get("enabled_plugins")
    if plugins is not None:
        lines.append(f"- Enabled plugins: {', '.join(plugins) if plugins else '(none)'}")
    return lines


def build_report(summary: str, reason: str = "",
                 error: Optional[BaseException] = None,
                 context: Optional[dict] = None) -> str:
    """Render an editable markdown bug report. The user owns it before sending."""
    diag = collect_diagnostics(context)
    err = _format_error(error)

    env_lines = []
    label = {
        "localm_version": "localm", "python": "Python", "platform": "OS",
        "machine": "Arch", "gpu_vendors": "GPU vendor(s)",
        "recommended_backend": "Recommended backend", "detect_source": "Detected via",
        "nvidia_gpu": "NVIDIA GPU", "nvidia_driver": "NVIDIA driver",
        "nvidia_cuda_capability": "Driver CUDA capability",
        "native_runtime_provisioned": "Native runtime provisioned",
        "native_libs": "Native libraries", "operation": "Operation",
        "backend": "Backend (effective)", "requested_backend": "Backend (requested)",
        "with_cudart": "Fetched CUDA runtime bundle",
    }
    for key, name in label.items():
        if key in diag:
            val = diag[key]
            if isinstance(val, list):
                val = ", ".join(str(x) for x in val) if val else "(none)"
            env_lines.append(f"- {name}: {val}")

    parts = [
        f"# localm bug report: {summary}",
        "",
        "## What I was doing",
        "<!-- Please describe what you ran and what you expected. -->",
        "",
        "## What happened",
        summary + ((f"\n\nReason: {reason}") if reason else ""),
        "",
        "## App state",
        "\n".join(_app_state_lines(diag)),
        "",
        "## Environment",
        "\n".join(env_lines) if env_lines else "(could not collect environment)",
    ]

    config_subset = diag.get("config_subset") or {}
    if config_subset:
        parts += ["", "## Configuration (safe subset)", "\n".join(_kv_lines(config_subset))]
    deps = diag.get("dependencies") or {}
    if deps:
        parts += ["", "## Dependencies", "\n".join(_kv_lines(deps))]

    if err:
        parts += ["", "## Error detail", "```", err, "```"]
    # Crash diagnostics passed via context (e.g. recovered-crash reports, which have
    # no Python error object). Without these the report is contentless (BUG-1): a
    # faulthandler native trace when one was captured, and the crashed run's own log
    # tail (the actionable bit when a window-close/OS-kill left no trace). Both are
    # already home-scrubbed at their source.
    ctx = context or {}
    native = ctx.get("native_trace")
    if native:
        parts += ["", "## Native fault trace", "```", _scrub_home(str(native))[:4000], "```"]
    tail = ctx.get("recent_log_tail")
    if tail:
        parts += ["", "## Recent log (tail)", "```", _scrub_home(str(tail))[:4000], "```"]

    # Always-on in-memory breadcrumbs (INFO+; no chat content) so even a non-debug
    # report shows what the app was doing right before the problem.
    ring = _ring_activity()
    if ring:
        parts += ["", "## Recent activity (in-memory log)", "```",
                  _scrub_home("\n".join(ring[-80:]))[-4000:], "```"]

    # Browser/client context for a GUI-filed report (user agent, page, viewport,
    # and recent JS console errors). Already a plain dict from the GUI; scrubbed
    # for home paths defensively.
    client = ctx.get("client")
    if isinstance(client, dict) and client:
        parts += ["", "## Browser / client"] + _client_lines(client)

    parts += [
        "",
        "---",
        f"Sent to the localm maintainer ({MAINTAINER_EMAIL}). "
        "You can edit anything above before sending.",
        "",
    ]
    return "\n".join(parts)


def _ring_activity() -> list:
    """The in-memory recent-activity buffer, or [] if unavailable. Never raises."""
    try:
        from localm.debuglog import recent_activity
        lines = recent_activity()
        try:
            from localm.config import home_dir
            pre_log = home_dir() / "logs" / "pre_restart.log"
            if pre_log.exists():
                lines = pre_log.read_text(encoding="utf-8").splitlines() + ["--- RESTART ---"] + lines
                pre_log.unlink(missing_ok=True)
        except Exception:
            pass
        return lines
    except Exception:
        return []


def _client_lines(client: dict) -> list:
    """Render the GUI-supplied browser context (user agent, page, viewport, recent
    console errors) for the report. All values are treated as untrusted text."""
    lines = []
    for field, label_ in (("userAgent", "User agent"), ("page", "Page"),
                          ("viewport", "Viewport"), ("appVersion", "GUI build")):
        val = client.get(field)
        if val:
            lines.append(f"- {label_}: {_scrub_home(str(val))[:300]}")
    console_errs = client.get("console")
    if isinstance(console_errs, list) and console_errs:
        rendered = "\n".join(_scrub_home(str(e)) for e in console_errs[-40:])
        lines += ["", "Recent browser console errors:", "```", rendered[-3000:], "```"]
    return lines


def save_report(text: str, when: Optional[str] = None) -> Optional[Path]:
    """Write the report to the data dir and return its path (or None on failure).
    *when* is a caller-supplied timestamp string (kept injectable for tests)."""
    try:
        from localm.config import home_dir
        base = home_dir() / "bug-reports"
    except Exception:
        base = Path.home() / ".localm" / "bug-reports"
    try:
        base.mkdir(parents=True, exist_ok=True)
        if when is None:
            import time
            when = time.strftime("%Y%m%d-%H%M%S")
        path = base / f"bug-{when}.md"
        path.write_text(text, encoding="utf-8")
        # The report carries environment diagnostics and a traceback; on a
        # multi-user box it should not be world-readable. chmod is a no-op on
        # Windows, so this is safe cross-platform.
        try:
            path.chmod(0o600)
        except OSError:
            pass
        return path
    except Exception:
        return None


def save_user_report(description: str, *, summary: str = "",
                     include_log: bool = False,
                     client: Optional[dict] = None) -> Optional[Path]:
    """Build and save a USER-initiated bug report and return its path (R47).

    The shared backend for the GUI "Report a bug" control and the
    ``localm bug-report`` CLI: the user's *description* fills the "What I was
    doing" section, the safe environment snapshot is collected as usual (now incl.
    loaded model, effective backend, session mode, a safe config subset, key
    dependency versions, and the in-memory recent-activity log), and with
    *include_log* the current run's on-disk debug log tail is attached
    (home-scrubbed at source - never the API key, config secrets, or chat data).
    *client* is an optional GUI-supplied browser context (user agent, page,
    viewport, recent JS console errors). Returns None on a write failure (the
    caller surfaces that rather than reporting a false success)."""
    description = (description or "").strip()
    if not summary:
        summary = description.splitlines()[0] if description else ""
    summary = summary.strip()[:120] or "user-reported issue"
    context: dict = {"operation": "gui-bug-report"}
    if include_log:
        import os
        tail = _recent_log_tail(pid=os.getpid())
        if tail:
            context["recent_log_tail"] = tail
    if isinstance(client, dict) and client:
        context["client"] = client
    text = build_report(summary, context=context)
    if description:
        # Drop the user's own words into the otherwise-empty "What I was doing".
        text = text.replace(
            "<!-- Please describe what you ran and what you expected. -->",
            description)
    return save_report(text)


def _truncate_body(body: str) -> str:
    if len(body) <= _MAX_PREFILL_BODY:
        return body
    return body[:_MAX_PREFILL_BODY] + "\n\n... (truncated - see the saved report file)"


def mailto_url(summary: str, body: str) -> str:
    q = urllib.parse.urlencode(
        {"subject": f"localm bug: {summary}", "body": _truncate_body(body)},
        quote_via=urllib.parse.quote)
    return f"mailto:{MAINTAINER_EMAIL}?{q}"


def issue_url(summary: str, body: str) -> str:
    q = urllib.parse.urlencode(
        {"title": f"bug: {summary}", "body": _truncate_body(body)})
    return f"{ISSUES_NEW_URL}?{q}"


def report_failure(*, summary: str, reason: str = "",
                   error: Optional[BaseException] = None,
                   context: Optional[dict] = None,
                   interactive: bool = True,
                   assume_yes: bool = False,
                   as_failure: bool = True,
                   open_browser=webbrowser.open,
                   prompt=None) -> Optional[Path]:
    """Say sorry (what + why), save an editable report, and offer to send it.

    Returns the saved report path (or None). ``interactive`` False (or
    ``assume_yes``) saves and points at the file without prompting or opening a
    browser - the right behaviour for unattended / scripted runs. ``as_failure``
    False is for a user-initiated report (``localm bug-report``): neutral header,
    no apology. ``open_browser`` and ``prompt`` are injectable for tests."""
    console.print()
    if as_failure:
        console.print(f"[bold red]Sorry - {summary}.[/bold red]")
        if reason:
            console.print(f"[red]Reason:[/red] {reason}")
    else:
        console.print(f"[bold]Filing a bug report:[/bold] {summary}")
        if reason:
            console.print(f"[dim]{reason}[/dim]")

    text = build_report(summary, reason=reason, error=error, context=context)
    path = save_report(text)
    if path is not None:
        console.print(f"[dim]A bug report was saved (edit it before sending):[/dim] {path}")
    else:
        console.print("[yellow]Could not save a report file; you can still copy the "
                      "details above.[/yellow]")

    if not interactive or assume_yes:
        console.print(f"[dim]Send it to the maintainer ({MAINTAINER_EMAIL}) by email or "
                      "Discord, or open a GitHub issue once you have repo access.[/dim]")
        return path

    console.print("How would you like to send it (edit the file first if you want)?")
    console.print("  [1] Email the maintainer  [dim](opens your mail app, works anywhere)[/dim]")
    console.print("  [2] Open a GitHub issue   [dim](needs access while the repo is private)[/dim]")
    console.print(f"  [3] I'll send it myself   [dim](Discord / email to {MAINTAINER_EMAIL})[/dim]")
    console.print("  [Enter] not now")

    ask = prompt
    if ask is None:
        import click
        def ask(text_):  # noqa: E306
            return click.prompt(text_, default="", show_default=False)
    choice = (ask("  Pick 1-3") or "").strip()

    # Re-read the saved file so the user's edits (made before picking a channel)
    # are what actually gets sent - otherwise "edit it first" would be a lie.
    body = text
    if path is not None:
        try:
            body = path.read_text(encoding="utf-8")
        except OSError:
            body = text
    try:
        if choice == "1":
            open_browser(mailto_url(summary, body))
            console.print(f"[green]Opened your mail app to {MAINTAINER_EMAIL}.[/green]")
        elif choice == "2":
            open_browser(issue_url(summary, body))
            console.print("[green]Opened a prefilled GitHub issue in your browser.[/green]")
            console.print("[dim](If it 404s, the repo is private - email it instead.)[/dim]")
        elif choice == "3":
            console.print(f"[dim]Thanks. Send {path} to {MAINTAINER_EMAIL} or on Discord "
                          "when you can.[/dim]")
        else:
            console.print("[dim]No report sent. It is saved if you change your mind.[/dim]")
    except Exception:
        console.print("[yellow]Could not open that automatically - the report is saved "
                      f"at {path}.[/yellow]")
    return path


# --------------------------------------------------------------------------- #
#  Process-wide net: catch a bug ANYWHERE, not just in a CLI command           #
#                                                                              #
#  Bugs are not confined to setup. A crash in a background thread (model       #
#  preload, the jobs runner, the coder loop) used to die silently; an uncaught #
#  main-thread exception used to dump a raw traceback. These hooks make every  #
#  Python-level failure route through the same "sorry X for Y" + report path.  #
#                                                                              #
#  Honest limit: this catches PYTHON exceptions. A native crash inside         #
#  llama.dll (segfault), an OS OOM-kill, or os._exit cannot be caught in-       #
#  process - that needs subprocess isolation, a separate effort.               #
# --------------------------------------------------------------------------- #

_handlers_installed = False


def _handle_main_exception(exc_type, exc, tb) -> None:
    """sys.excepthook: last-resort net for an uncaught main-thread exception.
    Ctrl+C stays quiet; everything else becomes a friendly report. Fully guarded:
    if reporting itself fails, defer to the interpreter's default hook."""
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc, tb)
        return
    try:
        interactive = bool(getattr(sys.stdin, "isatty", lambda: False)())
        report_failure(
            summary=getattr(exc, "summary", None) or "localm hit an unexpected error",
            reason=getattr(exc, "reason", None) or str(exc),
            error=exc, context=getattr(exc, "context", None) or {},
            interactive=interactive)
    except Exception:
        sys.__excepthook__(exc_type, exc, tb)


def _handle_thread_exception(args) -> None:
    """threading.excepthook: a crash in a background thread used to vanish. Log it
    and save a report (never prompt - a worker thread has no user attention), so a
    failure is visible without taking the whole app down."""
    exc = getattr(args, "exc_value", None)
    if exc is None or isinstance(exc, SystemExit):
        return
    try:
        tname = getattr(getattr(args, "thread", None), "name", "?")
        report_failure(
            summary=f"a background task crashed (thread '{tname}')",
            reason=str(exc), error=exc, context={"thread": tname},
            interactive=False)
    except Exception:
        try:
            threading.__excepthook__(args)
        except Exception:
            pass


def install_global_handlers(force: bool = False) -> bool:
    """Install the process-wide graceful-failure net (main thread + background
    threads). Idempotent. A no-op under pytest unless *force* (so the test runner
    keeps its own exception/thread handling). Returns True if it installed."""
    global _handlers_installed
    if _handlers_installed:
        return False
    if not force and "pytest" in sys.modules:
        return False
    sys.excepthook = _handle_main_exception
    threading.excepthook = _handle_thread_exception
    _handlers_installed = True
    return True


# --------------------------------------------------------------------------- #
#  asyncio + native-crash net (SRV-3): "fire the bug reporter no matter what"  #
#                                                                              #
#  The excepthooks above cover the main thread and background threads, but two #
#  failure modes still escaped: (1) an uncaught exception inside an asyncio    #
#  task (uvicorn's event loop) only logs "Task exception was never retrieved"; #
#  (2) a NATIVE crash (a C-extension segfault, an OS kill, or a force-closed   #
#  console window) cannot be caught in-process at all. We close (1) with an    #
#  asyncio exception handler and (2) with a crash marker: the server arms a    #
#  marker on start and disarms it on a clean shutdown, so a marker still       #
#  present on the NEXT start means the previous run died hard - and we file the #
#  report then, with the native traceback faulthandler captured.               #
# --------------------------------------------------------------------------- #

_crash_trace_fh = None   # kept alive so faulthandler can write to it


def install_asyncio_handler(loop) -> bool:
    """Route an uncaught asyncio task/loop exception through the bug reporter
    (saved, never prompted - a server loop has no user at the keyboard). Returns
    True if installed. Non-exception loop messages fall through to the default."""
    import asyncio
    try:
        def _h(loop, ctx):
            exc = ctx.get("exception")
            if isinstance(exc, (KeyboardInterrupt, SystemExit,
                                asyncio.CancelledError)):
                return   # normal control flow, not a crash
            if exc is None:
                loop.default_exception_handler(ctx)   # message-only: keep default
                return
            try:
                report_failure(
                    summary="an async task crashed",
                    reason=ctx.get("message") or str(exc),
                    error=exc, context={"asyncio": ctx.get("message", "")},
                    interactive=False)
            except Exception:
                loop.default_exception_handler(ctx)
        loop.set_exception_handler(_h)
        return True
    except Exception:
        return False


def _crash_dir(home=None):
    from pathlib import Path
    if home is None:
        from localm.config import HOME_DIR
        home = HOME_DIR
    d = Path(home) / "run"
    d.mkdir(parents=True, exist_ok=True)
    return d


def arm_crash_guard(context: Optional[dict] = None, home=None) -> bool:
    """Mark that a server run is in progress and enable faulthandler so a native
    fault leaves a trace. If the process dies hard the marker survives;
    check_and_report_prior_crash() reports it on the next start. Returns True if
    armed. Fully guarded - never raises into the caller."""
    global _crash_trace_fh
    import faulthandler
    import json
    import os
    try:
        d = _crash_dir(home)
        _crash_trace_fh = open(d / "server-crash-trace.txt", "w", encoding="utf-8")
        try:
            faulthandler.enable(file=_crash_trace_fh, all_threads=True)
        except Exception:
            pass
        (d / "server-crash.marker").write_text(
            json.dumps({"pid": os.getpid(), "context": context or {}}),
            encoding="utf-8")
        return True
    except Exception:
        return False


def disarm_crash_guard(home=None) -> None:
    """Clean shutdown: drop the marker so the next start does not report a crash."""
    global _crash_trace_fh
    import faulthandler
    try:
        (_crash_dir(home) / "server-crash.marker").unlink(missing_ok=True)
    except Exception:
        pass
    try:
        if _crash_trace_fh is not None:
            faulthandler.disable()
            _crash_trace_fh.close()
            _crash_trace_fh = None
    except Exception:
        pass


def check_and_report_prior_crash(home=None, interactive: bool = False):
    """If a previous server run left a crash marker (it died without a clean
    shutdown: a native crash, an OS kill, or a force-closed window), file a bug
    report so the failure is never lost, then clear the marker. Returns the
    report path if one was filed, else None. Never raises into the caller."""
    import json
    try:
        marker = _crash_dir(home) / "server-crash.marker"
        if not marker.exists():
            return None
        info = {}
        try:
            info = json.loads(marker.read_text(encoding="utf-8"))
        except Exception:
            pass
        trace = ""
        try:
            tp = _crash_dir(home) / "server-crash-trace.txt"
            if tp.exists():
                trace = tp.read_text(encoding="utf-8").strip()
        except Exception:
            pass
        # Clear FIRST so a failure while reporting cannot loop the marker forever.
        try:
            marker.unlink(missing_ok=True)
        except Exception:
            pass
        ctx = {"prior_run": info}
        if trace:
            ctx["native_trace"] = trace[:4000]
        # Attach the crashed run's own log tail (matched by pid) so the report is
        # actionable even with no native trace (window-close / OS-kill leave none).
        tail = _recent_log_tail(home, pid=info.get("pid"))
        if tail:
            ctx["recent_log_tail"] = tail
        return report_failure(
            summary="localm server crashed (recovered on the next start)",
            reason=("the previous server run ended without a clean shutdown - a "
                    "native crash, an OS kill, or a force-closed window"),
            error=None, context=ctx, interactive=interactive)
    except Exception:
        return None
