# SPDX-License-Identifier: AGPL-3.0-or-later
"""Graceful failure + an autogenerated, user-editable bug report.

When something goes wrong, localm should fail like a good citizen: say *what*
broke and *why* in plain language, then offer to send a prefilled report the
user can read and edit before anything leaves their machine.

Channels, in the order that actually works for a tester:
  * **email** - opens the user's mail app prefilled to the maintainer. Works for
    anyone, including a tester on a still-private repo.
  * **GitHub issue** - opens a prefilled new-issue page. Best once the repo is
    public (or the tester is a collaborator); noted as such.
  * **do it yourself** - the report is always saved to a file, so the user can
    drop it on Discord, paste it, or attach it however they like.

The maintainer's contact email is intentionally published here for bug reports
(the maintainer opted in); see scripts/check_hygiene.py.

Diagnostics are deliberately conservative: OS / GPU / driver / backend / the
error, and the *names* of provisioned libraries - never environment variables
(which can hold an API key), config contents, or chat data. The user reviews and
edits the report before sending regardless.
"""

from __future__ import annotations

import platform
import sys
import threading
import traceback
import urllib.parse
import webbrowser
from pathlib import Path
from typing import Optional

from rich.console import Console

console = Console(highlight=False)

# Intentionally published maintainer contact for bug reports (hygiene-ok).
MAINTAINER_EMAIL = "theilige@gmail.com"
REPO_SLUG = "Matlan1/localm"
ISSUES_NEW_URL = f"https://github.com/{REPO_SLUG}/issues/new"

# mailto/issue bodies cannot be arbitrarily long (mail clients and some browsers
# truncate very long query strings), so the prefilled body is a short pointer and
# the full detail lives in the saved file the user attaches or pastes.
_MAX_PREFILL_BODY = 1500


class LocalmError(Exception):
    """A user-facing, reportable failure.

    Raise this (not a bare Exception) when a command hits a known, describable
    problem. The CLI's single graceful handler turns it into a "sorry, X went
    wrong because Y" message and offers a bug report - the command that raises it
    knows nothing about reporting. Carries a human *summary*, an optional
    *reason*, and diagnostic *context* for the report."""

    def __init__(self, summary: str, reason: str = "",
                 context: Optional[dict] = None):
        super().__init__(summary)
        self.summary = summary
        self.reason = reason
        self.context = context or {}


def _localm_version() -> str:
    try:
        from importlib.metadata import version
        return version("localm")
    except Exception:
        return "unknown"


def _runtime_libs() -> tuple:
    """(binary_dir or None, sorted list of native library file NAMES present).
    Names only - never full paths beyond the resolved dir, never contents."""
    try:
        from localm.inference.backends.llamacpp._loader import (
            lib_filename, runtime_binary_dir)
        d = runtime_binary_dir()
        if d is None:
            return None, []
        # Load-bearing shared libraries only - the bundled llama-*.exe tools are
        # noise in a report (dozens of them) and not relevant to a load failure.
        names = sorted(
            f.name for f in Path(d).iterdir()
            if f.is_file() and (f.suffix.lower() in (".dll", ".so", ".dylib")
                                or ".so." in f.name)
        )
        return d, names, lib_filename()
    except Exception:
        return None, [], ""


def collect_diagnostics(context: Optional[dict] = None) -> dict:
    """Gather a safe, useful environment snapshot. Never raises."""
    context = dict(context or {})
    diag: dict = {}
    try:
        diag["localm_version"] = _localm_version()
        diag["python"] = sys.version.split()[0]
        diag["platform"] = platform.platform()
        diag["machine"] = platform.machine()
    except Exception:
        pass

    try:
        from localm import hwdetect
        det = hwdetect.detect()
        diag["gpu_vendors"] = det.vendors or []
        diag["recommended_backend"] = det.recommended
        diag["detect_source"] = det.source
    except Exception:
        diag["gpu_vendors"] = []

    # NVIDIA driver / CUDA capability, when an NVIDIA GPU is involved.
    try:
        from localm.setup_llama import nvidia_preflight
        if "nvidia" in diag.get("gpu_vendors", []) or context.get("backend") == "cuda":
            nv = nvidia_preflight()
            if nv.present:
                diag["nvidia_gpu"] = nv.gpu_name
                diag["nvidia_driver"] = nv.driver_version
                diag["nvidia_cuda_capability"] = nv.cuda_capability
    except Exception:
        pass

    try:
        res = _runtime_libs()
        binary_dir = res[0]
        names = res[1]
        diag["native_runtime_provisioned"] = binary_dir is not None
        diag["native_libs"] = names
    except Exception:
        pass

    # Caller-supplied context (chosen backend, the operation, etc.).
    for k in ("operation", "backend", "requested_backend", "with_cudart"):
        if k in context:
            diag[k] = context[k]
    return diag


def _format_error(error: Optional[BaseException]) -> str:
    if error is None:
        return ""
    tb = "".join(traceback.format_exception(type(error), error, error.__traceback__))
    # Drop the home directory (which contains the username) from frame paths so a
    # tester's report does not leak their account name; the file/line structure
    # that matters for debugging is kept.
    try:
        home = str(Path.home())
        if home:
            tb = tb.replace(home, "~")
    except Exception:
        pass
    # Keep the tail - the last frames are the useful ones, and a shorter report
    # is more likely to be read and sent.
    lines = tb.strip().splitlines()
    if len(lines) > 25:
        lines = ["... (earlier frames trimmed) ..."] + lines[-24:]
    return "\n".join(lines)


def build_report(summary: str, reason: str = "",
                 error: Optional[BaseException] = None,
                 context: Optional[dict] = None) -> str:
    """Render an editable markdown bug report. The user owns it before sending."""
    diag = collect_diagnostics(context)
    err = _format_error(error)

    env_lines = []
    label = {
        "localm_version": "localm", "python": "Python", "platform": "OS",
        "machine": "Arch", "gpu_vendors": "GPU vendor(s)",
        "recommended_backend": "Recommended backend", "detect_source": "Detected via",
        "nvidia_gpu": "NVIDIA GPU", "nvidia_driver": "NVIDIA driver",
        "nvidia_cuda_capability": "Driver CUDA capability",
        "native_runtime_provisioned": "Native runtime provisioned",
        "native_libs": "Native libraries", "operation": "Operation",
        "backend": "Backend (effective)", "requested_backend": "Backend (requested)",
        "with_cudart": "Fetched CUDA runtime bundle",
    }
    for key, name in label.items():
        if key in diag:
            val = diag[key]
            if isinstance(val, list):
                val = ", ".join(str(x) for x in val) if val else "(none)"
            env_lines.append(f"- {name}: {val}")

    parts = [
        f"# localm bug report: {summary}",
        "",
        "## What I was doing",
        "<!-- Please describe what you ran and what you expected. -->",
        "",
        "## What happened",
        summary + ((f"\n\nReason: {reason}") if reason else ""),
        "",
        "## Environment",
        "\n".join(env_lines) if env_lines else "(could not collect environment)",
    ]
    if err:
        parts += ["", "## Error detail", "```", err, "```"]
    parts += [
        "",
        "---",
        f"Sent to the localm maintainer ({MAINTAINER_EMAIL}). "
        "You can edit anything above before sending.",
        "",
    ]
    return "\n".join(parts)


def save_report(text: str, when: Optional[str] = None) -> Optional[Path]:
    """Write the report to the data dir and return its path (or None on failure).
    *when* is a caller-supplied timestamp string (kept injectable for tests)."""
    try:
        from localm.config import home_dir
        base = home_dir() / "bug-reports"
    except Exception:
        base = Path.home() / ".localm" / "bug-reports"
    try:
        base.mkdir(parents=True, exist_ok=True)
        if when is None:
            import time
            when = time.strftime("%Y%m%d-%H%M%S")
        path = base / f"bug-{when}.md"
        path.write_text(text, encoding="utf-8")
        # The report carries environment diagnostics and a traceback; on a
        # multi-user box it should not be world-readable. chmod is a no-op on
        # Windows, so this is safe cross-platform.
        try:
            path.chmod(0o600)
        except OSError:
            pass
        return path
    except Exception:
        return None


def _truncate_body(body: str) -> str:
    if len(body) <= _MAX_PREFILL_BODY:
        return body
    return body[:_MAX_PREFILL_BODY] + "\n\n... (truncated - see the saved report file)"


def mailto_url(summary: str, body: str) -> str:
    q = urllib.parse.urlencode(
        {"subject": f"localm bug: {summary}", "body": _truncate_body(body)},
        quote_via=urllib.parse.quote)
    return f"mailto:{MAINTAINER_EMAIL}?{q}"


def issue_url(summary: str, body: str) -> str:
    q = urllib.parse.urlencode(
        {"title": f"bug: {summary}", "body": _truncate_body(body)})
    return f"{ISSUES_NEW_URL}?{q}"


def report_failure(*, summary: str, reason: str = "",
                   error: Optional[BaseException] = None,
                   context: Optional[dict] = None,
                   interactive: bool = True,
                   assume_yes: bool = False,
                   as_failure: bool = True,
                   open_browser=webbrowser.open,
                   prompt=None) -> Optional[Path]:
    """Say sorry (what + why), save an editable report, and offer to send it.

    Returns the saved report path (or None). ``interactive`` False (or
    ``assume_yes``) saves and points at the file without prompting or opening a
    browser - the right behaviour for unattended / scripted runs. ``as_failure``
    False is for a user-initiated report (``localm bug-report``): neutral header,
    no apology. ``open_browser`` and ``prompt`` are injectable for tests."""
    console.print()
    if as_failure:
        console.print(f"[bold red]Sorry - {summary}.[/bold red]")
        if reason:
            console.print(f"[red]Reason:[/red] {reason}")
    else:
        console.print(f"[bold]Filing a bug report:[/bold] {summary}")
        if reason:
            console.print(f"[dim]{reason}[/dim]")

    text = build_report(summary, reason=reason, error=error, context=context)
    path = save_report(text)
    if path is not None:
        console.print(f"[dim]A bug report was saved (edit it before sending):[/dim] {path}")
    else:
        console.print("[yellow]Could not save a report file; you can still copy the "
                      "details above.[/yellow]")

    if not interactive or assume_yes:
        console.print(f"[dim]Send it to the maintainer ({MAINTAINER_EMAIL}) by email or "
                      "Discord, or open a GitHub issue once you have repo access.[/dim]")
        return path

    console.print("How would you like to send it (edit the file first if you want)?")
    console.print("  [1] Email the maintainer  [dim](opens your mail app, works anywhere)[/dim]")
    console.print("  [2] Open a GitHub issue   [dim](needs access while the repo is private)[/dim]")
    console.print(f"  [3] I'll send it myself   [dim](Discord / email to {MAINTAINER_EMAIL})[/dim]")
    console.print("  [Enter] not now")

    ask = prompt
    if ask is None:
        import click
        def ask(text_):  # noqa: E306
            return click.prompt(text_, default="", show_default=False)
    choice = (ask("  Pick 1-3") or "").strip()

    # Re-read the saved file so the user's edits (made before picking a channel)
    # are what actually gets sent - otherwise "edit it first" would be a lie.
    body = text
    if path is not None:
        try:
            body = path.read_text(encoding="utf-8")
        except OSError:
            body = text
    try:
        if choice == "1":
            open_browser(mailto_url(summary, body))
            console.print(f"[green]Opened your mail app to {MAINTAINER_EMAIL}.[/green]")
        elif choice == "2":
            open_browser(issue_url(summary, body))
            console.print("[green]Opened a prefilled GitHub issue in your browser.[/green]")
            console.print("[dim](If it 404s, the repo is private - email it instead.)[/dim]")
        elif choice == "3":
            console.print(f"[dim]Thanks. Send {path} to {MAINTAINER_EMAIL} or on Discord "
                          "when you can.[/dim]")
        else:
            console.print("[dim]No report sent. It is saved if you change your mind.[/dim]")
    except Exception:
        console.print("[yellow]Could not open that automatically - the report is saved "
                      f"at {path}.[/yellow]")
    return path


# --------------------------------------------------------------------------- #
#  Process-wide net: catch a bug ANYWHERE, not just in a CLI command           #
#                                                                              #
#  Bugs are not confined to setup. A crash in a background thread (model       #
#  preload, the jobs runner, the coder loop) used to die silently; an uncaught #
#  main-thread exception used to dump a raw traceback. These hooks make every  #
#  Python-level failure route through the same "sorry X for Y" + report path.  #
#                                                                              #
#  Honest limit: this catches PYTHON exceptions. A native crash inside         #
#  llama.dll (segfault), an OS OOM-kill, or os._exit cannot be caught in-       #
#  process - that needs subprocess isolation, a separate effort.               #
# --------------------------------------------------------------------------- #

_handlers_installed = False


def _handle_main_exception(exc_type, exc, tb) -> None:
    """sys.excepthook: last-resort net for an uncaught main-thread exception.
    Ctrl+C stays quiet; everything else becomes a friendly report. Fully guarded:
    if reporting itself fails, defer to the interpreter's default hook."""
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc, tb)
        return
    try:
        interactive = bool(getattr(sys.stdin, "isatty", lambda: False)())
        report_failure(
            summary=getattr(exc, "summary", None) or "localm hit an unexpected error",
            reason=getattr(exc, "reason", None) or str(exc),
            error=exc, context=getattr(exc, "context", None) or {},
            interactive=interactive)
    except Exception:
        sys.__excepthook__(exc_type, exc, tb)


def _handle_thread_exception(args) -> None:
    """threading.excepthook: a crash in a background thread used to vanish. Log it
    and save a report (never prompt - a worker thread has no user attention), so a
    failure is visible without taking the whole app down."""
    exc = getattr(args, "exc_value", None)
    if exc is None or isinstance(exc, SystemExit):
        return
    try:
        tname = getattr(getattr(args, "thread", None), "name", "?")
        report_failure(
            summary=f"a background task crashed (thread '{tname}')",
            reason=str(exc), error=exc, context={"thread": tname},
            interactive=False)
    except Exception:
        try:
            threading.__excepthook__(args)
        except Exception:
            pass


def install_global_handlers(force: bool = False) -> bool:
    """Install the process-wide graceful-failure net (main thread + background
    threads). Idempotent. A no-op under pytest unless *force* (so the test runner
    keeps its own exception/thread handling). Returns True if it installed."""
    global _handlers_installed
    if _handlers_installed:
        return False
    if not force and "pytest" in sys.modules:
        return False
    sys.excepthook = _handle_main_exception
    threading.excepthook = _handle_thread_exception
    _handlers_installed = True
    return True
