#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Advance localm's AMD ROCm wheel pins (torch, torchvision, rocm-sdk-core,
rocm-sdk-libraries-gfx103x-all) and regenerate uv.lock.

The ``[gpu]`` extra pins torch and torchvision with an exact ``==version`` in
``pyproject.toml`` and again as wheel URLs in ``[tool.uv.sources]``. The two
rocm-sdk packages carry no version in ``pyproject.toml``; ``uv.lock`` records
the version uv resolved from AMD's wheel index. This script moves all four
together. It is review-only: a person reads the diff and the printed checklist,
then merges.

``--tag`` names all four packages as ``package==version`` pairs, for example
``torch==2.11.0+rocm7.13.0,torchvision==0.26.0+rocm7.13.0,rocm-sdk-core==7.13.0,
rocm-sdk-libraries-gfx103x-all==7.13.0``. A package named at its current version
stays; at least one must move forward.

WHAT IT REWRITES (with ``--write``; without it, a unified diff is printed and
nothing is touched):

  pyproject.toml
    the torch and torchvision ``==`` pins in the gpu extra
    the torch and torchvision wheel URLs in [tool.uv.sources]
  uv.lock
    regenerated by ``uv lock`` in a scratch directory holding only the new
    pyproject.toml and the current uv.lock; copied into the tree only when it
    verifies

WHAT IT CHECKS BEFORE WRITING:
  * all four packages are named once, with plain versions (torch and torchvision
    carry a ``+rocmX.Y.Z`` local part, the rocm-sdk packages do not);
  * no package moves backwards and at least one moves forward; torch and
    torchvision share one ROCm release and the two rocm-sdk packages share one
    version;
  * AMD's wheel index lists each requested wheel (cp312 win_amd64 for torch and
    torchvision, py3-none win_amd64 for the rocm-sdk packages), and the ``rocm``
    sdist when the rocm-sdk version moves;
  * ``uv lock`` succeeds, the new lock records exactly the requested versions,
    ``uv lock --check`` accepts it, and the pyproject regions are each found
    exactly once. A failure at any step leaves the tree untouched.

WHAT IT LEAVES TO A PERSON, printed as the remaining checklist: the packages
whose locked version changed, the targeted tests, the ComfyUI torch pin that
this script does not touch, a real import and generation on a gfx103x Windows
machine, and the CHANGELOG bullet. Nothing is installed or run on a GPU here.

Exit codes: 0 when the edit was applied or the dry run completed; 1 when
refused.

Environment: needs ``uv`` on PATH; ``UV_CACHE_DIR`` is honoured.

Usage:
    python scripts/bump_amd_wheels_pin.py --tag "torch==2.11.0+rocm7.13.0,torchvision==0.26.0+rocm7.13.0,rocm-sdk-core==7.13.0,rocm-sdk-libraries-gfx103x-all==7.13.0"
    ... --write
"""

import argparse
import difflib
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INDEX_BASE = "https://repo.amd.com/rocm/whl/gfx103X-all"
UV_TIMEOUT = 900
MAX_INDEX_BYTES = 16 * 1024 * 1024

TORCH_STACK = ("torch", "torchvision")
ROCM_SDK = ("rocm-sdk-core", "rocm-sdk-libraries-gfx103x-all")
PACKAGES = TORCH_STACK + ROCM_SDK

_STACK_VERSION_RE = re.compile(r"^(\d+(?:\.\d+)*)\+rocm(\d+(?:\.\d+)*)$")
_SDK_VERSION_RE = re.compile(r"^\d+(?:\.\d+)*$")
_HREF_RE = re.compile(r'href="([^"]+)"')
_LOCK_PACKAGE_RE = re.compile(r'^\[\[package\]\]\nname = "([^"]+)"\nversion = "([^"]+)"', re.M)


class Refused(Exception):
    """The bump cannot proceed; the message says why."""


# --------------------------------------------------------------------------- #
#  The request                                                                #
# --------------------------------------------------------------------------- #

def parse_request(text: str) -> dict:
    """{package: version} from ``pkg==ver,...``. Raises Refused unless it names
    exactly the four packages once each with well-formed versions."""
    out: dict = {}
    for pair in [p.strip() for p in (text or "").split(",")]:
        pkg, sep, ver = pair.partition("==")
        if not sep or pkg not in PACKAGES or "=" in ver:
            raise Refused(f"{pair!r} is not package==version for one of {', '.join(PACKAGES)}")
        if pkg in out:
            raise Refused(f"{pkg} appears more than once in --tag")
        check_shape(pkg, ver)
        out[pkg] = ver
    missing = [p for p in PACKAGES if p not in out]
    if missing:
        raise Refused(f"--tag must name all four packages; missing {', '.join(missing)}")
    return out


def check_shape(package: str, version: str) -> None:
    """Raises Refused unless *version* has the shape *package* is pinned with."""
    if package in TORCH_STACK:
        if not _STACK_VERSION_RE.match(version):
            raise Refused(f"{package}: {version!r} is not VERSION+rocmX.Y.Z")
    elif not _SDK_VERSION_RE.match(version):
        raise Refused(f"{package}: {version!r} is not a plain dotted version")


def _tuple(text: str) -> tuple:
    return tuple(int(p) for p in text.split("."))


def _pad(parts: tuple) -> tuple:
    return parts + (0,) * (8 - len(parts))


def sort_key(package: str, version: str) -> tuple:
    """Orderable key: the base version, then the ROCm release of a local part,
    padded so 7.13 equals 7.13.0."""
    if package in TORCH_STACK:
        m = _STACK_VERSION_RE.match(version)
        base, rocm = _tuple(m.group(1)), _tuple(m.group(2))
    else:
        base, rocm = _tuple(version), ()
    return _pad(base), _pad(rocm)


def plan_moves(current: dict, wanted: dict) -> dict:
    """The packages that move forward. Raises Refused when one moves backwards,
    nothing moves, or the requested versions disagree with each other."""
    moves = {}
    for package in PACKAGES:
        old, new = current[package], wanted[package]
        key_old, key_new = sort_key(package, old), sort_key(package, new)
        if key_new < key_old:
            raise Refused(f"{package}: {new} is older than the pinned {old}; this script "
                          "only moves a pin forward")
        if key_new > key_old:
            moves[package] = new
    if not moves:
        raise Refused("every package is already at the requested version; nothing to bump")
    if sort_key("torch", wanted["torch"])[1] != sort_key("torchvision", wanted["torchvision"])[1]:
        raise Refused("torch and torchvision name different ROCm releases "
                      f"({wanted['torch']}, {wanted['torchvision']})")
    if sort_key(ROCM_SDK[0], wanted[ROCM_SDK[0]]) != sort_key(ROCM_SDK[1], wanted[ROCM_SDK[1]]):
        raise Refused("rocm-sdk-core and rocm-sdk-libraries-gfx103x-all must share one version")
    return moves


# --------------------------------------------------------------------------- #
#  Upstream (injectable)                                                      #
# --------------------------------------------------------------------------- #

def _default_open(req, timeout):
    from localm.http_ssl import verified_urlopen
    return verified_urlopen(req, timeout=timeout)


def fetch_text(url: str, opener=None) -> str:
    """GET *url* and return its text. Raises Refused when it cannot be read."""
    if opener is None:
        opener = _default_open
    req = urllib.request.Request(url, headers={"User-Agent": "localm-bump-amd-wheels-pin"})
    try:
        with opener(req, 30) as resp:
            raw = resp.read(MAX_INDEX_BYTES + 1)
        if len(raw) > MAX_INDEX_BYTES:
            raise ValueError("response is larger than the allowed size")
        return raw.decode("utf-8")
    except Exception as e:
        raise Refused(f"could not read {url}: {type(e).__name__}: {e}") from e


def index_filenames(package: str, fetch_text_fn=fetch_text) -> set:
    """The file names AMD's index lists for *package*, percent-decoded."""
    html = fetch_text_fn(f"{INDEX_BASE}/{package}/")
    names = set()
    for href in _HREF_RE.findall(html):
        names.add(urllib.parse.unquote(href.split("#", 1)[0].rsplit("/", 1)[-1]))
    return names


def wheel_name(package: str, version: str) -> str:
    dist = package.replace("-", "_")
    if package in TORCH_STACK:
        return f"{dist}-{version}-cp312-cp312-win_amd64.whl"
    return f"{dist}-{version}-py3-none-win_amd64.whl"


def verify_on_index(wanted: dict, moves: dict, fetch_text_fn=fetch_text) -> None:
    """Raises Refused unless AMD's index lists every requested wheel (and the
    ``rocm`` sdist when the rocm-sdk version moves)."""
    for package in PACKAGES:
        names = index_filenames(package, fetch_text_fn)
        want = wheel_name(package, wanted[package])
        if want not in names:
            raise Refused(f"AMD's index lists no {want} for {package}")
    if any(p in moves for p in ROCM_SDK):
        sdk = wanted[ROCM_SDK[0]]
        if f"rocm-{sdk}.tar.gz" not in index_filenames("rocm", fetch_text_fn):
            raise Refused(f"AMD's index lists no rocm-{sdk}.tar.gz for the rocm package")


# --------------------------------------------------------------------------- #
#  The tree                                                                   #
# --------------------------------------------------------------------------- #

def _read(path: Path) -> tuple:
    """(text with LF newlines, the newline sequence the file uses)."""
    data = path.read_bytes().decode("utf-8")
    newline = "\r\n" if "\r\n" in data else "\n"
    return data.replace("\r\n", "\n"), newline


def _write(path: Path, text: str, newline: str) -> None:
    path.write_bytes(text.replace("\n", newline).encode("utf-8"))


def _pin_re(package: str) -> re.Pattern:
    return re.compile(rf'(?P<pre>"{re.escape(package)}==)(?P<ver>[^";\s]+)(?P<post>; sys_platform == \'win32\'")')


def _url_re(package: str) -> re.Pattern:
    return re.compile(rf'(?P<pre>url = "{re.escape(INDEX_BASE)}/{re.escape(package)}-)'
                      r'(?P<ver>[^"/]+?)(?P<post>-cp312-cp312-win_amd64\.whl")')


def _only(pattern: re.Pattern, text: str, what: str):
    matches = list(pattern.finditer(text))
    if len(matches) != 1:
        raise Refused(f"{what}: expected exactly one match, found {len(matches)}; "
                      "the file shape this script edits has changed")
    return matches[0]


def lock_versions(lock_text: str) -> dict:
    """{package name: [versions]} for every [[package]] in a uv.lock."""
    out: dict = {}
    for name, version in _LOCK_PACKAGE_RE.findall(lock_text):
        out.setdefault(name, []).append(version)
    return out


def read_current(pyproject: str, lock_text: str) -> dict:
    """The currently pinned version of each package. Raises Refused when a pin is
    missing, the pin and its wheel URL disagree, or a rocm-sdk package is not
    locked exactly once."""
    current = {}
    for package in TORCH_STACK:
        pin = _only(_pin_re(package), pyproject, f"{package} == pin").group("ver")
        url = _only(_url_re(package), pyproject, f"{package} wheel URL").group("ver")
        if urllib.parse.unquote(url) != pin:
            raise Refused(f"{package}: the pin is {pin} but the wheel URL names "
                          f"{urllib.parse.unquote(url)}; the tree is inconsistent")
        check_shape(package, pin)
        current[package] = pin
    locked = lock_versions(lock_text)
    for package in ROCM_SDK:
        versions = locked.get(package, [])
        if len(versions) != 1:
            raise Refused(f"{package}: uv.lock records {len(versions)} versions, expected one")
        check_shape(package, versions[0])
        current[package] = versions[0]
    return current


def rewrite_pyproject(text: str, wanted: dict) -> str:
    """*text* with the torch and torchvision pins and wheel URLs set to *wanted*."""
    for package in TORCH_STACK:
        version = wanted[package]
        for label, pattern, value in (
                ("== pin", _pin_re(package), version),
                ("wheel URL", _url_re(package), urllib.parse.quote(version, safe=".-"))):
            m = _only(pattern, text, f"{package} {label}")
            text = text[:m.start("ver")] + value + text[m.end("ver"):]
    return text


# --------------------------------------------------------------------------- #
#  uv                                                                         #
# --------------------------------------------------------------------------- #

def run_uv(args: list, directory: Path) -> tuple:
    """(exit code, combined output) of ``uv --directory <directory> <args>``.
    Raises Refused when uv is missing or times out."""
    exe = shutil.which("uv")
    if not exe:
        raise Refused("uv is not on PATH; it is needed to regenerate uv.lock")
    try:
        proc = subprocess.run([exe, "--directory", str(directory), *args], capture_output=True,
                              text=True, timeout=UV_TIMEOUT)
    except subprocess.TimeoutExpired as e:
        raise Refused(f"uv {' '.join(args)} did not finish in {UV_TIMEOUT}s") from e
    return proc.returncode, (proc.stdout or "") + (proc.stderr or "")


def upgrade_args(wanted: dict, moves: dict) -> list:
    """The ``uv lock`` arguments that move the rocm-sdk packages (and the rocm
    meta package) to the requested version."""
    if not any(p in moves for p in ROCM_SDK):
        return []
    sdk = wanted[ROCM_SDK[0]]
    args = []
    for package in (*ROCM_SDK, "rocm"):
        args += ["--upgrade-package", f"{package}=={sdk}"]
    return args


def regenerate_lock(pyproject: str, lock_text: str, wanted: dict, moves: dict,
                    run_uv_fn=run_uv) -> tuple:
    """(new uv.lock text, uv's output). Runs uv in a scratch directory holding only
    the new pyproject.toml and the current uv.lock. Raises Refused when uv fails or
    the new lock does not record exactly the requested versions or is not accepted
    by ``uv lock --check``."""
    with tempfile.TemporaryDirectory(prefix="bump-amd-") as tmp:
        scratch = Path(tmp)
        (scratch / "pyproject.toml").write_bytes(pyproject.encode("utf-8"))
        (scratch / "uv.lock").write_bytes(lock_text.encode("utf-8"))
        code, out = run_uv_fn(["lock", *upgrade_args(wanted, moves)], scratch)
        if code != 0:
            raise Refused(f"uv lock failed (exit {code}): {out.strip()[-600:]}")
        new_lock = (scratch / "uv.lock").read_bytes().decode("utf-8").replace("\r\n", "\n")
        verify_lock(new_lock, wanted)
        code, check = run_uv_fn(["lock", "--check"], scratch)
        if code != 0:
            raise Refused(f"uv lock --check rejects the regenerated lock (exit {code}): "
                          f"{check.strip()[-600:]}")
        return new_lock, out


def verify_lock(lock_text: str, wanted: dict) -> None:
    """Raises Refused unless the lock records exactly the requested AMD versions."""
    locked = lock_versions(lock_text)
    for package in TORCH_STACK:
        local = [v for v in locked.get(package, []) if "+rocm" in v]
        if local != [wanted[package]]:
            raise Refused(f"the regenerated lock holds {package} {local or 'no ROCm build'}, "
                          f"not {wanted[package]}")
    for package in ROCM_SDK:
        if locked.get(package) != [wanted[package]]:
            raise Refused(f"the regenerated lock holds {package} {locked.get(package)}, "
                          f"not {wanted[package]}")
    if "rocm" in locked and locked["rocm"] != [wanted[ROCM_SDK[0]]]:
        raise Refused(f"the regenerated lock holds rocm {locked['rocm']}, "
                      f"not {wanted[ROCM_SDK[0]]}")


def changed_packages(old_lock: str, new_lock: str) -> list:
    """``name: old -> new`` lines for every package whose locked versions differ."""
    old, new = lock_versions(old_lock), lock_versions(new_lock)
    lines = []
    for name in sorted(set(old) | set(new)):
        if old.get(name) != new.get(name):
            lines.append(f"{name}: {', '.join(old.get(name, ['(absent)']))} -> "
                         f"{', '.join(new.get(name, ['(removed)']))}")
    return lines


# --------------------------------------------------------------------------- #
#  Output                                                                     #
# --------------------------------------------------------------------------- #

def checklist(wanted: dict, current: dict, changes: list) -> str:
    rocm_local = _STACK_VERSION_RE.match(wanted["torch"]).group(2)
    lines = ["REMAINING STEPS, not automated - each has its own check:"]
    lines += ["  1. packages whose locked version changed (read them; a torch bump can move its",
              "       dependencies):"]
    lines += [f"       {c}" for c in changes] or ["       (none)"]
    lines += [
        "  2. pytest tests/test_bump_amd_wheels_pin.py tests/test_check_amd_rocm_wheels_pin.py",
        "       tests/test_gpu_extra_pins.py",
        "  3. python scripts/check_amd_rocm_wheels_pin.py   reports every package current",
        "  4. localm/media/managed_comfy_fresh.py _AMD_GFX103X_TORCH is a separate pin for the",
        "       managed ComfyUI and is not touched by this script",
    ]
    if sort_key(ROCM_SDK[0], wanted[ROCM_SDK[0]])[0][:3] != sort_key("torch", wanted["torch"])[1][:3]:
        lines.append(f"  !! the rocm-sdk version {wanted[ROCM_SDK[0]]} differs from the torch ROCm "
                     f"release {rocm_local}: check that AMD ships them as one release")
    lines += [
        "  5. comments in pyproject.toml that name the old torch or ROCm release (history or",
        "       measured notes; edit only if now false)",
        "  6. A real import and a model generation on a gfx103x Windows machine; no GPU wheel is",
        "       installed or run by this script",
        "  7. CHANGELOG.md, [Unreleased]: one bullet, the AMD GPU stack moved",
    ]
    return "\n".join(lines)


def main(argv=None, *, fetch_text_fn=fetch_text, run_uv_fn=run_uv) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tag", required=True,
                    help='"torch==V+rocmX,torchvision==V+rocmX,rocm-sdk-core==V,'
                         'rocm-sdk-libraries-gfx103x-all==V"')
    ap.add_argument("--write", action="store_true",
                    help="apply the edit (default: print a diff and change nothing)")
    args = ap.parse_args(argv)

    pyproject_path, lock_path = REPO / "pyproject.toml", REPO / "uv.lock"
    try:
        wanted = parse_request(args.tag)
        pyproject, py_nl = _read(pyproject_path)
        lock_text, lock_nl = _read(lock_path)
        current = read_current(pyproject, lock_text)
        moves = plan_moves(current, wanted)
        print("moving: " + ", ".join(f"{p} {current[p]} -> {v}" for p, v in moves.items()))
        verify_on_index(wanted, moves, fetch_text_fn)
        print("  AMD's wheel index lists every requested wheel")
        new_pyproject = rewrite_pyproject(pyproject, wanted)
        print("running uv lock in a scratch directory ...")
        new_lock, _ = regenerate_lock(new_pyproject, lock_text, wanted, moves, run_uv_fn)
        print("  the regenerated lock records exactly the requested versions and passes --check")
    except Refused as e:
        print(f"REFUSED: {e}")
        return 1

    changes = changed_packages(lock_text, new_lock)
    for path, rel, old, new, newline in ((pyproject_path, "pyproject.toml", pyproject,
                                          new_pyproject, py_nl),
                                         (lock_path, "uv.lock", lock_text, new_lock, lock_nl)):
        if old == new:
            continue
        if args.write:
            _write(path, new, newline)
            print(f"wrote {rel}")
        else:
            sys.stdout.writelines(difflib.unified_diff(
                old.splitlines(keepends=True), new.splitlines(keepends=True),
                fromfile=f"a/{rel}", tofile=f"b/{rel}", n=1))
    if not args.write:
        print("\n(dry run: nothing written; add --write to apply)")
    print()
    print(checklist(wanted, current, changes))
    return 0


if __name__ == "__main__":
    sys.exit(main())
