#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Drive every llama.cpp BPE pre-tokenizer regex through the REAL, unmodified
upstream ``unicode_regex_split()`` with adversarial repetition input, and
report which ones are catastrophic under the runtime localm actually ships.

WHY THE REAL RUNTIME, NOT A STATIC SCAN. ``tokenizer.ggml.pre`` in a GGUF's
metadata selects one of llama.cpp's ~35 hardcoded ``regex_exprs`` lists (see
``llm_tokenizer_bpe``'s constructor in ``src/llama-vocab.cpp``); a caller can
only pick among these, never inject a novel pattern. Whether one of them is
itself catastrophic is a bounded, offline-answerable question, but it needs
the pattern actually EXECUTED: Python's ``re`` cannot even compile most of
them (they use PCRE/ICU syntax such as ``\\p{L}``), and a different engine
that CAN compile them (Python's ``regex`` module, PCRE, ICU) still answers a
different question - this project has already measured that ``re``,
``regex`` and Oniguruma have different catastrophic sets, and MSVC's
``std::wregex`` (what localm's shipped Windows runtime actually uses) is a
fourth. So this script fetches ``unicode.cpp``/``unicode-data.cpp`` verbatim
from the pinned tag, compiles them with MSVC (the same toolchain family
llama.cpp's official Windows release binaries use) alongside a tiny harness
that calls the real ``unicode_regex_split()``, and times it against
adversarial input in a subprocess with a hard wall-clock timeout (std::regex
offers no interruption mechanism, so a timeout is the only way to bound a
genuine hang).

It also extracts the CUSTOM, non-backtracking fast-path dispatch table from
``unicode_regex_split_custom()`` (an exact-string match against a handful of
known-safe patterns - GPT2, LLAMA3, QWEN2, QWEN35, K2's ``\\p{Han}+``,
AFMoE's ``\\p{AFMoE_digits}``, the Gemma4/Sarvam newline-only pattern, and
tiny_aya's digit-grouping pattern - that never reach ``std::regex`` at all)
directly from the fetched source, so a pattern upstream has already hardened
this way is correctly skipped rather than needlessly (though harmlessly)
retested.

KNOWN LIMITATION: needs an MSVC toolchain (Visual Studio Build Tools, via
``vswhere``) and network access. It has no Linux/macOS path and is not part
of the pytest suite - run it by hand when re-assessing the pin, or after a
``_PINNED_TAG`` bump in ``setup_llama.py``.

Usage:
    python scripts/check_pretokenizer_redos.py                  # the pinned tag
    python scripts/check_pretokenizer_redos.py --ref b10375      # a specific tag
    python scripts/check_pretokenizer_redos.py --out report.json # full JSON dump
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

# Several patterns embed real non-ASCII characters (CJK ranges, fullwidth
# punctuation), and the default Windows console codepage cannot encode them -
# reconfigure rather than let a print crash the run after the expensive part
# (fetch, compile, sweep) already finished.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

_REPO = "ggml-org/llama.cpp"
_SRC_FILES = ("llama-vocab.cpp", "unicode.cpp", "unicode.h", "unicode-data.cpp",
              "unicode-data.h")
_TIMEOUT_S = 3.0
_SIZES = (2000, 8000, 32000)
_ESCALATE_SIZE = 128000

_PROBE_CPP = r"""
// Generated by scripts/check_pretokenizer_redos.py - calls the real,
// unmodified unicode_regex_split() on one pattern against one text, and
// reports elapsed wall-clock time.
#include "unicode.h"

#include <chrono>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

static std::string read_file(const char * path) {
    std::ifstream f(path, std::ios::binary);
    std::stringstream buf;
    buf << f.rdbuf();
    return buf.str();
}

int main(int argc, char ** argv) {
    if (argc < 3) {
        std::fprintf(stderr, "usage: probe <pattern-file> <text-file>\n");
        return 2;
    }
    const std::string pattern = read_file(argv[1]);
    const std::string text    = read_file(argv[2]);
    const std::vector<std::string> regex_exprs = { pattern };

    const auto t0 = std::chrono::steady_clock::now();
    try {
        const auto words = unicode_regex_split(text, regex_exprs);
        const auto t1 = std::chrono::steady_clock::now();
        const double ms = std::chrono::duration<double, std::milli>(t1 - t0).count();
        std::printf("OK %.3f %zu\n", ms, words.size());
        return 0;
    } catch (const std::exception & e) {
        const auto t1 = std::chrono::steady_clock::now();
        const double ms = std::chrono::duration<double, std::milli>(t1 - t0).count();
        std::printf("ERROR %.3f %s\n", ms, e.what());
        return 1;
    }
}
"""


def _pinned_tag() -> str:
    """localm's own confirmed-good pin, read live rather than restated -
    a copy here would silently go stale the next time it advances."""
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from localm.setup_llama import _PINNED_TAG
    return _PINNED_TAG


def _fetch(ref: str, name: str, dest: Path) -> None:
    url = f"https://raw.githubusercontent.com/{_REPO}/{ref}/src/{name}"
    req = urllib.request.Request(url, headers={"User-Agent": "localm-redos-check"})
    with urllib.request.urlopen(req, timeout=30) as r:
        if r.status != 200:
            raise SystemExit(f"fetch {name} @ {ref}: HTTP {r.status}")
        data = r.read()
    if len(data) < 200:
        raise SystemExit(f"fetch {name} @ {ref}: suspiciously small ({len(data)} "
                         f"bytes) - likely an error page, not real source")
    dest.write_bytes(data)


# --------------------------------------------------------------------------- #
#  String-literal-aware C++ extraction (respects "..." and // comments, so a
#  literal '{' or '}' inside a regex like \p{N}{1,3} is never mistaken for a
#  block delimiter, and a commented-out "original" pattern is never picked up
#  as if it were live code).
# --------------------------------------------------------------------------- #

def _unescape_cpp_string(raw: str) -> str:
    out = []
    i, n = 0, len(raw)
    simple = {"n": "\n", "t": "\t", "r": "\r", "\\": "\\", '"': '"', "'": "'", "0": "\0"}
    while i < n:
        c = raw[i]
        if c == "\\" and i + 1 < n and raw[i + 1] in simple:
            out.append(simple[raw[i + 1]])
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def _scan_string_literals_from(text: str, start: int):
    """Yield each top-level (non-comment) string literal starting at or after
    *start*, stopping when the enclosing brace block (opened at the first '{'
    encountered) closes. Used both for a `regex_exprs = { ... };` initializer
    and, with start pointed at a bare statement, for scanning a function body
    for scattered `regex_expr == "..."` comparisons (brace-tracked so it stops
    at that function's closing brace, not the next one)."""
    literals = []
    i = start
    depth = 0
    in_string = False
    escape_next = False
    in_comment = False
    cur = None
    opened = False
    while i < len(text):
        c = text[i]
        if in_comment:
            if c == "\n":
                in_comment = False
            i += 1
            continue
        if in_string:
            if escape_next:
                cur.append(c)
                escape_next = False
            elif c == "\\":
                cur.append(c)
                escape_next = True
            elif c == '"':
                in_string = False
                literals.append("".join(cur))
                cur = None
            else:
                cur.append(c)
            i += 1
            continue
        if c == "/" and i + 1 < len(text) and text[i + 1] == "/":
            in_comment = True
            i += 2
            continue
        if c == '"':
            in_string = True
            cur = []
            i += 1
            continue
        if c == "{":
            depth += 1
            opened = True
            i += 1
            continue
        if c == "}":
            depth -= 1
            i += 1
            if opened and depth <= 0:
                break
            continue
        i += 1
    return literals, i


def extract_regex_exprs_blocks(vocab_src: str):
    """Every `regex_exprs = { ... };` initializer, each item unescaped from
    C++ source-literal form to the real regex string llama.cpp constructs."""
    blocks = []
    marker = "regex_exprs = {"
    idx = 0
    while True:
        start = vocab_src.find(marker, idx)
        if start == -1:
            break
        brace_start = start + len(marker) - 1
        literals, end = _scan_string_literals_from(vocab_src, brace_start)
        blocks.append({"patterns": [_unescape_cpp_string(s) for s in literals],
                       "line": vocab_src.count("\n", 0, start) + 1})
        idx = end
    return blocks


def extract_custom_triggers(unicode_src: str) -> dict:
    """Exact-string patterns unicode_regex_split_custom() intercepts BEFORE
    std::regex, extracted from its own dispatch body rather than hardcoded -
    so a future tag that adds another fast path is picked up automatically."""
    anchor = unicode_src.find("static std::vector<size_t> unicode_regex_split_custom(")
    if anchor == -1:
        return {}
    body_start = unicode_src.find("{", anchor)
    literals, _ = _scan_string_literals_from(unicode_src, body_start)
    # Every literal in this function's body IS a dispatch-comparison target -
    # confirmed by reading the function (each `if (regex_expr == "...")`).
    return {_unescape_cpp_string(s): True for s in literals}


# --------------------------------------------------------------------------- #
#  MSVC toolchain
# --------------------------------------------------------------------------- #

def _find_vcvars64() -> str:
    # Derived from the environment Windows itself sets, not a hardcoded C:
    # path - vswhere's own install location is fixed by Microsoft, but the
    # drive/folder name it lives under is not.
    program_files_x86 = os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")  # hygiene-ok: last-resort fallback only, the env var wins whenever it is set
    vswhere = Path(program_files_x86) / "Microsoft Visual Studio" / "Installer" / "vswhere.exe"
    if not vswhere.exists():
        raise SystemExit(
            "vswhere.exe not found - this check needs a Visual Studio / Build "
            "Tools installation with the C++ workload. Install it, or run this "
            "on a box that has it.")
    out = subprocess.run(
        [str(vswhere), "-latest", "-products", "*",
         "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
         "-property", "installationPath"],
        capture_output=True, text=True, timeout=30)
    install_path = out.stdout.strip().splitlines()[0] if out.stdout.strip() else None
    if not install_path:
        raise SystemExit("vswhere found no VS install with the C++ (VC.Tools.x86.x64) "
                         "component - install the 'Desktop development with C++' "
                         "workload.")
    vcvars = Path(install_path) / "VC" / "Auxiliary" / "Build" / "vcvars64.bat"
    if not vcvars.exists():
        raise SystemExit(f"vcvars64.bat not found under {install_path}")
    return str(vcvars)


def compile_probe(workdir: Path) -> Path:
    """Compile via a generated .bat file, not a shell=True string: cmd.exe's
    quote-stripping for `/c "..."` and subprocess's own list-mode re-quoting
    of an already-quoted string fight each other, and a .bat file sidesteps
    both - each line carries its own quoting, no shell interpolation of a
    constructed string. No untrusted input reaches this: every path here is
    either this script's own tempdir or vswhere's own output."""
    vcvars = _find_vcvars64()
    probe_cpp = workdir / "probe.cpp"
    probe_cpp.write_text(_PROBE_CPP, encoding="utf-8")
    exe = workdir / "probe.exe"
    unicode_cpp = workdir / "unicode.cpp"
    unicode_data_cpp = workdir / "unicode-data.cpp"
    bat_lines = [
        "@echo off",
        'call "' + str(vcvars) + '"',
        # /Fo: matters: cl.exe otherwise writes .obj intermediates to the
        # CALLING PROCESS's cwd (not the source files' directory, and not
        # wherever /Fe: points), so without it every run of this script
        # leaves stray build artifacts in whatever directory it was invoked
        # from. Its value ends in a forward slash, not a backslash: a
        # Windows command line parses a trailing BACKSLASH immediately
        # before a closing quote as an ESCAPED quote rather than a
        # terminator, silently swallowing everything after it into one
        # malformed argument. cl.exe accepts either separator, so a forward
        # slash sidesteps the ambiguity outright.
        ("cl.exe /nologo /O2 /EHsc /std:c++17 "
         '/I"' + str(workdir) + '" "' + str(probe_cpp) + '" "' + str(unicode_cpp) +
         '" "' + str(unicode_data_cpp) + '" /Fo:"' + str(workdir) + '/" '
         '/Fe:"' + str(exe) + '"'),
    ]
    bat = workdir / "build.bat"
    bat.write_text("\r\n".join(bat_lines) + "\r\n", encoding="utf-8")
    r = subprocess.run([str(bat)], capture_output=True, text=True, timeout=120)
    if not exe.exists():
        raise SystemExit(f"MSVC compile failed:\n{r.stdout}\n{r.stderr}")
    return exe


# --------------------------------------------------------------------------- #
#  Adversarial probing
# --------------------------------------------------------------------------- #

def _bait_chars(pattern: str):
    chars = []
    if "\\d" in pattern or "\\p{N}" in pattern or "[0-9]" in pattern:
        chars.append(("digit", "5"))
    if "\\p{L}" in pattern or "A-Za-z" in pattern or "a-z" in pattern:
        chars.append(("letter", "a"))
    if "\\s" in pattern or "\\p{Z}" in pattern:
        chars.append(("space", " "))
    if "\\p{P}" in pattern or "\\p{S}" in pattern:
        chars.append(("punct", "."))
    if any(ord(c) >= 0x2E80 for c in pattern):
        chars.append(("cjk", "\u4e2d"))
    seen, out = set(), []
    for label, ch in chars:
        if ch in seen:
            continue
        seen.add(ch)
        out.append((label, ch))
        if len(out) == 3:
            break
    return out or [("fallback", "a")]


def _run_probe(exe: Path, pat_file: Path, txt_file: Path, pattern: str, text: str):
    pat_file.write_bytes(pattern.encode("utf-8"))
    txt_file.write_bytes(text.encode("utf-8"))
    t0 = time.time()
    try:
        r = subprocess.run([str(exe), str(pat_file), str(txt_file)],
                           capture_output=True, text=True, timeout=_TIMEOUT_S)
    except subprocess.TimeoutExpired:
        return {"status": "TIMEOUT", "wall_s": round(time.time() - t0, 3)}
    m = re.match(r"^(OK|ERROR) ([\d.]+) (.*)$", r.stdout.strip())
    if not m:
        return {"status": "UNPARSEABLE", "raw": r.stdout.strip(), "stderr": r.stderr.strip()}
    status, ms, rest = m.groups()
    return {"status": status, "ms": float(ms), "detail": rest}


def _verdict(times_ms):
    pts = [t for t in times_ms if t is not None]
    if len(pts) < 2:
        return "insufficient-data (errored/timed out before scaling could be read)"
    ratios = [pts[i] / max(pts[i - 1], 0.01) for i in range(1, len(pts))]
    avg = sum(ratios) / len(ratios)
    if avg < 6:
        return f"linear-ish (avg {avg:.2f}x per 4x length)"
    if avg < 30:
        return f"QUADRATIC-ish (avg {avg:.2f}x per 4x length)"
    if avg < 100:
        return f"CUBIC-OR-WORSE (avg {avg:.2f}x per 4x length)"
    return f"SEVERE (avg {avg:.2f}x per 4x length)"


def sweep(exe: Path, patterns: list, workdir: Path, log=lambda s: None) -> dict:
    pat_file, txt_file = workdir / "s_pat.bin", workdir / "s_text.bin"
    results = []
    for idx, pattern in enumerate(patterns):
        log(f"[{idx + 1}/{len(patterns)}] {pattern[:60]!r}...")
        entry = {"pattern": pattern, "probes": []}
        for label, ch in _bait_chars(pattern):
            times_ms, runs, trouble = [], [], False
            for size in _SIZES:
                res = _run_probe(exe, pat_file, txt_file, pattern, ch * size)
                runs.append({"size": size, **res})
                if res["status"] == "OK":
                    times_ms.append(res["ms"])
                    trouble = trouble or res["ms"] > 1500
                else:
                    times_ms.append(None)
                    trouble = True
                    break
            if not trouble and all(t is not None for t in times_ms) and times_ms[-1] > 50:
                res = _run_probe(exe, pat_file, txt_file, pattern, ch * _ESCALATE_SIZE)
                runs.append({"size": _ESCALATE_SIZE, **res})
                times_ms.append(res["ms"] if res["status"] == "OK" else None)
            entry["probes"].append({"bait": label, "char": ch, "runs": runs,
                                    "verdict": _verdict(times_ms)})
        results.append(entry)
    return results


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ref", default=None, help="llama.cpp tag/commit (default: the pin)")
    ap.add_argument("--out", default=None, help="write the full JSON report here")
    args = ap.parse_args()

    ref = args.ref or _pinned_tag()
    print(f"# fetching llama.cpp @ {ref}", file=sys.stderr)

    with tempfile.TemporaryDirectory(prefix="redos-check-") as tmp:
        workdir = Path(tmp)
        for name in _SRC_FILES:
            _fetch(ref, name, workdir / name)

        vocab_src = (workdir / "llama-vocab.cpp").read_text(encoding="utf-8")
        unicode_src = (workdir / "unicode.cpp").read_text(encoding="utf-8")

        blocks = extract_regex_exprs_blocks(vocab_src)
        distinct = sorted({p for b in blocks for p in b["patterns"]})
        custom = extract_custom_triggers(unicode_src)
        to_test = [p for p in distinct if p not in custom]

        print(f"# {len(blocks)} regex_exprs blocks, {len(distinct)} distinct patterns: "
              f"{len(custom)} custom-handled (skip, never reach std::regex), "
              f"{len(to_test)} to drive through the real std::regex/std::wregex",
              file=sys.stderr)

        print("# compiling probe harness with MSVC...", file=sys.stderr)
        exe = compile_probe(workdir)

        results = sweep(exe, to_test, workdir, log=lambda s: print(s, file=sys.stderr))

    report = {"ref": ref, "n_blocks": len(blocks), "n_distinct": len(distinct),
              "custom_handled": sorted(custom), "tested": results}

    # Written before the summary print below: the report is the durable
    # artifact and must survive even if console rendering hits a problem.
    if args.out:
        Path(args.out).write_text(json.dumps(report, indent=1, ensure_ascii=False),
                                  encoding="utf-8")
        print(f"full report: {args.out}", file=sys.stderr)

    concerning = []
    for entry in results:
        for probe in entry["probes"]:
            if "linear-ish" not in probe["verdict"]:
                concerning.append((entry["pattern"], probe["bait"], probe["verdict"]))

    print(f"\n=== {len(to_test)} patterns driven through the real runtime, "
          f"{len(concerning)} probe(s) flagged ===\n")
    for pattern, bait, verdict in concerning:
        print(f"  [{bait}] {verdict}")
        print(f"    {pattern[:100]}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
