# SPDX-License-Identifier: AGPL-3.0-or-later
"""Check the committed CI requirement sets in .github/requirements/.

Two checks, both read only:

  drift       Regenerates every set with the commands in
              .github/requirements/README.md into a temporary directory and
              compares it with the committed file, ignoring the two header lines
              that record the output path. A difference means the committed set
              no longer matches what the commands produce today.
  advisories  Looks up every pinned name==version in the OSV database (which
              includes the GitHub advisory database) and reports each one that
              has an advisory. A local version label such as ``+cpu`` is dropped
              for the lookup.

Exit codes: 0 clean, 1 a set drifted or a pin has an advisory, 2 a check could not
run (uv missing, network down). Nothing is written to the repository.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / ".github" / "requirements"
SETS = ("torch-cpu.txt", "mutmut.txt")
OSV_BATCH_URL = "https://api.osv.dev/v1/querybatch"
_PIN = re.compile(r"^([A-Za-z0-9._-]+)==(\S+)", re.MULTILINE)
_HEADER_LINES = ("# This file was autogenerated", "#    uv pip compile")
_PLATFORM = ["--python-version", "3.12", "--python-platform", "x86_64-manylinux_2_28"]


class CheckError(Exception):
    """A check could not run, as opposed to running and finding a problem."""


def pins(text: str) -> dict[str, str]:
    """Map each pinned distribution name (lowercased) to its version."""
    return {name.lower(): version for name, version in _PIN.findall(text)}


def normalize(text: str) -> str:
    """Drop the header lines that record how and where the file was written."""
    return "".join(line for line in text.splitlines(keepends=True)
                   if not line.startswith(_HEADER_LINES))


def drift(committed: str, regenerated: str) -> list[str]:
    """Unified diff lines between two sets, empty when they agree."""
    return list(difflib.unified_diff(
        normalize(committed).splitlines(), normalize(regenerated).splitlines(),
        "committed", "regenerated", lineterm=""))


def _run(cmd: list[str], *, cwd: Path, stdin: str | None = None) -> None:
    try:
        subprocess.run(cmd, cwd=cwd, input=stdin, text=True, check=True,
                       capture_output=True)
    except FileNotFoundError as exc:
        raise CheckError(f"{cmd[0]} is not installed") from exc
    except subprocess.CalledProcessError as exc:
        raise CheckError(f"{' '.join(cmd)} failed: {exc.stderr.strip()[-600:]}") from exc


def regenerate(workdir: Path, uv: str = "uv") -> dict[str, str]:
    """Rebuild every committed set in *workdir* and return the texts by file name."""
    torch_pin = pins((REQUIREMENTS / "torch-cpu.txt").read_text(encoding="utf-8"))["torch"]
    _run([uv, "pip", "compile", "-", "--no-config", "--no-emit-package", "setuptools",
          "--generate-hashes", "--emit-index-url", *_PLATFORM,
          "--index-url", "https://download.pytorch.org/whl/cpu",
          "--extra-index-url", "https://pypi.org/simple",
          "--index-strategy", "unsafe-best-match", "-o", "torch-cpu.txt"],
         cwd=workdir, stdin=f"torch=={torch_pin}\n")
    mutmut_pin = pins((REQUIREMENTS / "mutmut.txt").read_text(encoding="utf-8"))["mutmut"]
    _run([uv, "export", "--quiet", "--locked", "--no-emit-project", "--extra", "dev",
          "--no-hashes", "--no-header", "-o", str(workdir / "mutmut-constraints.txt")],
         cwd=ROOT)
    _run([uv, "pip", "compile", "-", "--no-config", "-c", "mutmut-constraints.txt",
          "--generate-hashes", *_PLATFORM, "-o", "mutmut.txt"],
         cwd=workdir, stdin=f"mutmut=={mutmut_pin}\n")
    return {name: (workdir / name).read_text(encoding="utf-8") for name in SETS}


def _post_json(url: str, body: dict) -> dict:
    req = urllib.request.Request(url, data=json.dumps(body).encode(),
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:  # noqa: S310
            return json.load(resp)
    except OSError as exc:
        raise CheckError(f"advisory lookup failed: {exc}") from exc


def advisories(found: dict[str, str],
               post: Callable[[str, dict], dict] = _post_json) -> dict[str, list[str]]:
    """Advisory ids per ``name==version`` for the pins that have any."""
    items = sorted(found.items())
    queries = [{"package": {"name": name, "ecosystem": "PyPI"},
                "version": version.split("+", 1)[0]} for name, version in items]
    results: list[dict] = []
    for start in range(0, len(queries), 500):
        reply = post(OSV_BATCH_URL, {"queries": queries[start:start + 500]})
        results.extend(reply.get("results", []))
    if len(results) != len(queries):
        raise CheckError(f"advisory lookup answered {len(results)} of {len(queries)} queries")
    if any(r.get("next_page_token") for r in results):
        raise CheckError("advisory lookup returned a partial page")
    return {f"{name}=={version}": [v["id"] for v in result["vulns"]]
            for (name, version), result in zip(items, results, strict=True)
            if result.get("vulns")}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--only", choices=("drift", "advisories"))
    parser.add_argument("--requirements-dir", type=Path, default=REQUIREMENTS,
                        help="read the committed sets from this directory")
    args = parser.parse_args(argv)
    committed = {name: (args.requirements_dir / name).read_text(encoding="utf-8")
                 for name in SETS}
    failed = False
    try:
        if args.only in (None, "drift"):
            uv = shutil.which("uv")
            if uv is None:
                raise CheckError("uv is not installed")
            with tempfile.TemporaryDirectory() as tmp:
                fresh = regenerate(Path(tmp), uv)
            for name in SETS:
                lines = drift(committed[name], fresh[name])
                if lines:
                    failed = True
                    print(f"DRIFT {name}: the regenerated set differs from the committed one")
                    print("\n".join(lines[:200]))
                else:
                    print(f"ok    {name}: matches a fresh regeneration")
        if args.only in (None, "advisories"):
            every = {k: v for name in SETS for k, v in pins(committed[name]).items()}
            hits = advisories(every)
            for pin, ids in hits.items():
                failed = True
                print(f"ADVISORY {pin}: {', '.join(ids)}")
            if not hits:
                print(f"ok    no advisory against any of the {len(every)} pinned versions")
    except CheckError as exc:
        print(f"could not check: {exc}", file=sys.stderr)
        return 2
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
