# SPDX-License-Identifier: AGPL-3.0-or-later
"""Graceful failure + an autogenerated, user-editable bug report.

When something goes wrong, localm should fail like a good citizen: say *what*
broke and *why* in plain language, then offer to send a prefilled report the
user can read and edit before anything leaves their machine.

Channels, in the order that actually works for a tester:
  * **hosted send** (`--send`, or menu [1]) - uploads through the account-less
    Cloudflare Worker proxy, which files the GitHub issue server-side. No
    GitHub account, ever - this is the only channel that actually creates an
    issue automatically. See the "Upload channel" section in transport.py.
  * **email** - opens the user's mail app prefilled to the maintainer. Works for
    anyone, including a tester on a still-private repo.
  * **do it yourself** - the report is always saved to a file, so the user can
    drop it on Discord, paste it, or attach it however they like.

There is NO "open a GitHub issue in your browser" channel.

Diagnostics aim to be *actually useful* - the data a maintainer needs to act on a
report - while staying safe:
  * OS / arch / Python, GPU vendor + NVIDIA driver / CUDA capability, the chosen
    and recommended backend, and the *names* of provisioned native libraries.
  * App state: the loaded model, effective backend, context ceiling, session
    (privacy) mode, debug flag, and enabled plugins.
  * An ALLOWLISTED, scrubbed subset of config (context sizing, ports, media URLs,
    privacy mode) - never the whole config, so a future secret-bearing key cannot
    leak; path values are home-scrubbed and URL values credential-scrubbed.
  * Versions of the dependencies that shape a failure (native runtime, HF + server
    stacks).
  * The in-memory recent-activity log (INFO+ breadcrumbs; the raw model output is
    DEBUG-level, so it never enters this in-process ring buffer) and, for a GUI
    report, the browser context + recent JS console errors.

What is NEVER collected: the API key, environment variables (which can hold one),
config secrets, or the raw chat/transcript content. The user also reviews and
edits the report before sending, regardless.

Chat content DOES land in the on-disk debug log at DEBUG level when --debug (or
keep_diagnostics) is on and the session is not privacy mode. What must never
happen is that content reaching a REPORT: the digest builder
(localm/_log_digest.py) drops every record from a known
debug_content_enabled()-gated write site (the raw model reply, a memory-embed
content snippet, a web-tool query, the assembled chat prompt) before it is ever
collapsed or classified, so none of them can appear in ``_recent_log_tail``
regardless of what the content itself says.
"""

from __future__ import annotations

from localm.bugreport._common import (
    console, MAINTAINER_EMAIL,
)
from localm.bugreport.errors import (
    LocalmError, RateLimitedError,
)
from localm.bugreport.scrub import (
    _scrub_home, _scrub_url_creds, _QUERY_SECRET_RE, _HEADER_SECRET_RE, _JSON_SECRET_RE,
    _scrub_query_and_header_secrets, _BEARER_RE, _APIKEY_RE, _scrub_secrets,
)
from localm.bugreport.diagnostics import (
    _localm_version, _runtime_libs, _NOT_DETECTED, _gpu_inventory, collect_diagnostics,
    _SAFE_CONFIG_KEYS, _REPORTED_DISTS, _loaded_model_info, _runtime_state,
    _enabled_plugins, _safe_config_subset, _config_unreadable, _dependency_versions,
    _ring_activity,
)
from localm.bugreport.logs import (
    _LOG_TAIL_READ_BYTES, _find_run_log, _LOG_UNAVAILABLE_NO_FILE, _log_failure_reason,
    _recent_log_tail_result, _recent_log_tail, _HANG_TRACE_MAX_AGE_S,
    _recent_hang_traces, live_server_hang_trace,
)
from localm.bugreport.assembly import (
    _format_error, _kv_lines, _app_state_lines, build_report, _report_footer,
    _strip_report_footer, _client_lines, report_title, _TRACE_REPORT_LIMIT,
    trim_trace_for_report,
)
from localm.bugreport.persistence import (
    save_report, _SAVE_REPORT_LOCK, save_user_report,
)
from localm.bugreport.transport import (
    _MAX_PREFILL_BODY, _truncate_body, mailto_url, upload_config, upload_available,
    _retry_after_from, _classify_url_error, upload_report,
)
from localm.bugreport.consent import (
    report_failure, offer_to_send,
)
from localm.bugreport.handlers import (
    _handle_main_exception, _handle_thread_exception, install_global_handlers,
    install_asyncio_handler,
)
from localm.bugreport.crash_guard import (
    _diagnostics_allowed, _crash_dir, _crash_marker_path, _crash_trace_path,
    _exit_path_for_marker, _read_exit_record, _trace_path_for_marker,
    _all_crash_markers, _crash_stopping_path, _trace_path_for_stopping_record,
    _all_crash_stopping_records, arm_crash_guard, armed_instance_id, clear_crash_marker,
    release_crash_trace, disarm_crash_guard,
)
from localm.bugreport.crash_recovery import (
    _NATIVE_OP_LINE_RE, _TRUNCATION_CHECK_READ_BYTES, _WIN_FAULT_LINE_RE,
    _POSIX_FAULT_LINE_RE, _WIN_FAULT_CODE_RE, _is_fatal_fault_description,
    _fatal_fault_line, _raw_tail_truncation_signal, _first_chance_codes,
    _classify_prior_death, _report_one_crash_marker, _report_one_stopping_record,
    check_and_report_prior_crash,
)

_handlers_installed = False
_crash_trace_fh = None   # kept alive so faulthandler can write to it
_crash_trace_instance_id = None   # which instance_id currently owns _crash_trace_fh
_armed_instance_id = None   # instance_id of the last arm_crash_guard() in THIS process

__all__ = [
    "_all_crash_markers", "_all_crash_stopping_records", "_APIKEY_RE",
    "_app_state_lines", "arm_crash_guard", "_armed_instance_id", "armed_instance_id",
    "_BEARER_RE", "build_report", "check_and_report_prior_crash",
    "_classify_prior_death", "_classify_url_error", "clear_crash_marker",
    "_client_lines", "collect_diagnostics", "_config_unreadable", "console",
    "_crash_dir", "_crash_marker_path", "_crash_stopping_path", "_crash_trace_fh",
    "_crash_trace_instance_id", "_crash_trace_path", "_dependency_versions",
    "_diagnostics_allowed", "disarm_crash_guard", "_enabled_plugins",
    "_exit_path_for_marker", "_fatal_fault_line", "_find_run_log",
    "_first_chance_codes", "_format_error", "_gpu_inventory", "_handle_main_exception",
    "_handle_thread_exception", "_handlers_installed", "_HANG_TRACE_MAX_AGE_S",
    "_HEADER_SECRET_RE", "install_asyncio_handler", "install_global_handlers",
    "_is_fatal_fault_description", "_JSON_SECRET_RE", "_kv_lines",
    "live_server_hang_trace", "_loaded_model_info", "_localm_version", "LocalmError",
    "_log_failure_reason", "_LOG_TAIL_READ_BYTES", "_LOG_UNAVAILABLE_NO_FILE",
    "mailto_url", "MAINTAINER_EMAIL", "_MAX_PREFILL_BODY", "_NATIVE_OP_LINE_RE",
    "_NOT_DETECTED", "offer_to_send", "_POSIX_FAULT_LINE_RE", "_QUERY_SECRET_RE",
    "RateLimitedError", "_raw_tail_truncation_signal", "_read_exit_record",
    "_recent_hang_traces", "_recent_log_tail", "_recent_log_tail_result",
    "release_crash_trace", "report_failure", "_report_footer",
    "_report_one_crash_marker", "_report_one_stopping_record", "report_title",
    "_REPORTED_DISTS", "_retry_after_from", "_ring_activity", "_runtime_libs",
    "_runtime_state", "_SAFE_CONFIG_KEYS", "_safe_config_subset", "save_report",
    "_SAVE_REPORT_LOCK", "save_user_report", "_scrub_home",
    "_scrub_query_and_header_secrets", "_scrub_secrets", "_scrub_url_creds",
    "_strip_report_footer", "_trace_path_for_marker", "_trace_path_for_stopping_record",
    "_TRACE_REPORT_LIMIT", "trim_trace_for_report", "_truncate_body",
    "_TRUNCATION_CHECK_READ_BYTES", "upload_available", "upload_config",
    "upload_report", "_WIN_FAULT_CODE_RE", "_WIN_FAULT_LINE_RE",
]
